bigcommerce/cornerstone

- assets/scss/components/foundation/dropdown/_dropdown.scss
> MERC-404 Fix dropdown menus

- assets/config.js
- assets/scss/theme.scss
- package.json
@mickr @mcampa @grishmarupani @bc-ejoe
> MERC-353 updating package.json and more to use npmjs

- assets/js/theme/common/product-details.js
- assets/scss/components/citadel/forms/_forms.scss
- assets/scss/settings/stencil/productView/_settings.scss
- templates/components/products/options/date.html
- templates/components/products/options/input-checkbox.html
- templates/components/products/options/input-file.html
- templates/components/products/options/input-numbers.html
- templates/components/products/options/input-text.html
- templates/components/products/options/product-list.html
- templates/components/products/options/set-radio.html
- templates/components/products/options/set-rectangle.html
- templates/components/products/options/set-select.html
- templates/components/products/options/swatch.html
- templates/components/products/options/textarea.html
@hegrec @mickr @sherrybc @bc-ejoe 
Depends on 
https://github.com/bigcommerce/bigcommerce/pull/12568 (merged)
https://github.com/bigcommerce/bigcommerce/pull/12603 (merged)
> MERC-295 Mark or Hide out-of-stock products attributes

- assets/config.js
- assets/scss/theme.scss
- package.json
Migrate to Stencil-Citadel - We have moved Citadel to a different repo
> Migrate to Stencil-Citadel

- assets/js/theme/cart/shipping-estimator.js
- templates/components/cart/shipping-estimator.html
- when default country does not have states, show input field 
- update state validation; only validate when it is a dropdown
@mcampa @mickr @bc-ejoe
>  MERC-341 fix state validation in shipping estimator

- templates/components/products/price.html
- templates/pages/compare.html
https://jira.bigcommerce.com/browse/MERC-346
@mickr @bc-ejoe @sherrybc
> MERC-346 'Excluding tax' persists on storefront unnecessarily

- assets/js/theme/cart/shipping-estimator.js
* Fix ESLint throwing an error due to unused var.
> ESLint throwing an error due to unused variable.

- config.json
> MERC-429: bump version to 1.1.0

- templates/components/faceted-search/facets/rating.html
MERC-400 - Rating Facet
* Add selected state for rating facet item.
> MERC-400 - Rating Facet

- lang/en.json
- templates/pages/newsletter/thanks.html
- templates/pages/unsubscribe.html
@hegre @mickr @sherrybc 
depending on https://github.com/bigcommerce/bigcommerce/pull/12795
> MERC-472 unsubscribe template file

- templates/pages/brand.html
- templates/pages/category.html
> MERC-417 brand image

- config.json
Update the documentation_url in the config.json to point to
https://support.bigcommerce.com/articles/Public/Cornerstone-Theme-Manual
https://jira.bigcommerce.com/browse/MERC-543
ping @mcampa @sherrybc @mickr @hegrec
> MERC-543 Update config.json to point to correct release notes url

- templates/components/common/footer.html
ping @sherrybc @mcampa @hegrec
> MERC-584 Updating powered by based on rebranding.

- assets/scss/components/foundation/modal/_modal.scss
@hegrec @mickr @bc-ejoe @sherrybc @bc-ranji
> MERC-586 Fix modal vertical centering on small devices

- package.json
Adding correct version to package.json
> Adding correct version to package.json

- assets/scss/layouts/header/_header.scss
- config.json
- schema.json
- templates/components/common/header.html
mobile screenshots (margin as is asked by design)
image logo
text logo
ipad size:
text logo
@mcampa @mickr @bc-miko-ademagic @bc-ejoe
> MERC-611 position logo for theme editor

- assets/js/app.js
- package.json
- webpack.conf.js
> MERC-684: Babel polyfill for Symbol

- assets/js/test-unit/theme/common/faceted-search.spec.js
- assets/js/theme/brand.js
- assets/js/theme/category.js
- assets/js/theme/common/faceted-search.js
- assets/js/theme/search.js
- assets/scss/components/stencil/facetedSearch/_facetedSearch.scss
- templates/components/brand/show-more.html
- templates/components/category/show-more.html
- templates/components/faceted-search/facets/hierarchy.html
- templates/components/faceted-search/facets/multi.html
- templates/components/faceted-search/show-more-facets.html
- templates/components/search/show-more.html
MERC-75 Faceted Search Up to 500 Facets
* Add template to be rendered in modal for search, brand, category
* Refactor javascript for show more functionality to rely on `has_more_results` to show the show more toggle which will fire the modal for all facet results.
> MERC-75 Faceted Search Up to 500 Facets

- config.json
- package.json
@mickr @sherrybc @mcampa @hegrec
> MERC-612: Cornerstone v1.2.0 release

- assets/js/theme/common/product-details.js
> MERC-639 Default option shown even when item has zero-stock for option

- templates/components/products/options/set-select.html
MERC-709 - Add empty value to default option
> MERC-709 - Add empty value to default option.

- assets/js/theme/common/product-details.js
> MERC-639 ESlint Bug fix

- assets/js/theme/common/product-details.js
@mickr @sherrybc @bc-ejoe @hegrec
> MERC-678 display OOS message and update view when the default attributes are OOS

- templates/components/products/featured.html
MERC-701 - Firefox fix for featured products partial.
> MERC-701 - Firefox fix for featured products partial.

- config.json
- package.json
> MERC-717 - Bump Cornerstone to v1.2.1

- templates/pages/brands.html
@mickr @hegrec @sherrybc @bc-ejoe 
Can be safely merge before the bcapp changes
> MERC-725 Brands pagination

- config.json
- package.json
- templates/pages/category.html
@mickr @bc-ejoe @sherrybc @mcampa
> THEME-1056: Use larger category image size

- config.json
- schema.json
- templates/components/account/order-contents.html
- templates/components/account/orders-list.html
- templates/components/account/returns-list.html
- templates/components/blog/post.html
- templates/components/cart/content.html
- templates/components/cart/preview.html
- templates/components/common/cart-preview.html
- templates/components/common/store-logo.html
- templates/components/products/card.html
- templates/components/products/list-item.html
- templates/components/products/modals/writeReview.html
- templates/components/products/options/product-list.html
- templates/components/products/options/swatch.html
- templates/components/products/product-view.html
- templates/pages/account/orders/invoice.html
- templates/pages/brand.html
- templates/pages/brands.html
- templates/pages/category.html
- templates/pages/compare.html
update schema.json for Logo
update schema.json for product images
add subtext about Desktop sizing
update the display order of the settings in TE 
@mcampa @mickr @bc-ejoe 
MERC-616 also has changes in stencil-paper and stencil-editor
> MERC-616, MERC-608 logo and product image resize functionality

- assets/scss/components/stencil/account/_account.scss
- assets/scss/components/stencil/cart/_cart.scss
- assets/scss/components/stencil/previewCart/_previewCart.scss
- assets/scss/components/stencil/productView/_productView.scss
- templates/components/account/order-contents.html
- templates/components/account/orders-list.html
- templates/components/cart/preview.html
orders
orders detail
cart
cart preview
@mcampa @mickr @bc-ejoe @deepa2083
> MERC-888 update orders and cart product images

- assets/scss/components/stencil/cart/_cart.scss
- templates/components/cart/content.html
temporary fix for enlarged gift certificate image in IE10, 11, and firefox 41
@mcampa @bc-ong @bc-miko-ademagic
> MERC-930 update gift certificate img

- templates/components/faceted-search/facets/hierarchy-children.html
- templates/components/faceted-search/facets/hierarchy.html
- templates/components/faceted-search/facets/multi.html
- templates/components/faceted-search/facets/rating.html
- templates/components/faceted-search/selected-facets.html
- templates/components/faceted-search/show-more-facets.html
inform Googlebot not to follow the faceted search links
@mcampa @bc-ong
> MERC-948 add nofollow attributes to faceted search links

- assets/js/theme/common/product-details.js
- package.json
- templates/layout/base.html
Berfore merging we need to:
- merge `stencil-utils` PR https://github.com/bigcommerce/stencil-utils/pull/66
- publish `stencil-utils` to npm
@sherrybc
> MERC-962 zoom image fix

- assets/js/theme/common/product-details.js
- assets/scss/components/citadel/cards/_cards.scss
- assets/scss/components/stencil/account/_account.scss
- assets/scss/components/stencil/cart/_cart.scss
- assets/scss/components/stencil/previewCart/_previewCart.scss
- assets/scss/components/stencil/productView/_productView.scss
- config.json
- package.json
- templates/components/account/order-contents.html
- templates/components/account/orders-list.html
- templates/components/cart/content.html
- templates/components/cart/preview.html
- templates/components/faceted-search/facets/hierarchy-children.html
- templates/components/faceted-search/facets/hierarchy.html
- templates/components/faceted-search/facets/multi.html
- templates/components/faceted-search/facets/rating.html
- templates/components/faceted-search/selected-facets.html
- templates/components/faceted-search/show-more-facets.html
- templates/components/products/product-view.html
- templates/layout/base.html
> Cornerstone 1.3 merge to master

- config.json
- schema.json
- templates/pages/brands.html
> MERC-996 update and allow brand image resize

- config.json
> MERC-998 update default product gallery image size

- config.json
- schema.json
- templates/components/blog/post.html
> MERC-997 update and allow blog image resize

- schema.json
> MERC-998 update schema for product gallery image size

- config.json
- package.json
> Bump version to 1.3.1

- assets/js/theme/product/video-gallery.js
- templates/components/products/videos.html
Make youtube load as protocol agnostic.
> MERC-1037 - fix youtube videos on HTTPS

- assets/scss/checkout.scss
- config.json
- schema.json
- Change size/position and size of the logo
@bigcommerce/checkout @sherrybc @bc-ong @mcampa @bigcommerce/ui-platform
> CHECKOUT-917: uco customize header 

- config.json
- package.json
> Releasing: 1.3.2

- assets/js/theme/common/product-details.js
@bc-ong @bc-julianleong @bc-ranji
> MERC-1175 disable options when the item is a dropdown

- assets/js/theme/common/product-details.js
- assets/js/theme/common/select-option-plugin.js
- assets/js/theme/global.js
I found the solution in blueprint javascript
Is a jquery plugin that handles the hiding by creating a shadow hidden select element.
@bc-ranji @bc-ong @bc-julianleong
> MERC-1175 the fix for the dropdown bug using blueprint method

- config.json
- schema.json
- templates/components/common/footer.html
Adding in copyright information into the footer at parity to Blueprint style themes.
In the format of (c) current_year store_name.
> Spraypaint BigHacks: Adding Copyright Information to Footer

- assets/js/theme/common/product-details.js
- assets/js/theme/common/select-option-plugin.js
- assets/js/theme/global.js
- templates/components/products/product-view.html
Same PR that was reverted https://github.com/bigcommerce/stencil/pull/847 but with the bug fix
@bc-ong @bc-ranji
> MERC-1175 IE/edge product options fix

- assets/js/theme/global/loading-progress-bar.js
Please see https://github.com/HubSpot/pace/issues/328#issuecomment-246210165
Without this patch I cannot get a clean build of stencil in [my Docker setup](https://gist.github.com/Lewiscowles1986/d4ef75a2d9c3e7d6e1794c3e90246c9a)
> Updated pace reference

- package.json
Changing `pace` to `pace-progress` and locking to a commit hash to prevent from happening again.
https://github.com/HubSpot/pace/commit/62bc45debe3944ba189d5f563905d4620d06cb96
@lord2800 @saurabh-g
> Change pace reference to pace-progress

- config.json
https://jira.bigcommerce.com/browse/MERC-1445
> MERC-1445 - add read_only_files defaults

- templates/components/account/order-contents.html
- templates/components/account/orders-list.html
- templates/components/account/returns-list.html
- templates/components/blog/post.html
- templates/components/carousel.html
- templates/components/cart/content.html
- templates/components/cart/preview.html
- templates/components/cart/shipping-quotes.html
- templates/components/category/shop-by-price.html
- templates/components/category/sidebar.html
- templates/components/common/cart-preview.html
- templates/components/common/store-logo.html
- templates/components/page/contact-us-form.html
- templates/components/products/card.html
- templates/components/products/list-item.html
- templates/components/products/options/product-list.html
- templates/components/products/product-view.html
- templates/layout/base.html
- templates/pages/account/download-item.html
- templates/pages/account/orders/invoice.html
- templates/pages/brands.html
- templates/pages/compare.html
* Demonstrate usage of the `locale_name` variable for specifying the document language.
* Add `title` attributes to all images.
For accessibility and SEO.
Ping @mcampa @lord2800 @bc-AlyssNoland
> MERC-1025, MERC-1477: HTML refinements.

- schema.json
I'm not sure how this got merged. Seems like the tests we have in place don't check for this.
@johnhebron @bc-adamferenzi Please make sure you test your code before opening a PR
@lord2800
> Malformed json

- assets/scss/optimized-checkout.scss
documentation additions to `optimized-checkout.scss` file
`optimized-checkout-webdav.css` will have the same documentation
@bc-mkatz @bigcommerce/checkout @mcampa @lord2800
> CHECKOUT-807: update checkout stylesheet docs

- schema.json
https://github.com/bigcommerce/stencil/pull/871/ was closed, but @jordanwink201 spotted an issue (again a problem created by my re-creation of the original PR, my apologies), so simply submitting fix of added line. Tested twice just to make sure I wasn't testing the wrong one again (which is why this was missed) and appears to be working.
> Fix to missing line in schema

- config.json
>  MERC-1445 abc

- lang/en.json
- templates/pages/search.html
> MERC-1537 xss bug fix

- .travis.yml
> MERC-1531 add stencil bundle to travis

- config.json
- lang/en.json
- package.json
- templates/pages/search.html
This is already reviewed, it is cherry picked from the codefreeze branch
@bc-ong @mattolson
> MERC-1537 1.4.1 cherry pick

- templates/components/page/contact-us-form.html
Switch contact captcha to use google captcha instead of internal version of captcha.
ping @mcampa @lord2800 @PascalZajac
> MERC-1637 Switch contact captcha to use google captcha.

- lang/en.json
@mcampa @bc-ong 
For my hackathon project (called "Grammar Nazi") I'm proposing to fix ~20 typos in the language file in Cornerstone. I present them here for your review.
> Fixes to grammar

- .gitignore
- .travis.yml
- assets/js/test-unit/theme/common/faceted-search.spec.js
- assets/js/theme/common/faceted-search.js
- assets/js/theme/common/url-utils.js
- assets/js/theme/global.js
- assets/js/theme/product.js
- config.json
- package.json
- schema.json
- templates/components/common/footer.html
- webpack.conf.js
* shop by brand footer toggle
* add stencil bundle to travis
* Replace history.js with html5 history api shim
> Codefreeze

- LICENSE.md
- README.md
- assets/scss/settings/citadel/actionBar/_settings.scss
- assets/scss/settings/citadel/buttonGroup/_settings.scss
- assets/scss/settings/citadel/cards/_settings.scss
- assets/scss/settings/citadel/forms/_settings.scss
- assets/scss/settings/citadel/loading/_settings.scss
- assets/scss/settings/citadel/nav/_settings.scss
- assets/scss/settings/foundation/accordion/_settings.scss
- assets/scss/settings/foundation/alerts/_settings.scss
- assets/scss/settings/foundation/breadcrumbs/_settings.scss
- assets/scss/settings/foundation/buttons/_settings.scss
- assets/scss/settings/foundation/dropdown/_settings.scss
- assets/scss/settings/foundation/forms/_settings.scss
- assets/scss/settings/foundation/global/_settings.scss
- assets/scss/settings/foundation/grid/_settings.scss
- assets/scss/settings/foundation/inlineList/_settings.scss
- assets/scss/settings/foundation/modal/_settings.scss
- assets/scss/settings/foundation/pagination/_settings.scss
- assets/scss/settings/foundation/panels/_settings.scss
- assets/scss/settings/foundation/tables/_settings.scss
- assets/scss/settings/foundation/tabs/_settings.scss
- assets/scss/settings/foundation/type/_settings.scss
- config.json
- package.json
@mjschock 
https://jira.bigcommerce.com/browse/MERC-584
> MERC-584 Bigcommerce to BigCommerce

- assets/js/theme/common/product-details.js
- assets/js/theme/product.js
> STENCIL-2506 Fix quick view not working when opened on product page

- package.json
> upgrade webpack to fix a bug with babel source maps

- lang/en.json
- templates/pages/checkout.html
This is required for introducing UCO as Stencil resource
> CHECKOUT-1241 : Adding Checkout Stencil page

- assets/scss/components/citadel/forms/_forms.scss
- assets/scss/components/stencil/navUser/_navUser.scss
- assets/scss/components/stencil/socialLinks/_socialLinks.scss
- assets/scss/layouts/_layouts.scss
- assets/scss/layouts/footer/_footer.scss
- assets/scss/layouts/products/_productSaleBadges.scss
- assets/scss/layouts/products/_productSwatch.scss
- assets/scss/settings/stencil/socialLinks/_settings.scss
- config.json
- schema.json
- templates/components/cart/content.html
- templates/components/cart/preview.html
- templates/components/cart/totals.html
- templates/components/common/cart-preview.html
- templates/components/common/footer.html
- templates/components/common/login-for-pricing.html
- templates/components/common/navigation-menu.html
- templates/components/common/navigation.html
- templates/components/common/payment-icons.html
- templates/components/common/social-links.html
- templates/components/products/card.html
- templates/components/products/carousel.html
- templates/components/products/featured.html
- templates/components/products/grid.html
- templates/components/products/options/swatch.html
- templates/components/products/price.html
- templates/components/products/product-view.html
- templates/components/products/top.html
- templates/pages/compare.html
* Hide brand in the footer toggle (STENCIL-2938)
* Sale badges (STENCIL-2640)
* Resizing of swatches (STENCIL-2540)
* Require login for pricing (STENCIL-2578)
* As low as display (MERC-1165)
* Social media placement (STENCIL-2530)
* UX adjustments (STENCIL-2670)
> Spraypaint

- CHANGELOG.md
- assets/scss/components/stencil/productView/_productView.scss
* https://jira.bigcommerce.com/browse/STENCIL-2462
> STENCIL-2462 - Show 'Write a Review' link for mobile

- CHANGELOG.md
- templates/components/products/modals/writeReview.html
WHY:  https://jira.bigcommerce.com/browse/STENCIL-2486
> STENCIL-2486 - Change review comment to multiline instead of text element

- CHANGELOG.md
- assets/scss/components/stencil/productView/_productView.scss
File upload button does not properly display in IE if font-size is 0
> STENCIL-2439 File upload button does not properly display in IE

- CONTRIBUTING.md
[Stencil-3126: As a developer, I want to read contribution guidelines](https://jira.bigcommerce.com/browse/STENCIL-3126)
> STENCIL-3126: Add contribution guidelines to Stencil repository

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
See title. CONTRIBUTING.md has a link to this which currently 404s.
> STENCIL-3126: Add pull request template for contribution guidelines

- CHANGELOG.md
- package.json
Cornerstone is a theme. Stencil is a platform. Updating package.json to correctly reflect what's in the repo.
[STENCIL-3207](https://jira.bigcommerce.com/browse/STENCIL-3207)
> STENCIL-3207 - Update package.json to disambiguate Stencil and Cornerstone

- CHANGELOG.md
> STENCIL-3210 Changelog entry

- schema.json
This should help us avoid confusion as most merchants are not in the Google AMP beta.
[STENCIL-3261](https://jira.bigcommerce.com/browse/STENCIL-3261)
> STENCIL-3261 - Move Google AMP settings to its own section

- README.md
> Update to README.md header

- CHANGELOG.md
- assets/js/theme/common/product-details.js
Fix a bug that was preventing opening the cart preview modal
- https://jira.bigcommerce.com/browse/STENCIL-3270
@junedkazi
> STENCIL-3270 Fix a bug that was preventing opening the cart preview

- CHANGELOG.md
- assets/js/theme/product.js
- templates/components/amp/products/product-options.html
Price and weight do not update on product page when an option is selected	
https://jira.bigcommerce.com/browse/STENCIL-3277
> STENCIL-3277 fix product details scope

- CHANGELOG.md
- stencil.conf.js
- webpack.conf.js
see [this description](https://github.com/bigcommerce/stencil-cli/pull/286) for a more detail explanation 
https://jira.bigcommerce.com/browse/STENCIL-3243
@bigcommerce/stencil-team @lord2800
> STENCIL-3243 refactor stencil.conf.js to run as a worker

- CHANGELOG.md
- templates/components/products/list-item.html
See title
- [STENCIL-3312](https://jira.bigcommerce.com/browse/STENCIL-3312)
- [#970](https://github.com/bigcommerce/cornerstone/issues/970)
*Behavior prior to this PR*
> STENCIL-3312: Properly escape html in product list view

- CHANGELOG.md
- config.json
Reflect actual default value for `autoprefixer-browsers`.
> Stencil 3317

- assets/js/theme/cart.js
- Related to https://github.com/bigcommerce/bigcommerce/pull/18758
https://jira.bigcommerce.com/browse/STENCIL-3433
@PascalZajac @bigcommerce/stencil-team
> STENCIL-3433 check for value of zero

- templates/components/common/footer.html
Wrong file committed in #1007.
> Display current year in footer using {{moment}} template helper.

- README.md
- webpack.conf.js
* quick cleanup of README
* set clean-webpack-plugin verbose mode to false
> Cleanup README and turn off clean-webpack-plugin verbose mode

- CHANGELOG.md
- templates/pages/unavailable/maintenance.html
Maintenance page style fix
https://jira.bigcommerce.com/browse/STENCIL-3509
> STENCIL-3509 Maintenance page style fix

- assets/js/theme/common/carousel.js
- assets/js/theme/global.js
- webpack.conf.js
Move *.min import resolution to webpack config
cc @bigcommerce/stencil-team @sacr3dc0w
> Move *.min import resolution to webpack config

- CHANGELOG.md
Add README for changes to spacing for google plus.
https://jira.bigcommerce.com/browse/STENCIL-3153
> Add readme for google plus change

- lang/en.json
Recent changes in the en.json file had some typos that introduced some test failures.
https://jira.bigcommerce.com/browse/STENCIL-3670
> STENCIL-3670 Typos in en file causing tests to fail

- CHANGELOG.md
- assets/js/theme/common/product-details.js
Fixes a bug where product options and add to cart do not work when opened in Quick View modals
https://jira.bigcommerce.com/browse/STENCIL-3697
> STENCIL-3697 Add to cart not working on quick view modals

- CHANGELOG.md
- templates/pages/checkout.html
- templates/pages/order-confirmation.html
Add footer scripts to optimized checkout
https://jira.bigcommerce.com/browse/CHECKOUT-2314
@bigcommerce/checkout @junedkazi @mjschock
> CHECKOUT-2314 Add footer scripts to optimized checkout

- CHANGELOG.md
Add missing changelog entry for [STENCIL-3106](https://jira.bigcommerce.com/browse/STENCIL-3106). This was not included in #1096.
- [STENCIL-3106](https://jira.bigcommerce.com/browse/STENCIL-3106)
> STENCIL-3106 Adding missing changelog entry

- CHANGELOG.md
> Changelog for PR #1105

- package.json
Update Stencil-Utils to version 1.0.8
Links to any relevant tickets and documentation.
- [Ticket](https://jira.bigcommerce.com/browse/STENCIL-3972)
- ...
> STENCIL-3972 Update stencil-utils to 1.0.8

- package.json
> Bump stencil utils to 1.0.9

- CHANGELOG.md
Update the changelog to reflect the changes in [1113](https://github.com/bigcommerce/cornerstone/pull/1113)
[STENCIL-3567](https://jira.bigcommerce.com/browse/STENCIL-3567)
> Add Changelog description for PR 1113

- package.json
* prep for greenkeeper.  everything else but these deps are at the latest version
> greenkeeper ignore prep

- package.json
Reverts bigcommerce/cornerstone#1128
> Revert "greenkeeper ignore prep"

- CHANGELOG.md
A quick update to the changelog to point to the correct PR for STRF-4154
@mattolson
> Update changelog to point to correct PR for STRF-4154

- CHANGELOG.md
@bigcommerce/storefront-team @bookernath
> Move price range change log entry into draft as it is not part of 1.11.0 release

- templates/components/amp/common/footer.html
- templates/components/common/footer.html
Add UTMs to Powered by BigCommerce Logos and links on Merchant Stores
https://jira.bigcommerce.com/browse/STRF-4270
@bigcommerce/storefront-team @jasonherbst8
> Add UTMs to Powered by BigCommerce Logos and links on Merchant Stores

- CHANGELOG.md
* adds missing changelog entries for 1.13.2.
ping @junedkazi
> Add 1.13.2 changelog entries

- CHANGELOG.md
Added entry for #1225.
Grouped changes separate from strict fixes.
> 1.18.0 Changelog updates.

- CHANGELOG.md
Typo fix. Faceted, not facered.
> 1.18.0 Changelog typo fix.

- CHANGELOG.md
Adding #1210 to CHANGELOG.md for 1.18.0 release.
> Adding #1210 to CHANGELOG.md

- CHANGELOG.md
Updates CHANGELOG.md to note #1237 and #1241 
- #1237 
- #1241
> Update CHANGELOG.md with #1237 and #1241.

- CHANGELOG.md
* Added #1199, 1234, and #1247 to CHANGELOG.md
* Moved #1248 to top of draft changes.
> Adding #1199, #1234, and #1247 to CHANGELOG.md.

- CHANGELOG.md
- templates/components/amp/products/product-view.html
- templates/pages/amp/product.html
This reverts commit c3acff82bec204e3023ce0110e3b1b690fba73f5, reversing
changes made to 1acb31ec9c1fa106b4c2826d0c0ef8db3d518142.
A description about what this pull request implements and its purpose. Try to be detailed and describe any technical details to simplify the job of the reviewer and the individual on production support.
- ...
> Revert "Merge pull request #1242 from davidwrpayne/STRF-4866"

- CHANGELOG.md
> CHANGELOG entry for PR #1262

- CHANGELOG.md
- assets/scss/settings/stencil/navPages/_settings.scss
**What?**
Changing Menu Colors In Theme Editor Not Respected In Mobile View.
**Documentation**
#1078
> Fix for Changing Menu Colors In Theme Editor Not Respected In Mobile View

- CHANGELOG.md
> Move wishlist changelog into draft section

- CHANGELOG.md
Added entry for #1284 in `CHANGELOG.md`.
> Changelog entry for #1284.

- CHANGELOG.md
- templates/components/amp/css/base.html
- templates/components/amp/products/product-options.html
- templates/components/amp/products/product-view-details.html
- templates/components/amp/products/product-view.html
Reverts bigcommerce/cornerstone#1306
> Revert "fix(storefront): STRF-5101 - Fixes for product pricing JS for Google AMP on both PDP and PLP"

- CHANGELOG.md
- assets/js/theme/common/product-details.js
- assets/scss/components/stencil/price/_price.scss
- templates/components/products/price-range.html
- templates/components/products/price.html
Reverts bigcommerce/cornerstone#1300
> Revert "fix(storefront): STRF-5084 - Fixed PDP pricing element styling so it works with Google AMP"

- CHANGELOG.md
Moved #1326 changelog entry from `2.3.1` to `Draft`.
> Moved #1326 changelog entry to Draft.

- assets/scss/components/stencil/paymentMethods/_paymentMethods.scss
- lang/en.json
- templates/components/account/payment-methods-list.html
Implementation of the payment methods actions.
- [Link](https://jira.bigcommerce.com/browse/PAYMENTS-3363)
Desktop
Mobile
ping @bigcommerce/payments
> credit card actions(add, edit, delete) buttons

- assets/js/app.js
- assets/js/theme/account.js
- templates/components/account/payment-methods-list.html
Bind delete button FE/BE: the click will trigger window confirm, on confirming a post request will be sent then redirect to the credit card listing.
- [Link](https://jira.bigcommerce.com/browse/PAYMENTS-3148)
@bigcommerce/payments @jackosaurus
> delete payment method

- schema.json
Reverts bigcommerce/cornerstone#1361
Yep, I straight up accidentally merged a PR. Reverting.
> Revert "MERC-4097 Copy changes, rearrange Payment Buttons section"

- CHANGELOG.md
> Changelog entry for #1365.

- CHANGELOG.md
Changelog updates should be listed like a list.
> Changelog updates for Cornerstone 2.6.0

- CHANGELOG.md
Updated `CHANGELOG.md` for 2.7.0.
> Changelog for 2.7.0.

- CHANGELOG.md
#1401 introduces a breaking change. Accounting for that in the version number.
> Re-releasing 2.7.0 as 3.0.0.

- CHANGELOG.md
> Add #1417 to Changelog.

- CHANGELOG.md
Changelog additions for Cornerstone 3.1.1.
- Align product thumbnail image slider arrows. [#1399](https://github.com/bigcommerce/cornerstone/pull/1399)
- Corrected IDs in date.html form fields. [#1433](https://github.com/bigcommerce/cornerstone/pull/1433)
> Changelog for Cornerstone 3.2.0.

- assets/js/theme/search.js
- package.json
> Bump stencil utils

- templates/pages/compare.html
> Product Description show HTML content

- templates/components/products/list-item.html
> fix(cp): CP-4140 fixes modal scroll issue from quickview button

- config.json
Add csrf key to the theme features list.
> STRF-6115 Add csrf key to the theme features list.

- CHANGELOG.md
- config.json
This BC support URL is out of date, updating it to the current one.
- [MRKT-720](https://jira.bigcommerce.com/browse/MRKT-720)
> MRKT-720 - Update support URL

- CHANGELOG.md
Changelog updates for Cornerstone 3.4.3.
> Review changelog for 3.4.3.

- .travis.yml
- CHANGELOG.md
> Stop running Travis against Node 6

- CHANGELOG.md
Changelog updates for Cornerstone 3.5.0
> update changelog.md for release 3.5.0

- CHANGELOG.md
- templates/components/common/share.html
**What?**
This should be else if as this is basically a switch statement.
Similar reason for logic cleanup in #1512.
> Clean up share.html conditional logic

- CHANGELOG.md
- assets/scss/components/stencil/socialLinks/_socialLinks.scss
- templates/components/amp/common/share.html
- templates/components/common/share.html
- templates/components/common/social-links.html
Google plus is deprecated so we should remove it.  This pull request is part of that that removal.
- [Link 1](https://jira.bigcommerce.com/browse/STRF-5665)
> STRF-5665 remove google plus

- CHANGELOG.md
Adds changelog for https://github.com/bigcommerce/cornerstone/pull/1542
Thanks again @AlbertJBurton !
> Add changelog for #1542

- package-lock.json
diffs coming from nodev0.12 and npm npm 2.15.11
- ...
> diffs coming from nodev0.12 and npm npm 2.15.11

- CHANGELOG.md
- templates/components/amp/products/product-view-details.html
- templates/components/products/bulk-discount-rates.html
* templates/components/amp/products/product-view-details.html
* templates/components/products/bulk-discount-rates.html
> Clean up conditional logic in a couple component templates

- assets/js/theme/global.js
- assets/js/theme/global/basicGraphQLQuery.js
- package.json
- templates/layout/base.html
Adding a simple GraphQL request example as a branch so we can link to it as sample code.
> Simple GraphQL example using Apollo Client

- CHANGELOG.md
Adding changelog I forgot when I made https://github.com/bigcommerce/cornerstone/pull/1559
ping @mattolson
> Add changelog for #1559

- CHANGELOG.md
- config.json
- package.json
> Revert releases

- CHANGELOG.md
- lang/en.json
Missing default translation for gift certificate amount validation.
N/A
N/A
> Added missing gift certificate translation

- templates/pages/account/addresses.html
Add alert/success components on customer address list page. So we can surface errors when any action related to add/edit/delete addresses fail.
> Add alert/success components on customer address list page.

- CHANGELOG.md
Adds a changelog for https://github.com/bigcommerce/cornerstone/pull/1588
> Add changelog for #1588

- CHANGELOG.md
Adding changelog for 
https://github.com/bigcommerce/cornerstone/pull/1598
https://github.com/bigcommerce/cornerstone/pull/1599
> Add changelog for PR 1598 and 1599

- CHANGELOG.md
update changelog in preparation for cornerstone release 4.3.1
- [Link 1](https://jira.bigcommerce.com/browse/STRF-7801)
> add changelog for PR 1601 and 1618

- CHANGELOG.md
add changelog for 1622 to setup cornerstone 4.4 release
- [Link 1](https://jira.bigcommerce.com/browse/STRF-7903)
> add changelog for 1622

- CHANGELOG.md
update changelog to prep for cornerstone 4.4.1 release
- [Link 1](https://jira.bigcommerce.com/browse/STRF-7939)
> update changelog to prep for cornerstone 4.4.1 release

- package-lock.json
- package.json
> chore: bump stencil utils to 5.0.3

- CHANGELOG.md
Update changelog to prep for Cornerstone 4.4.2 release
- [Link 1](https://jira.bigcommerce.com/browse/STRF-8057)
> update changelog for cornerstone 4.4.2 release

- templates/pages/page.html
Adds a region to the page.html template for use in Store Design.
- [MERC-6208](https://jira.bigcommerce.com/browse/MERC-6208)
- [Thread](https://threads.com/34375388632)
> MERC-6208: Add region to page.html

- CHANGELOG.md
update changelog to set up for cornerstone 4.5.0 release
- [Link 1](https://jira.bigcommerce.com/browse/STRF-8175)
> update changelog for cornerstone 4.5.0 release

- schema.json
- schemaTranslations.json
Added a .json file that contains translations for the Cornerstone theme.
> feat(translate) TRANS-650 added SchemaTranslations.json for cornerstone

- package-lock.json
- package.json
Bump lazysizes to 5.2 to pull in these [changes and fixes.](https://github.com/aFarkas/lazysizes/compare/5.1.0...gh-pages)
> Bump lazysizes to 5.2.0

- assets/js/theme/global/maintenanceMode.js
Fix the logo in the admin bar, which is currently not rendering.
> Fix logo in admin bar

- CHANGELOG.md
https://jira.bigcommerce.com/browse/STRF-8366
> create changelog for cornerstone release 4.5.1

- assets/scss/components/stencil/productView/_productView.scss
Ticket: https://jira.bigcommerce.com/browse/STRF-8303
**Mobile**
Before
After
**Desktop**
Before
After
> Fix radio buttons responsive view

- CHANGELOG.md
add to changelog for cornerstone 4.5.4 release
> add to changelog for Cornerstone 4.5.4 release

- assets/scss/layouts/header/_header.scss
- lang/en.json
- templates/components/common/body.html
- templates/components/common/header.html
As a Shopper
I want to skip to the main content of a page
So I can skip menus and repeated blocks of information that appear on every page 
Link is becoming visible on focus
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-62)
> feat(storefront): BCTHEME-62 As a Shopper I want to skip to main content

- assets/js/theme/global/modal.js
- assets/js/theme/global/quick-view.js
- package-lock.json
- package.json
@BC-tymurbiedukhin @bc-alexsaiannyi 
As a shopper I want to have the quick view modal immediately have keyboard focus.
Now we have algo for modal trap that for implemented for quick view
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-73)
> feature(storefront): BCTHEME-73 As a shopper I want to have the quick view modal immediately have keyboard focus

- .github/workflows/pull_request_review.yml
Github actions to replace travis
```bash
juned.kazi at C02WF0AQHTDH in ~/Codebases/cornerstone on github-actions*
$ act pull_request -P ubuntu-latest=nektos/act-environments-ubuntu:18.04
[Node.js CI/build] 🧪  Matrix: map[node:10.x]
[Node.js CI/build] 🚀  Start image=nektos/act-environments-ubuntu:18.04
[Node.js CI/build]   🐳  docker run image=nektos/act-environments-ubuntu:18.04 entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Node.js CI/build]   🐳  docker cp src=/Users/juned.kazi/Codebases/cornerstone/. dst=/github/workspace
[Node.js CI/build] ⭐  Run pwd
| /github/workspace
[Node.js CI/build]   ✅  Success - pwd
[Node.js CI/build] ⭐  Run ls -al /github /home
| /github:
| total 20
| drwxr-xr-x 5 root root 4096 Jul 29 18:27 .
| drwxr-xr-x 1 root root 4096 Jul 29 18:26 ..
| drwxr-xr-x 2 …
```
> Github actions to replace travis

- .github/workflows/pull_request_review.yml
- package-lock.json
- package.json
remove stencil cli from dev dependency and move it over to GitHub actions install
https://github.com/bigcommerce/cornerstone/pull/1751/checks
@bigcommerce/storefront-team @bigcommerce/themes-team
> Remove stencil cli from dev dependency and move it over to github actions install

- CHANGELOG.md
- assets/scss/components/citadel/cards/_cards.scss
- templates/components/amp/products/card.html
- templates/components/products/card.html
- templates/pages/brands.html
- templates/pages/compare.html
Return heading to product card due to SEO
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-265)
> fix(storefront): BCTHEME-265 Return heading to product card

- README.md
Just updating test badge now that we use GitHub Actions.
> Update Test Badge in README.md

- .github/workflows/pull_request_review.yml
After the bundle test, upload the bundled .zip for easy testing on real stores if needed.
CC @bc-as @bigcommerce/themes-team
> Upload bundled .zip file on PRs for easy testing

- CHANGELOG.md
- templates/components/common/header.html
Adds the `header_bottom--global` global region to cornerstone. This will support the new global region feature in page builder once work on the feature is finished there.
- [MERC-7162](https://jira.bigcommerce.com/browse/MERC-7162)
> feat(content): MERC-7162 Add header bottom global region

- .github/workflows/pull_request_review.yml
Bumps versions of Ruby Actions used
- #1904
> Bump versions of Ruby

- CHANGELOG.md
- package-lock.json
- package.json
Updated stencil utils version, that has fix to the http request library 
https://jira.bigcommerce.com/browse/STRF-8898
- ...
> STRF-8898 'Show More' gives no additional options when filter clicked

- CHANGELOG.md
- assets/js/theme/account.js
- assets/js/theme/auth.js
- assets/js/theme/cart/shipping-estimator.js
- assets/js/theme/common/utils/form-utils.js
- assets/js/theme/contact-us.js
- assets/js/theme/gift-certificate.js
- assets/js/theme/product/reviews.js
- assets/js/theme/search.js
- assets/js/theme/wishlist.js
Error message not announced automatically through all of application
[jira](https://jira.bigcommerce.com/browse/BCTHEME-372)
> fix(storefront): BCTHEME-372 Error message not announced automatically

- assets/js/test-unit/theme/cart.spec.js
- assets/js/theme/cart.js
- assets/js/theme/cart/shipping-estimator.js
This PR has fixes of eslint and jest errors
> Fix eslint errors in cart.js, shipping-estimator.js and test in cart.spec.js

- assets/js/test-unit/theme/cart.spec.js
- lang/en.json
Added missing quotes for Country and State/Province fields of Shipping Estimator to pass functional tests
> Add missing quotes for Country and State/Province fields of Shipping Estimator to pass functional tests

- CHANGELOG.md
- lang/it.json
- lang/pt-BR.json
- lang/pt.json
This PR has updates in it, pt and pt-BR lang files to fix consent manager issue for corresponding locales. Also it has fix for rating aria label on pt and pt-BR
[BCTHEME-689](https://jira.bigcommerce.com/browse/BCTHEME-689) - parent ticket
[BCTHEME-685](https://jira.bigcommerce.com/browse/BCTHEME-685) - consent manages
[BCTHEME-690](https://jira.bigcommerce.com/browse/BCTHEME-690) - rating aria label
> fix(storefront): BCTHEME-689 Update lang files for some locales

- config.json
- schema.json
- schemaTranslations.json
Added container setting for spb container
https://jira.bigcommerce.com/browse/PAYPAL-886
> feat(payment): PAYPAL-886 added container setting for spb container

- CHANGELOG.md
- package-lock.json
- templates/components/account/navigation.html
When navigating to the specific Wish List, there is no navigation in the store to come back to the list of Wish lists as tab ("My Wish Lists" in this case) becomes unclickable if user is currently on this tab.
[Jira](https://jira.bigcommerce.com/browse/BCTHEME-606)
> fix(storefront): BCTHEME-606 No navigation back to wishlist tab when you are in a wishlist

- CHANGELOG.md
- assets/js/theme/common/state-country.js
On submit, we need to accept the non-translated version of the state to store it correctly in the DB
https://jira.bigcommerce.com/browse/CUST-1583
Supporting PR: https://github.com/bigcommerce/bigcommerce/pull/42221
> feat(customers): CUST-1583 use label for country states to send non-translated name on submit

- CHANGELOG.md
- lang/fr.json
Update lang file for FR locale.
[BCTHEME-932](https://jira.bigcommerce.com/browse/BCTHEME-932)
> fix(storefront): BCTHEME-932 Update lang file for FR locale

- CHANGELOG.md
- package-lock.json
- package.json
Update dev dependency to address a critical security vulnerability.
**BEFORE**
**AFTER**
https://github.com/advisories/GHSA-phwq-j96m-2c2q
> Bump webpack-bundle-analyzer

- CHANGELOG.md
- schemaTranslations.json
**What?**
This PR updates schemaTranslations.json for Korean.
**Tickets / Documentation**
- [BCTHEME-1203](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1203)
> fix(storefront): BCTHEME-1203 Translations update September 2022

- CHANGELOG.md
- package-lock.json
- package.json
Bump stencil utils version with BODL integration for Add to Cart and Remove from Cart events
- [STRF-10018](https://bigcommercecloud.atlassian.net/browse/STRF-10018)
> feat(storefront): STRF-10018 Bump stencil utils with BODL events: Add to Cart and Remove from Cart

- CHANGELOG.md
- templates/pages/auth/account-created.html
Revert [BCTHEME-1185](https://github.com/bigcommerce/cornerstone/pull/2248/files)
> Revert BCTHEME-1185

- CHANGELOG.md
- assets/scss/components/stencil/cart/_cart.scss
- assets/scss/components/stencil/previewCart/_previewCart.scss
Fix styles for SPB buttons
Depends on https://github.com/bigcommerce/bigcommerce/pull/50165
- [PAYPAL-1807](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1807)
Braintree
https://user-images.githubusercontent.com/99336044/206390026-a149a928-7578-46ec-936d-b1d044ac4277.mov
PayPalCommerce
https://user-images.githubusercontent.com/99336044/206390226-75a03311-cdcd-46d8-90c3-5ec8c15360dd.mov
> feat(payment): PAYPAL-1807 fix styles for SPB buttons

- CHANGELOG.md
- assets/scss/components/stencil/cart/_cart.scss
- assets/scss/components/stencil/previewCart/_previewCart.scss
Reverts bigcommerce/cornerstone#2295
Unnecessary changes
> Revert "feat(payment): PAYPAL-1807 fix styles for SPB buttons"

- CHANGELOG.md
- assets/js/theme/account.js
- templates/pages/account/add-payment-method.html
Extended BigCommerce.accountPayments app initialization interface due to the 
Due to the
https://bigcommercecloud.atlassian.net/browse/ADYEN-313
https://bigcommercecloud.atlassian.net/browse/ADYEN-707
https://bigcommercecloud.atlassian.net/browse/ADYEN-313
https://bigcommercecloud.atlassian.net/browse/ADYEN-707
[Storefront Account Payments pr](https://github.com/bigcommerce/storefront-account-payments/pull/4)
https://user-images.githubusercontent.com/79574476/215445008-999d0489-a073-488e-b2f1-2e621022ddf8.mov
> feat(payment): ADYEN-313 improved interface of payment widget

- assets/scss/layouts/footer/_footer.scss
- templates/components/common/footer.html
Removed unnecessary block of code and corresponding styles. Removed unnecessary block of code and corresponding styles
According to ticket https://bigcommercecloud.atlassian.net/browse/PAYPAL-1843
> feat(payment): PAYPAL-1843 removed unnecessary block of code and corresponding styles

- CHANGELOG.md
- package-lock.json
- package.json
Use the latest release of stencil-utils
[DATA-10695](https://bigcommercecloud.atlassian.net/browse/DATA-10695)
[DATA-10695]: https://bigcommercecloud.atlassian.net/browse/DATA-10695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: DATA-10695 Bump stencil-utils version

- CHANGELOG.md
- assets/js/theme/account.js
- templates/pages/account/add-payment-method.html
- Updated initialization interface of the storefront-account-payments lib
- added theme styles
> feat(payment): ADYEN-729 updated initialization interface of the storefront-account-payments lib, added theme styles

- CHANGELOG.md
- assets/js/theme/account.js
Added showAlertModal to the renderAccountPayments initialization
https://bigcommercecloud.atlassian.net/browse/ADYEN-726
> feat(payment): ADYEN-726 added showAlertModal to the renderAccountPayments initialization

- CHANGELOG.md
- lighthouse-config.js
- package.json
This PR fixes errors in the terminal when running the Lighthouse command.
- [BCTHEME-1326](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1326)
[BCTHEME-1326]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(storefront): BCTHEME-1326 Running Lighthouse npm script fails in terminal

- CHANGELOG.md
- config.json
Changed default size of PayPal button on checkout step
- CHANGELOG.md entry added (required for code changes only)
> feat(payment): PAYPAL-3064 changed default paypal size

- README.md
Add deepwiki link so that our wiki will automatically refresh.
> Add deepwiki badge to readme
