assets/js/theme/common/product-details.js
If an option has an image change rule attached to it and it's set as the default option, the image change rule does not trigger upon loading of the product details page. 
https://jira.bigcommerce.com/browse/MERC-363
@bc-ejoe @sherrybc @mickr @hegrec
=> MERC-363 Show "init" image from a product or option rule

templates/components/search/advanced-search.html
MERC-116 - Price fields should be of number type
* Change field type to `number` this will prevent unwanted strings from being submitted for price.
=> MERC-116 - Price fields should be of number type

assets/scss/components/stencil/navUser/_navUser.scss
MERC-111 - Fix text cutoff in search dropdown
* Unset height rule for the dropdown search bar, the results with going with the default height instead of being explicitly sized.
=> MERC-111 - Fix text cutoff in search dropdown

assets/js/theme/global/stencil-dropdown.js, templates/components/search/quick-results.html
MERC-108 - Add 'X' to close full screen quick search dropdown.
Once there are search results it is difficult and unintuitive to close the search results drop down.
Just added the standard 'X' that we use in modals to display when there are search results. This is bound to the listener with the `data-drop-down-close` data attribute.
=> MERC-108 - Add 'X' to close full screen quick search dropdown.

templates/pages/auth/account-created.html
Change the url for the "continue" button to point to a specific url instead of to the home url.
Currently the url doesn't take redirects during account signup into account, which means adding to wishlist while not signed in doesn't work when you create an account (among other things).
Ping @hegrec @mickr @mcampa
=> MERC-456 Update the continue url to point to a new specific url instead of home

templates/components/products/modals/writeReview.html
Without this, the throttle token won't be sent to BC App, and it will consider all "throttled" requests to be invalid.
=> MERC-581 - adding support for hidden throttle token to product review modal

templates/components/cart/content.html, templates/components/cart/preview.html
MERC-454 Configurable Fields on Cart and Cart Preview
* Configurable fields were not visible unless there are options on the cart page
* Configurable fields are now visible in the cart preview modal.
=> MERC-454 Configurable Fields on Cart and Cart Preview

config.json, templates/components/products/card.html
Use the gallery image size and also bump it up slightly to prevent blurry images
The `product` preset is much larger than the css limited size of card images. They are never larger than 300px across all responsive widths so this appears to be an appropriate size.
@sherrybc @bc-ejoe @mickr @mcampa
=> MERC-410: Improve gallery image size

package.json, webpack.conf.js
Babel 6 does not transpile object.assign automatically so we need to include this plugin.
@mcampa @bc-ejoe @mickr @sherrybc
=> MERC-662: Transpile Object.assign

package.json
Fix for missing previous slide arrow on the carousel by reverting back to slick-carousel v1.5.5.  
Prior to 328cf24, v1.5.5 was being pulled in.  v1.5.6 of the lib introduced a change to the dom location of the arrow, causing the z-index to be lower than the carousel image.
before:
after:
@hegrec @mickr @sherrybc @mcampa
=> MERC-691: revert back to slick-carousel v1.5.5

README.md
Doing poc on customizing unified checkout and saw a few typos in the readme.
@mickr @mcampa @hegrec
=> Fix some typos and grammar in readme

templates/components/products/options/product-list.html, templates/components/products/options/set-rectangle.html, templates/components/products/options/set-select.html, templates/components/products/options/swatch.html
MERC-721 - Consistent `required` labeling
* Required fields for options should be clearly marked as required, and consistent.
=> MERC-721 - Consistent `required` labeling

templates/components/cart/content.html
The cart table should not have the `data-cart-content` attribute. That attribute is already present on the div that wraps the cart content component in the `page/cart.html` file.
This attribute causes the cart not to function as expected when the last product is removed from the cart after previously removing other products. As an example, put 2 products in your cart. Remove one, then remove the last. The page is supposed to refresh after the last item is removed, but it doesn't.
This pull request fixes that problem.
=> Remove repetitive data attribute from cart table

assets/scss/components/citadel/cards/_cards.scss, assets/scss/components/stencil/productView/_productView.scss, templates/components/products/product-view.html
product image in product details
product images in gallery
ignore the red title - that is for another ticket
@mcampa @mickr @bc-ejoe @hegrec @deepa2083
=> MERC-888 show actual product image dimensions

assets/js/theme/common/product-details.js
Fix for 'Add to Cart' button in quick view modal being disabled.  
`window.BCData` does not get set for the quick view modal, so the call to `updateView` would disable the 'Add to Cart' button.  Updated so that product attributes are updated when the product has options, and then the view gets updated.  (related to MERC-678)
@mcampa @hegrec @sherrybc @bc-ranji
=> MERC-893: update the view in quick view modal if product has options

assets/scss/layouts/products/_productGrid.scss
`column-count` breaks layout to top to bottom arrangement rather than left to right; use pattern-lab columns 
@bc-ong
=> MERC-999 update feature product style

assets/scss/checkout.scss, config.json, schema.json
ability to change background color
Ability to update Typography via existing style editor features under 'Backgrounds & Fonts"
*Page Text	
*Heading	
*Heading Text
update form fields color
@bigcommerce/checkout @sherrybc @mcampa @bc-ong
=> CHECKOUT-919: add main content uco customizations

assets/scss/components/stencil/cart/_cart.scss, assets/scss/components/stencil/previewCart/_previewCart.scss
Fixing Pay with Amazon button position for Cornerstone themes and using new `RemoteCheckout` class for unification.
Because it looks ugly otherwise.
ping @davidchin, @bc-miko-ademagic, @bigcommerce/payments
=> BIG-27748: Cornerstone Light, Bold, Warm fix of Amazon button placement

templates/components/account/order-contents.html, templates/components/cart/content.html, templates/components/common/quick-search.html, templates/components/common/search-box.html, templates/components/common/subscription-form.html, templates/components/products/product-view.html, templates/components/search/advanced-search.html
The `.u-` utility classes are being deprecated in version 3.0 of Citadel. In places where `u-hiddenVisually`is being used for labels, replace it with `is-srOnly` (behavior of this class hides the content to users, but is read out by assistive technology like screen readers).
@bc-miko-ademagic
=> Deprecate u-hiddenVisually in labels

assets/scss/components/stencil/cart/_cart.scss, lang/en.json, templates/components/cart/preview.html, templates/components/common/cart-preview.html, templates/pages/cart.html
Consume the new field exposed in https://github.com/bigcommerce/bigcommerce/pull/15145 to display links to checkout with support for multiple addresses.
Merchant demand.
Home page cart popup:
Full cart page:
Product page added to cart popup:
=> CHECKOUT-1016: Expose links to multi-address checkout.

assets/js/theme/global/maintenanceMode.js
* Use CSS only to position maintenance banner.
* Currently, we use both JS and CSS to position the maintenance banner. They conflict with each other. Therefore, the banner goes out of position when you scroll.
* For your reference, these are the original commits. As you can see, JS solution was implemented first. And then few days later, a different engineer introduced the CSS change.:
* https://github.com/bigcommerce/stencil/commit/4ab7648598622ec8b0ac4a379e102f185b350b4c
* https://github.com/bigcommerce/stencil/commit/44a0757fc05d6b0c7412ad5236ae7f97588e3f90
* Existing CSS here: https://github.com/bigcommerce/stencil/blob/master/assets/scss/components/stencil/maintenanceNotice/_maintenanceNotice.scss
|Before|After|   
|---|---|
|![screen shot 2016-09-28 at 12 26 22 …
=> Use CSS to position maintenance banner

.gitignore, assets/js/test-unit/theme/common/faceted-search.spec.js, assets/js/theme/common/faceted-search.js, assets/js/theme/common/url-utils.js, assets/js/theme/global.js, assets/js/theme/product.js, package.json, webpack.conf.js
MERC-1272: Use of URLs with a hashbang (#!) removes the hashbang from the URL and adds it back to window.location without the #
This PR replaces [history.js](https://github.com/browserstate/history.js/) which is abandoned and buggy with [HTML5-History-API](https://github.com/devote/HTML5-History-API) which operates according to W3C specification.
@lord2800 @sherrybc
=> MERC-1272 Replace history.js with html5 history api shim

config.json, schema.json, templates/components/common/footer.html
1. Moves the "Quickview" setting from the "Layout Settings" accordion to the Products accordion
2. Moves the "Content pages in Main Menu" setting from the "Layout Settings" accordion to the "Header > Page Navigation" accordion
3. In the Footer > Show Copyright section – adds more qualification:  Show "©", current year and store name
4. In the Footer > Show Powered By – adds more qualification: "Powered by BigCommerce"
5. In the Footer > Hide Brands in Footer has been changed to "Show brands in footer".
=> spraypaint ux adjustments

assets/scss/layouts/_layouts.scss, assets/scss/layouts/products/_productSaleBadges.scss, config.json, schema.json, templates/components/products/card.html
* adding HTML to productcard.html added productSaleBadges.scss and added to layouts.sccs to import new productSaleBadges.scss file
* added updated config and schema
* Fixed up css added excludes burst to schema
* updated productsalebadges.scss with fixes form pull request
* removed vendor prefixes
* made changes to product card and sale badge css per miko's instructions
* changing order of padding per git test
* consolidate shared styles
* fix indentation
=> sale badges

config.json, schema.json, templates/components/products/card.html, templates/components/products/featured.html, templates/components/products/grid.html, templates/components/products/product-view.html
you can now toggle 'Log in for pricing' in Theme Editor
[![IMAGE ALT TEXT HERE](https://i.ytimg.com/vi/YUKY8rGXCGk/default.jpg?sqp=CNyFosIF&rs=AOn4CLAOWX_8hU-JlzMYYnHOTXt2NYNTOA)](https://youtu.be/YUKY8rGXCGk)
(replaces <a href="https://github.com/bigcommerce/stencil/pull/857">PR 857</a>)
=> Login for pricing

assets/scss/layouts/_layouts.scss, assets/scss/layouts/products/_productSwatch.scss, config.json, schema.json, templates/components/products/options/swatch.html
(re-introduces the reverted merge from #855)
uncomment the needed scss
fixing errors from travis-ci
updated for errors from testing
changed swatches to have warning that swatches max at 150x150
e.g.:
=> swatch changes

assets/scss/components/citadel/forms/_forms.scss, assets/scss/components/stencil/navUser/_navUser.scss, assets/scss/components/stencil/socialLinks/_socialLinks.scss, assets/scss/layouts/footer/_footer.scss, assets/scss/settings/stencil/socialLinks/_settings.scss, config.json, schema.json, templates/components/common/footer.html, templates/components/common/navigation-menu.html, templates/components/common/navigation.html, templates/components/common/payment-icons.html, templates/components/common/social-links.html
Theme Editor settings:
`social_icon_placement_top = false`:
`social_icon_placement_top = true`:
`theme_settings.social_icon_placement_bottom = 'bottom_none'`:
`theme_settings.social_icon_placement_bottom = 'bottom_left'`:
`theme_settings.social_icon_placement_bottom = 'bottom_right'`:
* "Hide Content Pages in Main Menu" and "Show Quickview" are moved out of Layout Settings in #897
* updates Social Media Icons heading to be 'Placement'
=> social media placement

assets/scss/components/stencil/facetedSearch/_facetedSearch.scss, templates/components/faceted-search/facets/rating.html
Currently we are showing ratings facets as select list but it works more like radio buttons. So this will help move it away from select list options & use it as single select links.
ping @mcampa @bc-ranji @bc-julianleong
=> MERC-1560 Updating rating to links instead of select list options.

templates/components/products/price.html
https://forum.bigcommerce.com/s/question/0D51300003Qgwi6/itemprop-for-condition-in-cornerstone-stencil-theme
[BIG-19374](https://jira.bigcommerce.com/browse/BIG-19374)
This schema is used by Google Shopping Feed and can result in clients receiving error messages. This PR adds support for product availability and condition.
=> BIG-19374: added support for product availablity and condition

assets/scss/components/vendor/slick/_slick.scss
Ticket: [CRO-11: Horizontal bar in Stencil Theme Editor shouldn't be there](https://jira.bigcommerce.com/browse/CRO-11)
In viewports less than md (smaller tablet, etc) an annoying horizontal scrollbar shows. Here's how it looks:
The issue was from the right slick arrow for the carousel. It's pushed too far to the right by 5 pixels. Bringing it back 5 pixels solves the issue.
On multiple viewports, multiple browsers. All looks fine to me.
=> CRO-11: Fix scrollbar issue in viewport < md

templates/components/cart/totals.html
Only show the gift certificate section if gift certificates are enabled.
@mcampa @mjschock @bigcommerce/stencil-team
=> STENCIL-2461 Check if gift certificates are enabled before rendering.

templates/components/common/navigation-menu.html
For the mobile menu add check to make sure if gift certificate is enabled before showing the gift certificate link.
@bigcommerce/stencil-team @mcampa @mjschock
=> STENCIL-2446 Add check to show gift cert on mobile menu

assets/scss/components/stencil/search/_search.scss
Don't need to show the close button because there is one in the top left corner already
https://jira.bigcommerce.com/browse/STENCIL-2491
@bc-AlyssNoland @mjschock @bc-ong
=> STENCIL-2491 Fix mobile search dropdown style

CHANGELOG.md
=> STENCIL-3000 adding Changelog file

CHANGELOG.md, templates/components/common/navigation-menu.html, templates/components/common/navigation.html, templates/pages/auth/create-account.html, templates/pages/auth/login.html
This PR fixes 2 things;
- Sign In link is displayed always.
- Show the Sign Up link when the settings is enabled in the store settings.
@mcampa @mjschock @bigcommerce/stencil-team 
@nickdengler can we test this one.
=> STENCIL-2504 Show account creation only if it is enabled in store settings.

CHANGELOG.md, assets/scss/layouts/footer/_footer.scss, config.json, schema.json, templates/components/common/footer.html, templates/components/common/geotrust-ssl-seal.html, templates/components/common/ssl-seal.html
* adds a toggle for the GeoTrust SSL Seal
* implements the the instructions <a href="https://www.geotrust.com/support/seal/agreement/installation-instructions/">here</a>
* the domain and size can be set
=> STENCIL-2598 - Add GeoTrust SSL Seal Toggle

CHANGELOG.md, assets/scss/layouts/products/_productSwatch.scss, templates/components/products/options/swatch.html
Add a larger view of a swatch image when option is hovered over.   
@mjschock @mcampa
=> STENCIL-2448: Add expanded view of swatch on hover

CHANGELOG.md, assets/js/theme/product.js
Our product review emails link to the PDP with the hash #write_review
included.
We need to respond to this hash and automatically pop the review form.
*Testing/Proof*
Visit any product page with #write_review at the end of your URL.
=> STENCIL-3009 - automatically open review link if hash is included

CHANGELOG.md, templates/pages/search.html
Don’t suggest that nothing was found when things are found.
Proof:
=> STENCIL-2457 - fix incorrect suggestion warning

CHANGELOG.md, assets/scss/layouts/products/_productSaleBadges.scss
Sale badges can appear on top of the megamenu if it comes down far
enough. This is due to a bad z-index.
Proof:
Star Sale Badge
Diagonal Sale Badge
Top Left Sale Badge
=> STENCIL-3084 - fix z-index on product sale badges

CHANGELOG.md, templates/components/products/videos.html
If the product has videos, we should auto-expand that section.
Proof:
http://g.recordit.co/vYzLONhDWB.gif
=> STENCIL-2555 Auto-expand product videos when present

CHANGELOG.md, templates/pages/search.html
Page content and titles are entered by merchants in the CP so they can be safely rendered raw, without escaping.
Note that I tested some light script injection and nothing worked, including with Raw HTML pages. However, we will want to be able to detect those since they don't look nice visually.
Proof:
=> STENCIL-2415 - Prevent over-escaping of HTML in content page search

CHANGELOG.md, templates/components/carousel-content.html
Using triple braces for text content on Carousel so it doesn't get over-escaped.
Generally we don't consider this a security risk as the content must be entered by the merchant in the control panel.
Proof:
(Before)
(After)
=> STENCIL-2494 - don't over-escape carousel content text

CHANGELOG.md, schema.json
We have this weird option for "disabling" the number of products per page, which makes no sense and is causing confusion.
In the future we may evaluate some kind of best practice for infinite scrolling, but for now we should disable this.
Proof:
=> STENCIL-2629 - Remove option for "disable" on number of products per page

CHANGELOG.md, templates/components/products/options/product-list.html
Correctly hiding the “none” option for required pick lists (without
photo)
I've also verified that this works with and without a default selection on the option.
Proof:
=> STENCIL-2493 - Do not display "none" option for required pick lists

CHANGELOG.md, assets/js/theme/global/stencil-dropdown.js
Unused event variable was causing js errors in Firefox and preventing execution of the rest of the function.
@mcampa @mjschock
=> STENCIL-2445: Remove unused variable causing js error

CHANGELOG.md, assets/scss/optimized-checkout.scss, config.json
add font styles and background color for discount banners for Cornerstone theme variations
https://jira.bigcommerce.com/browse/CHECKOUT-1561
theme bundle: [Cornerstone-1.5.2.zip](https://github.com/bigcommerce/stencil/files/795668/Cornerstone-1.5.2.zip)
https://launchbay.bigcommerce.net/projects/1/releases/27254 -> https://store-k8ndry7kvg.my-integration.zone/
@bigcommerce/checkout @bigcommerce/stencil-team
=> CHECKOUT-1561: style discountBanners for Cornerstone theme variations

CHANGELOG.md, templates/pages/checkout.html
Expose a translation object on the checkout page.
Please note that this PR can only be merged after merging and releasing https://github.com/bigcommerce/paper/pull/103.
So it can be used by UCO to display non-English strings.
@bigcommerce/checkout @mcampa @lord2800
=> CHECKOUT-1234: Expose translations object

CHANGELOG.md, assets/js/theme/global/menu.js, assets/js/theme/global/mobile-menu-toggle.js, assets/scss/components/stencil/navPages/_navPages.scss, assets/scss/settings/stencil/navPages/_settings.scss, config.json, schema.json, templates/components/common/navigation-dropdown.html, templates/components/common/navigation-list-alternate.html, templates/components/common/navigation-menu.html
* Provides an option in theme editor to select the menu design type for categories.
* Has the legacy behavior when the design is set to Simple.
* Is responsive to small and medium+ screen sizes.
* Simple setting (3 and below; default, existing behavior):  http://g.recordit.co/K67orI3sgY.gif
* Alternate setting (up to the maximum display depth value):  http://g.recordit.co/nH5xoqTtr3.gif (note that the animation for the arrow looks a little strange in the GIF)
* https://jira.bigcommerce.com/browse/STENCIL-2558
ping @bigcommerce/stencil-team, @bc-ong
=> STENCIL-2558 - Update menu depth in navigation

CHANGELOG.md, stencil.conf.js
Print a readable error when a npm module is missing, or any other webpack error, instead of dumping the whole error object to the console.
Example:
```
Module not found: Error: Cannot resolve module 'lazysizes' in /Users/mario.campa/stencil/assets/js/theme resolve module lazysizes in /Users/mario.campa/stencil/assets/js/theme
looking for modules in /Users/mario.campa/stencil/node_modules
/Users/mario.campa/stencil/node_modules/lazysizes doesn't exist (module as directory)
resolve 'file' lazysizes in /Users/mario.campa/stencil/node_modules
resolve file
/Users/mario.campa/stencil/node_modules/lazysizes doesn't exist
/Users/mario.campa/stencil/node_modules/lazysizes.webpack.js doesn't exist
/Users/mario.campa/stencil/node_modules/lazysizes.web.js doesn't exist …
```
=> Print a readable error  instead of dumping the whole error object to the console.

assets/scss/components/stencil/navPages/_navPages.scss
This fixes the issue where the sub category menus would disappear after clicking away from them, as the stencil-dropdown `hide` method removes the 'is-open' class.
[STENCIL-3254](https://jira.bigcommerce.com/browse/STENCIL-3254)
=> STENCIL-3254 - Fixes disappearing sub category menus issue

README.md
The recommendation for fenced code blocks is a blank line before and after the code block. Without these blank lines, github might render correctly, but other markdown readers might not. 
Refernce: https://help.github.com/articles/creating-and-highlighting-code-blocks/
=> codeblock formating in readme

CHANGELOG.md, lang/en.json, templates/components/page/contact-us-form.html, templates/components/products/modals/writeReview.html, templates/pages/auth/create-account.html
Adding support for google recaptcha v2.
- https://jira.bigcommerce.com/browse/STENCIL-2934
It depends on https://github.com/bigcommerce/bigcommerce/pull/17715. 
zip: 
[Cornerstone-recaptcha-v2-1.5.3.zip](https://github.com/bigcommerce/cornerstone/files/829184/Cornerstone-recaptcha-v2-1.5.3.zip)
=> STENCIL-2934 Add recaptcha v2 support to cornerstone.

templates/pages/amp/product.html
Load amp-iframe script only when we have product options.
ping @bigcommerce/stencil-team @mcampa @bookernath
=> STENCIL-2944 Load amp iframe only when we have product options.

templates/layout/amp.html, templates/pages/amp/category.html, templates/pages/amp/product.html
Currently we load the AMP-analytics module even if no ID is specified.
Although we want everyone to have an ID, I don't want there to be
errors on the storefront, so let's fix that.
https://jira.bigcommerce.com/browse/STENCIL-3262
=> STENCIL-3262 - only load AMP-analytics if there's an ID

CHANGELOG.md, schema.json
Adds a "Product display mode" setting to the theme editor so merchants can choose between a grid or list view for their products on category, brand, and search results pages.  Product list view functionality already exists in the theme. This change allows merchants to actually use it :)
https://jira.bigcommerce.com/browse/STENCIL-3194
Grid Mode (Default):
List Mode:
=> STENCIL-3194: Adds theme editor setting for product display mode (grid vs list).

CHANGELOG.md, templates/components/amp/products/product-view.html, templates/pages/amp/product.html
Load amp social share only when we have social icons.
=> Load amp social share only when we have icons to share.

templates/components/products/options/product-list.html
In a previous PR an HTML tag was accidentally left unclosed, leading to broken PDPs when non-required Product List Options were used. 
- [STENCIL-3305](https://jira.bigcommerce.com/browse/STENCIL-3305)
=> STENCIL-3305 - Fix invalid html (tag not closed)

CHANGELOG.md, config.json
To serve checkout and order-confirmation pages in Stencil
https://github.com/bigcommerce/bigcommerce/pull/17826
Ping: @jordanwink201 @mcampa 
Tested manually that checkout/order confirmation renders in Stencil properly.
=> STENCIL-3190 : Adding `customized_checkout` theme feature

CHANGELOG.md
Move changelog entry for customized_checkout to draft. As the changes are slated to go out in the next release.
@bigcommerce/stencil-team @snaderiBC
=> STENCIL-3190 Move changelog entry for customized_checkout to draft.

CHANGELOG.md, templates/components/amp/css/base.html, templates/components/amp/css/product.html
Restyled how product details are implemented on the product page.
When there are additional details on the product page, the amp carousel
shrinks because of the way that the product details are styled.
ping: @junedkazi @bookernath
=> Fix AMP Carousel on Product Page

CHANGELOG.md, templates/layout/amp-iframe.html
Removing the footer.scripts helper from the amp-iframe so footer
scripts will NOT render in the amp product options iframe. This was
causing weird display of product options on some stores.
Ping @junedkazi
=> STENCIL-3328 - Remove footer scripts from amp-iframe

CHANGELOG.md, templates/components/common/footer.html
This HTTP link to bigcommerce.com was causing problems in theme editor
due to mixed content. Updating to a correct HTTPS link (which also
saves a redirect, incidentally.
=> STENCIL-2418 - Fix BC link in footer to HTTPS

CHANGELOG.md, templates/components/amp/common/alert-error.html, templates/components/amp/common/alert-success.html, templates/components/amp/common/navigation-menu.html, templates/components/amp/common/paginator.html, templates/components/amp/css/product.html, templates/components/amp/products/product-view.html
AMP is throwing validation errors based on some of the markup we use for our alert messages. We need to change the markup to use valid HTML tags and add in the styles for them since they were missing.
@bookernath @junedkazi
=> Fix invalid icon HTML in AMP templates

templates/pages/cart.html
While editing our cart page we discovered an orphan backtick hanging out in the cart template. This PR removes it.
N/A
N/A
=> Remove orphan backtick

CHANGELOG.md, config.json, schema.json, templates/components/common/footer.html, templates/components/common/geotrust-ssl-seal.html
Allowing the theme user to specify the correct Common Name for the
certificate will allow it to render correctly. This information can be
referenced from the billing system for certs purchased through BC.
The SSL common name value is known only by the billing system and/or the merchant, so we'll need to create a KB article detailing how to use this setting.
- [STENCIL-3253](https://jira.bigcommerce.com/browse/STENCIL-3253)
=> STENCIL-3253 allow merchants to specify Geotrust cert Common Name

CHANGELOG.md, assets/js/theme/product.js
Fixes a bug pointed out by @ocvninfo where clicking the 'Write a Review' link in the quick view would take you to the product page but would not open the modal.
- [STENCIL-3352](https://jira.bigcommerce.com/browse/STENCIL-3352)
- #984 
http://recordit.co/CS8jVePxfd/gif/notify
=> STENCIL-3352 - Fix product quick view 'Write a Review' link

CHANGELOG.md, templates/components/products/modals/writeReview.html
Fixes an issue where submitting an invalid form (usually because of the captcha) would result in the loss of the form data.  For example, the comments might need to be re-entered.
- [STENCIL-3010](https://jira.bigcommerce.com/browse/STENCIL-3010)
http://g.recordit.co/MhD8igg03S.gif
@bigcommerce/stencil-team 
P.S. i opted for `if/else`'s here for the sake of readability - i'm open to using an `if` subexpression in-line if people prefer that
=> STENCIL-3010 - Repopulate review form fields after error

templates/components/common/footer.html, templates/pages/category.html
When neither faceted search is enabled, or a subcategory is not present, the main content area remains at 75% width. This is due to the styling of .page-sidebar + .page-content. Another issue is three products display display in a row.
Using the {{or}} operator, verify if child category exists or faceted
search is enabled. If neither is true, page content will stretch 100%
and display four products by default.
Instead of using an extra JavaScript call on the client side, let's use {{moment}} to display the copyright year.
[https://github.com/bigcommerce/cornerstone/issues/1000](https://github.com/bigcommerce/cornerstone/issues/1000)
[https://stencil.bigcommerce.com/docs/handlebars-helpers-reference](https://stencil.bigcommerce.com/docs/handlebars-helpers-reference)
=> Category sidebar display & copyright year in footer

templates/components/common/footer.html, templates/pages/category.html
Reverts bigcommerce/cornerstone#1001
This has caused a side effect in which "shop by price" filter which was showing without faceted search no longer shows up.
https://jira.bigcommerce.com/browse/STENCIL-3438
@bigcommerce/stencil-team @shanth100 @bc-jason @lord2800
=> Revert "Category sidebar display & copyright year in footer"

CHANGELOG.md, assets/js/theme/product.js, templates/components/products/product-view.html
Swaps 'writeReview' for 'write_review' so that the link in email works and the fix for https://github.com/bigcommerce/cornerstone/issues/984 remains in place.
- [STENCIL-3508](https://jira.bigcommerce.com/browse/STENCIL-3508)
- [STENCIL-3352](https://jira.bigcommerce.com/browse/STENCIL-3352)
http://recordit.co/kKCS6DCywV
cc @bigcommerce/stencil-team @bookernath
=> STENCIL-3508

CHANGELOG.md, templates/pages/category.html
Three products are displayed per row on category pages if one or more of these three conditions are met.
A) Faceted search is enabled.
B) Category contains subcategories.
C) Shop by price is enabled
If none are met, the main content area remains at 75% width, leaving a quarter of the content area empty. This is due to the styling of .page-sidebar + .page-content.
Using the {{or}} operator, verify if either of the three conditions are met. If neither are true, page content will stretch 100% and display four products by default.
- [#1000](https://github.com/bigcommerce/cornerstone/issues/1000)
=> Restore four products per row on category pages when sidebar is empty.

CHANGELOG.md, assets/js/theme/common/gift-certificate-validator.js
Before we had a Gift Certificates API for the creation or import of gift certificates from another system, gift certificates in BC were all of a single format, alphanumeric with hyphens like this:
AAA-AAA-AAA-AAA
However, now we have the API and 3rd parties are welcome to import certificates of an arbitrary format.
However, Cornerstone still validates the old format, which will cause these imported certificates to fail. Making this change to fix that and allow any format.
- [STENCIL-3533](STENCIL-3533)
=> STENCIL-3533 Remove gift certificate format validation

CHANGELOG.md, templates/components/common/header.html, templates/layout/amp-iframe.html, templates/layout/base.html
`{{template_file}}` is deprecated, so better to use the `{{template}}` property.
=> Remove usage of deprecated {{template_file}} property

CHANGELOG.md, assets/scss/layouts/products/_productList.scss, templates/components/products/list-item.html
Brings back “Quick View” for list view mode.
See [issue #971](https://github.com/bigcommerce/cornerstone/issues/971)
*Desktop sized screens*
*Medium sized screens*
*Mobile sized screens*
=> Reinstate Quick View on product list mode when set to list view

CHANGELOG.md, assets/scss/layouts/products/_productView.scss, config.json, schema.json, templates/components/products/description-tabs.html, templates/components/products/description.html, templates/components/products/product-view.html
Apologies for the multiple PR. Struggling to figure out what I broke when merging branches/squashing commits.
Allow the ability to disable displaying product descriptions in tabbed containers.
=> Toggle displaying product description/warranty in tab format

CHANGELOG.md, assets/scss/components/stencil/productView/_productView.scss
Product image obscures product details when scaling down the viewport.
A minimum width and height of 366px solves the overlap issue. Setting
display to initial as an alternative solution breaks product zoom.
See [issue #966](https://github.com/bigcommerce/cornerstone/issues/966)
The red border is just for demonstration purposes.
**`display: initial` breaking out of container**
**Before**
**After**
=> Product Images obscure product details on smaller viewports

CHANGELOG.md, templates/components/common/header.html, templates/components/products/product-view.html
Cornerstone with Region tags added to default locations.
- [MERC-2436](https://jira.bigcommerce.com/browse/MERC-2436)
=> Add Dynamic Content Regions to Cornerstone - MERC-2436

CHANGELOG.md, assets/scss/components/foundation/type/_type.scss
Fixes a bug that showed up in Theme Editor where changing the H1 font size affected H2's because the same style (using the H1 font size) was being applied to both types of heading.
- [STENCIL-3592](https://jira.bigcommerce.com/browse/STENCIL-3592)
cc @bigcommerce/stencil-team @shanth100
=> STENCIL-3592 - Fix H1-H6 font-sizing

CHANGELOG.md, assets/js/theme/common/carousel.js, assets/js/theme/global.js
In an effort to reduce the size of the theme bundle, I've pointed two libraries to their minified versions.
**Bundle, before history.min.js**
**Bundle, after history.min.js**
**Bundle, before slick.min.js**
**Bundle, after slick.min.js**
**Bundle, after both history.min.js and slick.min.js**
=> Reduce theme bundle size by using specific minified libraries

CHANGELOG.md, config.json, schema.json, templates/pages/category.html
Adds an on/off toggle to the theme editor for the "Shop by Price" panel located on category pages:
After adding the feature, I also tested it alongside faceted search and subcategories which live within the same sidebar. Everything works as expected. See video below.
- https://jira.bigcommerce.com/browse/STENCIL-2599
https://www.screencast.com/t/Tk4mU7K5s
=> STENCIL-2599: Adds on/off toggle for Shop by Price.

assets/scss/components/stencil/socialLinks/_socialLinks.scss
This PR fixes the spacing issue between the google plus icon and the other icons
https://jira.bigcommerce.com/browse/STENCIL-3153
=> STENCIL-3153: Fix google plus spacing

CHANGELOG.md, assets/js/theme/account.js, assets/js/theme/auth.js, assets/js/theme/contact-us.js, assets/js/theme/gift-certificate.js, assets/js/theme/product.js, assets/js/theme/product/reviews.js, lang/en.json, templates/components/account/edit-account.html, templates/components/account/messages-form.html, templates/components/page/contact-us-form.html, templates/components/products/modals/writeReview.html, templates/pages/account/orders/details.html, templates/pages/auth/forgot-password.html, templates/pages/auth/login.html, templates/pages/gift-certificate/purchase.html
Move some hard-coded validation messages over to the language file
=> Move some validation messages to lang file

CHANGELOG.md, templates/components/cart/gift-certificate-input.html
IDs not unique in Shopping Cart for Coupon Code & Gift Certificate (they both use id=”couponcode”)
Make IDs to be unique for accessibility 
https://jira.bigcommerce.com/browse/CHECKOUT-1671
Before:
- Coupon code:
- Gift certificate:
After:
- Gift certificate:
=> CHECKOUT-1671 Use different id for gift cert in cart page

CHANGELOG.md, webpack.conf.js
In additional effort to #1037/#1038 and reduce the size of the theme bundle, I've pointed `async`, `jquery-zoom`, and `pace` to their minified versions.
**before**
**after**
=> Reduce theme bundle size by using minified libraries

CHANGELOG.md, assets/scss/settings/global/_global.scss
* Adds global sass $include-html-classes variable for easy exposure of Foundation styles from Citadel.  Simply set `$include-html-classes` to `true`.
* before scenario:  i try to include some basic Foundation 5 styles such as grid and panel:
```html
<div class="body">
{{#block "hero"}} {{/block}}
<div class="container">
{{#block "page"}} {{/block}}
</div>
{{> components/common/modal}}
<div class="row">
<div class="small-2 columns">2 columns</div>
<div class="small-10 columns">10 columns</div>
</div>
<div class="row">
<div class="small-3 columns">3 columns</div>
<div class="small-9 columns">9 columns</div>
</div>
<div class="panel callout radius">
<h5>This is a callout panel.</h5>
<p>It's a little ostentatious, but useful for important content.</p>
</div>
</div>
```
and they don't show up: …
=> Add global Sass variables to easily toggle exposure of Foundation styles from Citadel

CHANGELOG.md, assets/scss/components/stencil/socialLinks/_socialLinks.scss
* fixes width of google plus social icon position
- [STENCIL-3153](https://jira.bigcommerce.com/browse/STENCIL-3153)
=> STENCIL-3153 - Fix google plus social icon position

CHANGELOG.md, templates/components/common/footer.html
Hide brands in the footer if there are no brands, hide Info section in the footer if address isn't provided
https://jira.bigcommerce.com/browse/CRO-314
https://jira.bigcommerce.com/browse/CRO-179
epic is here https://jira.bigcommerce.com/browse/CRO-9
@junedkazi @mcampa please ping anyone else needed
=> CRO-169: also includes CRO-314 and CRO-179. Hide brands in the footer if

CHANGELOG.md, assets/scss/components/citadel/forms/_forms.scss
This change allows the title tag to appear when shoppers hover over product swatches.
https://jira.bigcommerce.com/browse/STENCIL-3384
**Color Swatches Before/After:**
**Pattern Swatches Before/After:**
=> STENCIL-3384: Makes title tag appear on hover for swatch options.

CHANGELOG.md, lang/en.json, templates/pages/errors/403.html
Change the 403 page message to be more friendly
https://jira.bigcommerce.com/browse/STENCIL-3559
=> STENCIL-3559 403 error message

CHANGELOG.md, lang/en.json, templates/pages/errors/403.html
Just a quick fix of the wording
@bc-mkatz @bigcommerce/stencil-team
=> STENCIL-3559 403 page message fix

CHANGELOG.md, config.json, templates/components/products/bulk-discount-rates.html, templates/components/products/card.html
Add bulk discount rates to product cards
https://jira.bigcommerce.com/browse/STENCIL-3695
=> STENCIL-3536 bulk discount rates

CHANGELOG.md, assets/scss/layouts/products/_productSaleBadges.scss
Cornerstone - 'Burst' Sale Badge Does Not Display Text
Adding a higher z-index to the text div.
https://jira.bigcommerce.com/browse/STENCIL-3374
=> STENCIL-3374 add higher z-index to display text over burst image.

CHANGELOG.md, assets/scss/layouts/products/_productList.scss, templates/components/products/card.html, templates/components/products/list-item.html, templates/components/products/list.html
This PR fixes a couple of things;
- In list view do not show "Add to Cart" on Storefront when Products are Disabled for Purchase.
- Added the "Pre order" cart action as it was missing.
- Fix the bug where the buttons were getting slightly cut off
- Updated "choose options" to not be a primary option to match grid view
- Login for pricing in list view
- Add to cart url for pre-order products since it was just redirecting to product detail page
https://jira.bigcommerce.com/browse/STENCIL-3383
https://jira.bigcommerce.com/browse/STENCIL-3353
@bigcommerce/stencil-team @bc-ranji @cristycarpenter
=> STENCIL-3383 Do not show add to cart on disabled products.

CHANGELOG.md, assets/scss/components/stencil/navPages/_navPages.scss, assets/scss/settings/stencil/navPages/_settings.scss
This change ensures the alternative navigation menu and its submenus always have the proper background length no matter how many categories a merchant has. 
https://jira.bigcommerce.com/browse/STENCIL-3380
Before/After for Main Menu:
https://www.screencast.com/t/Dueilwqbp
Before/After for Submenus:
https://www.screencast.com/t/qOgJbQnM
=> STENCIL-3380: Adds auto height to alternative nav menu and submenus.

CHANGELOG.md, assets/scss/components/stencil/productView/_productView.scss
Product images are overlapping product details on smaller viewports. This was fixed for product pages via this commit:
https://github.com/bigcommerce/cornerstone/commit/9fd0ea21c6eecdf1a616fc35412fbfd21414251d
However, the issue is still present for Quick View. This PR fixes both. Tested fix on Safari, Firefox, and Chrome. 
https://jira.bigcommerce.com/browse/STENCIL-3130
**BEFORE**
**AFTER**
**VIDEO**
http://www.screencast.com/t/7LvuVqYXeGe
=> STENCIL-3130: Fix img overlapping details on product page and Quick View

CHANGELOG.md, templates/components/products/options/product-list.html
Selects product pick list option 'none' by default if that is what a merchant has specified in his or her control panel settings. See video below.
https://jira.bigcommerce.com/browse/STENCIL-3289
Can download before and after video here:
http://www.screencast.com/t/TxxboMdlz7
=> STENCIL-3289: Allows 'none' to be default selection on pick lists.

CHANGELOG.md, assets/scss/components/stencil/applePay/_applePay.scss
Remove an unnecessary `display: block` rule that was causing the Apple Pay button to appear in the Cart Modal even for browsers that do not support Apple Pay.
Shopper confusion. The rule in question is ignoring the `apple-pay-supported` class that gets attached to the `body` element, forcing the button to appear in all browsers. My first solution was to fix this by changing the nesting of the rules to respect this class, but then I realised that the `display: block` rule itself is unnecessary, because it will be inherited from the rule defined on L33. 
Since I can't enable Apple Pay for local development, I have screenshots showing the HTML structure in Chrome and Safari respectively to prove that this should work.
Ping @bigcommerce/stencil-team @bigcommerce/payments
=> PAYMENTS-1160: Ensure Apple Pay button is hidden for incompatible browsers.

CHANGELOG.md, assets/scss/optimized-checkout.scss
Styling of the new checklist radio buttons in optimized checkout.
We changed the checklist from:
to: 
To make it more obvious that it is a `radio buttons list`.
Because of that, we need to include some `(s)CSS` in cornerstone to match the different theme designs. 
https://jira.bigcommerce.com/browse/CHECKOUT-2461
||Before|After
|---|---|---|
|Light|![light-before](https://user-images.githubusercontent.com/4542735/30732448-f813743c-9fb5-11e7-937e-9c21c2f7fe17.png)|![light-after](https://user-images.githubusercontent.com/4542735/30732604-b2375f40-9fb6-11e7-98e6-26c11110002a.png)|
|Bold|![bold-before](https://user-images.githubusercontent.com/4542735/30732552-7699011e-9fb6-11e7-899b-8af0a3dfc4ce.png)|![bold-after](https://user-images.githubusercontent.com/4542735/30732616-bf7e2b5c-9fb6-11e7-9 …
=> CHECKOUT-2461 Style optimized checkout checklist radios buttons

CHANGELOG.md, assets/js/theme/common/product-details.js
Selecting an option does not change the UPC to the UPC set on that option's SKU. The UPCs should change based on the option selected & should display the UPC of the option.
https://jira.bigcommerce.com/browse/STENCIL-3639
=> Update product UPC when options are selected

CHANGELOG.md, assets/scss/components/stencil/productView/_productView.scss
When we try to update product thumbnail image dimension in theme editor to a dimension smaller than 50x50 which is the max limit for the thumbnail it tries to scale & stretch the image
- https://jira.bigcommerce.com/browse/STENCIL-3499
=> STENCIL-3499 Do not scale product thumbnail images

CHANGELOG.md, config.json, lang/en.json, schema.json, templates/components/products/product-view.html
Adds toggle settings to the theme editor for displaying (or not displaying) weight and dimensions on product pages.
This is a feature request from customers as documented here:
- https://jira.bigcommerce.com/browse/STENCIL-3527
Video of working changes: https://www.screencast.com/t/juQ8DUTeG3F8
=> STENCIL-3527: Adding toggle for weight and dimensions on product pages.

assets/scss/components/vendor/slick/_slick.scss, templates/components/carousel.html
Use `anticipated` option rather than `ondemand` for slick carousel lazy loading. The `ondemand` option has a bug that causes the first slide not to appear while sliding in when wrapping back around from the last slide.
Also, set `z-index` of the slick arrows to 1. Prior to this the left arrow was not appearing.
- [STENCIL-3961](https://jira.bigcommerce.com/browse/STENCIL-3961)
=> STENCIL-3961 Switch slick library to 'anticipated' lazy load

assets/js/theme/common/faceted-search.js, assets/js/theme/common/form-utils.js
Lodash 4.0 and above removed the deprecated alias `_.contains` for the function `_.includes`. We were using the deprecated version in a few places, causing these functions to fail after updating lodash. This manifested in the State field in the new account form failing to change properly from a dropdown to a text field (and vice versa) as different Countries were selected.
It's quite possible this had other detrimental effects as well, as this function was also being used in faceted search.
- [STENCIL-3962](https://jira.bigcommerce.com/browse/STENCIL-3962)
=> STENCIL-3962 Use _.includes rather than _.contains

assets/scss/components/stencil/cart/_cart.scss, assets/scss/components/stencil/previewCart/_previewCart.scss
Adds spacing between "Additional Checkout Buttons" such as PayPal, PayPal Credit and VisaCheckout on the Cart and Cart Preview pages.
- [PAYMENTS-1945](https://jira.bigcommerce.com/browse/PAYMENTS-1945)
**Cart Page**
**Cart Preview Modal**
@bigcommerce/payments @davidchin @icatalina @supercrabtree
=> PAYMENTS-1945 - Add spacing between checkout buttons

templates/components/faceted-search/facets/hierarchy.html, templates/components/faceted-search/facets/multi.html, templates/components/faceted-search/facets/range.html, templates/components/faceted-search/facets/rating.html
For stores that implement faceted search on category and search pages, the list of filters can be limited to a specific number with the rest revealed after a 'show more' link is clicked. When the name of the filter or facet contains a space, the `show more` link does not work.
This fix uses the `hypenate` Handlebars filter to remove spaces before the facet name is applied as a DOM selector.
- [STENCIL-3567](https://jira.bigcommerce.com/browse/STENCIL-3567)
- ...
=> fix(storefront): STENCIL-3567 Fix spaces in faceted search option names

CHANGELOG.md, templates/components/products/card.html, templates/components/products/price-range.html, templates/pages/compare.html
* shows price ranges instead of prices when they are present in the context on product list pages (PLP)
- [STENCIL-3974](https://jira.bigcommerce.com/browse/STENCIL-3974)
@bigcommerce/stencil-team - this is ready to go
=> STENCIL-3974 - PLP Price Ranges

CHANGELOG.md, config.json, package.json
A description about what this pull request implements and its purpose. Try to be detailed and describe any technical details to simplify the job of the reviewer and the individual on production support.
- [STENCIL-4123](https://jira.bigcommerce.com/browse/STENCIL-4123)
* Before
* After
cc @bigcommerce/stencil-team
=> STENCIL-4123 - Bump stencil-utils version

CHANGELOG.md, templates/components/carousel.html
Allows carousel slide links to work in IE and Edge. 
- https://jira.bigcommerce.com/browse/STENCIL-2497
Before and after video: https://www.screencast.com/t/mlb6Nd3h
Links still work in Chrome, Firefox, and Safari too. Button links also still functional.
=> STENCIL-2497: Makes carousel links functional in IE and Edge.

CHANGELOG.md, templates/components/carousel.html
Add image width & height for carousel images.
- [STRF-4056](https://jira.bigcommerce.com/browse/STRF-4056)
=> STRF-4056 Add image width & height for carousel images.

CHANGELOG.md, assets/scss/layouts/products/_productGrid.scss
* `config.json` overode `homepage_featured_products_column_count` for Bold themes, causing the clickabilty to break.
- [STRF-4158](https://jira.bigcommerce.com/browse/STRF-4158)
ping @bigcommerce/stencil-team
=> STRF-4158 - Fix Bold Featured Products Clickability

CHANGELOG.md, assets/scss/components/citadel/forms/_forms.scss
* puts `pointer-events` prop under small breakpoint to fix swatch toggling style bug
- [STRF-4031](https://jira.bigcommerce.com/browse/STRF-4031)
=> STRF-4031 - Fixes mobile swatch selectability styling.

CHANGELOG.md, templates/pages/checkout.html
This PR addresses a bug where the logo does not show up on the UCO cart page. This is due to some libraries required for lazy loading not being included on the UCO page. 
[STRF-4138](https://jira.bigcommerce.com/browse/STRF-4138)
cc @bigcommerce/stencil-team
=> Bug Fix: Remove lazy loading from UCO header

.eslintrc, CHANGELOG.md, assets/scss/components/foundation/lazyLoad/_lazyLoad.scss
* Fixes issue where the order image would overlap order information (for Firefox)
- [STRF-4220](https://jira.bigcommerce.com/browse/STRF-4220)
cc @BC-EChristensen - wondering if you have any concerns with this change, as it relates to lazy loading of the images?
=> STRF-4220 - Fix image-overlap on Orders page

CHANGELOG.md, assets/scss/components/stencil/productView/_productView.scss
Users are unable to scroll on product pages when images are on the screen due to the zoom image feature.  This PR addresses that by disabling image zoom for smaller screen sizes.
- [STRF-4154](https://jira.bigcommerce.com/browse/STRF-4154)
- ...
=> STRF-4154: Disable pointer events and product image zoom for mobile

CHANGELOG.md, assets/scss/components/foundation/lazyLoad/_lazyLoad.scss, assets/scss/components/stencil/account/_account.scss
* this fixes a bug introduced by #1137.  now `position: relative` is only used for 'account' pages which includes the orders page
- [STRF-4302](https://jira.bigcommerce.com/browse/STRF-4302)
=> STRF-4302 - Fix mis-sized product images

CHANGELOG.md, templates/components/amp/products/product-view.html
There was a duplicate attribute for 'sandbox' on the <amp-iframe> in the /templates/components/amp/products/product-view.html file. This is to remove the duplicate.
Normally the second attribute would not be rendered, but Google checks the source not the rendered DOM.
[JIRA STRF-4326](https://jira.bigcommerce.com/browse/STRF-4326)
=> Removes duplicate sandbox attribute from amp-iframe element.

CHANGELOG.md, config.json, schema.json, templates/components/products/card.html, templates/components/products/price-range.html, templates/components/products/price.html
-Remove "as low as" feature (no longer needed with price ranges)
-Add new "price range" boolean theme editor setting, defaulting to true, to display ranges
-Augment price component to support ranges if available and enabled (graceful fallback for stores not enabled)
-Update schema.org to use PriceSpecification so that we can correctly support ranges and also inc tax/exc tax
- [CATALOG-1447](https://jira.bigcommerce.com/browse/CATALOG-1447)
- [CATALOG-1450](https://jira.bigcommerce.com/browse/CATALOG-1450)
- This effectively removes support for display of Retail Price when there's a price range. This is intentional, because it might not make too much sense to display a singular Retail Price in conjunction with a price range. As retail …
=> CATALOG-1447 - Update product cards to use price ranges

CHANGELOG.md, assets/js/theme/common/product-details.js, assets/js/theme/global/modal.js, assets/js/theme/wishlist.js, assets/scss/components/foundation/dropdown/_dropdown.scss, lang/en.json, templates/components/account/add-wishlist.html, templates/components/common/wishlist-dropdown.html, templates/components/products/product-view.html
* wish list dropdown with the ability to select which wish list to add a product to
* normalizes Wish List copy 
* depends on:
*  https://github.com/bigcommerce/bigcommerce/pull/22461
*  https://github.com/bigcommerce/bigcommerce/pull/22732
- [STRF-2471](https://jira.bigcommerce.com/browse/STRF-2471)
=> STRF-2471 - Multiple Wish Lists

CHANGELOG.md, assets/js/theme/global/modal.js
* there was a bug where the modals weren't closing due to the stop propagation call which was wired incorrectly.
- [STRF-4390](https://jira.bigcommerce.com/browse/STRF-4390)
=> STRF-4390: Fix event delegation error

CHANGELOG.md, templates/pages/order-confirmation.html
The image for the order-confirmation.html was not loading, and as with the issue in [STRF-4138](https://jira.bigcommerce.com/browse/STRF-4138), I've removed the lazyload for the logo for this template page.
- [STRF-4138](https://jira.bigcommerce.com/browse/STRF-4138)
- [STRF-4373](https://jira.bigcommerce.com/browse/STRF-4373)
[Before](https://www.screencast.com/t/VRojxYj1y8)
[After](https://www.screencast.com/t/cyl6e8sv1)
=> STRF-4373: Removing lazyload for logo in order-confirmation.html

CHANGELOG.md, config.json, schema.json, templates/layout/amp.html, templates/pages/amp/category.html, templates/pages/amp/product.html
Adds support to consume AMP ID (on the product and/or category rather than config)
- [STRF-4282](https://jira.bigcommerce.com/browse/STRF-4282)
- [STRF-4245](https://jira.bigcommerce.com/browse/STRF-4245)
http://g.recordit.co/eD9i23HoIt.gif
http://g.recordit.co/RpAKTvRMxh.gif
ping @bigcommerce/storefront-team @bookernath
=> STRF-4282 - Add support in Cornerstone to consume AMP ID

CHANGELOG.md, assets/scss/components/stencil/heroCarousel/_heroCarousel.scss
The slick-next and slick-prev nav arrows for the carousel had a top spacing of 20% which on smaller screens pushed them very close to the top of the page, and not centered like it is on medium and large size devices. This fix, allows the nav arrows to be centered across all device screen sizes.
https://jira.bigcommerce.com/browse/STRF-4340
ping @junedkazi @mjschock
=> STRF-4340 Set slick-next/prev to have top 50%

CHANGELOG.md, assets/js/theme/common/product-details.js, package.json, templates/components/products/bulk-discount-rates.html, templates/components/products/product-view.html
Price Lists support different bulk pricing tiers for each variant, so we need to update the viewModel whenever these tiers change.
- [CATALOG-2408](https://jira.bigcommerce.com/browse/CATALOG-2408)
=> CATALOG-2408 - Bulk Pricing updates per-variant

assets/js/theme/common/product-details.js, templates/components/products/options/input-checkbox.html, templates/components/products/options/product-list.html, templates/components/products/options/set-radio.html, templates/components/products/options/set-rectangle.html, templates/components/products/options/set-select.html, templates/components/products/options/swatch.html
Fix price reflowing when there are no default options, which was overriding price ranges. We will now only update the PDP view when there are default option values, which will mirror the behavior of actually clicking on those options.
I took @bc-jz 's advice that it's better to override price ranges when there are default option values, so they do get overridden in that case to set shopper expectation around what price they'll get if they press "add to cart" right away.
As a future improvement, we might maintain price ranges if there are required options without default values (meaning I must click at least one option before I can add to cart). Might make sense to keep the range around in that case.
- [CATALOG-2408](https://jira.bigcommerce.com/browse/CATALOG-2408)
ping …
=> CATALOG-2408 Fix updateView firing when there are no default options

assets/js/theme/common/product-details.js
Previous PR was removing catalog bulk pricing rules if the bulk pricing experiment was off for a store. We should make sure not to delete information in that case. This change reduces dependency on the deployment of another feature.
ping @mjschock
=> Don't clear bulk pricing rules when feature is disabled.

CHANGELOG.md, assets/js/theme/common/select-option-plugin.js
* product options weren't being added back for dropdowns after they had been hidden.
- [STRF-4496](https://jira.bigcommerce.com/browse/STRF-4496)
* before
* after
=> STRF-4496 - Fix product options not indexing issue

CHANGELOG.md, templates/components/products/price.html
* fixes schema.org microdata ItemAvailability for product pages
* the `product.availability` field maps to the Availability text field under a product's Other Details section and therefore does not necessarily satisfy the enumerated fields for ItemAvailability.  now we're explicitly selecting one of those enums depending on the product's fields.  note that this will always show InStock when 'Track inventory by options' is enabled, regardless of the stock level of a variant.
- [STRF-3168](https://jira.bigcommerce.com/browse/STRF-3168)
- https://forum.bigcommerce.com/s/question/0D51B00004ANw0v/here-is-an-improved-code-for-itemprop-availability-in-cornerstone-stencil-theme
* before
* after
=> STRF-3168 - ItemAvailability schema for products

CHANGELOG.md, templates/pages/account/orders/invoice.html
* fixes the invoice.css styles which were broken because the cdn helper doesn't properly handle configId.  they're now using the stylesheet helper like the others.
- [STRF-4502](https://jira.bigcommerce.com/browse/STRF-4502)
* after
* before
=> STRF-4502 - Fix invoice styles

CHANGELOG.md, templates/components/common/breadcrumbs.html
Adds microdata schema for breadcrumbs.
=> Add schema microdata for breadcrumbs

templates/layout/base.html
This PR tries to use Web font loader & tries to load the webfonts async so it is no longer a blocking call.
**This PR is POC only. If we decide to go down this route this work needs to be moved in paper-handlebars repo.**
=> Load google fonts async

templates/layout/base.html
It adds `dns-prefetch` & `preconnect` to domain names which we know we are going to hit.
This notifies the client that there are assets we'll need later from a specific URL so the browser can resolve the DNS as quickly as possible. Say we need a resource, like an image or an audio file, from the URL example.com. In the <head> of the document we'd write:
Much like the DNS prefetch method, preconnect will resolve the DNS but it will also make the TCP handshake, and optional TLS negotiation. It can be used like this:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types
- https://css-tricks.com/prefetching-preloading-prebrowsing/
- https://www.igvita.com/2015/08/17/eliminating-roundtrips-with-preconnect/
Check `link` in the …
=> Add dns prefetch & preconnect for urls we know we are going to hit

templates/layout/base.html
Preload the loading.svg file because we know we'll need it.
=> Preload the preloading svg since we know we will need it

.travis.yml, assets/js/app.js, assets/js/theme/account.js, assets/js/theme/auth.js, assets/js/theme/brand.js, assets/js/theme/cart.js, assets/js/theme/category.js, assets/js/theme/compare.js, assets/js/theme/contact-us.js, assets/js/theme/global.js, assets/js/theme/page-manager.js, assets/js/theme/product.js, assets/js/theme/search.js, assets/js/theme/wishlist.js, karma.conf.js, package.json, stencil.conf.js, webpack.common.js, webpack.dev.js, webpack.prod.js
* Upgrade to webpack 4
* Clean up stencil bootstrap
* Simplify interface for PageManager and get rid of async library dependency
* Get rid of html5-history-api library dependency (no longer needed)
* Get rid of fastclick library dependency (no longer needed)
* Upgrade several babel dependencies
* Separate webpack config into common, dev, prod, and add npm scripts to build
* Get rid of minifications in babel loader, instead rely on webpack
* Get rid of LoaderOptionsPlugin
* Get rid of CommonsChunkPlugin (webpack 4 will automaticaly do this for prod)
* Initial load of javascript is down from 450kb to 350kb. This PR lowers time to first paint by 50ms and time to first interactive by 210ms.
=> Webpack 4 + Javascript optimizations

CHANGELOG.md, templates/components/amp/products/card.html, templates/components/amp/products/list-item.html
* Instead of hardcoding 300x300, use the actual image dimensions
for product images on the product list
=> STRF-4527: Fix amp image sizes

CHANGELOG.md, templates/components/amp/common/navigation-menu.html, templates/components/amp/common/quick-search.html
* removes the AMP quick-search page and page include
- [STRF-4526](https://jira.bigcommerce.com/browse/STRF-4526)
* before:
* after:
=> STRF-4526 - Remove AMP quick-search

CHANGELOG.md, templates/pages/checkout.html, templates/pages/order-confirmation.html
Adds support for rendering head.scripts on the checkout and order_confirmation pages.
- [MERC-3034](https://jira.bigcommerce.com/browse/MERC-3034)
N/A
=> MERC-3034: Add head.scripts reference to checkout & order_confirmation pages

CHANGELOG.md
The CHANGELOG entry for the head.scripts change is currently under the wrong section. This moves the entry to the correct position.
N/A
N/A
=> Updates to fix changelog entry

CHANGELOG.md, assets/js/theme/common/product-details.js
refrain from updating the price shown on
quickview by default when the modal is rendered unless theres an
actual default selection to be made.
- [Ticket](https://jira.bigcommerce.com/browse/CATALOG-3085)
Before: The quickview page would instantly make a request for stock/price based on selection even if the product doesnt have a default selection, which would result in getting the base price.
After: The quickview page still makes the default request so that it can mark things as OOS when necessary, but it doesnt try to change the price in the view if its not applicable.
=> fix(catalog): CATALOG-3085 default selection in quickview

CHANGELOG.md, templates/components/common/search-box.html
The search box on the 403 and 404 pages displayed poorly in mobile viewports. Adding the `.wrap` class to the `form-prefixPostfix` div sets `flex-wrap: wrap;`
**Before**
**After**
**References**
- https://github.com/bigcommerce/cornerstone/issues/1168
=> Fix broken 403/404 page search box in mobile

assets/js/app.js
Right now, if no contextJSON argument is passed to the stencilBootstrap function, JSON.parse will try to parse an empty object, which will throw a SyntaxError because the argument supplied is not a string.
N/A
N/A
=> parse '{}' instead of empty object in app.js to avoid SyntaxError

CHANGELOG.md, templates/components/category/sidebar.html, templates/pages/category.html
Added the theme setting check for the shop by price sidebar
https://jira.bigcommerce.com/browse/STRF-4679
@bigcommerce/platform-engineering @bigcommerce/storefront-team
=> STRF-4679 - fixing product layout when sidebar off

CHANGELOG.md, assets/scss/layouts/header/_header.scss, schema.json, templates/components/common/header.html, templates/components/common/store-logo.html
* Our lazy loading solution relies on advance knowledge of the image dimensions. When `logo_size` is set to `original` in the theme settings, we don't have this information. For large logos, this leads to overlapping of the menu.
* For original sized images, don't use lazy loading or reserving space for the image via absolute positioning. Hopefully not many users will use this setting because it will impact frontend performance. To partially mitigate this, I reordered the options for `logo_size` so our optimized setting appears first in the list.
* The large diff in `schema.json` is due to changing the line endings from dos to unix. The only change of substance is reordering the options for `logo_size`
- [Jira](https://jira.bigcommerce.com/browse/STRF-4146)
=> STRF-4146: Don't lazy load logo if size is unknown

CHANGELOG.md, templates/components/amp/products/product-options.html
On a Google AMP Product Page, Options would hide Add to Cart under a very specific set of conditions. This only affected products with options.
* If a window is too short to display either options or the button, there is no issue.
* If a window is only long enough to display product options, the Add to Cart button will not appear.
* If a window is tall enough to display both options and the button, there is no issue.
It seems that some CSS is targeting what was originally `<div data-product-option-change style="display:none;">`. When this style was removed it would cause issues if Options would "push" Add to Cart below the viewable window.
Because this code is only called if there are product options to begin with (see `templates/components/amp/products/product-view`, there's no need to …
=> fix(storefront): STRF-4840 Options hide Add To Cart in AMP.

CHANGELOG.md, templates/pages/contact-us.html
Brought the `{{#if page.sub_pages}}` section in the `contact-us.html` template in line with the same section in `page.html`. This follows the workaround in the associated ticket.
- [STRF-4718](https://jira.bigcommerce.com/browse/STRF-4718)
=> fix(storefront): STRF-4718 Contact Us subpage link styling.

CHANGELOG.md, assets/js/theme/product/video-gallery.js, templates/components/products/videos.html
I originally made this just to lazyload the main video on product page load, but then I noticed that there is an existing bug that will not update the main video when the thumbnails are selected
- [1217](https://github.com/bigcommerce/cornerstone/issues/1217)
[video](https://screencast.com/t/f8jWdRIGmf4)
=> add lazyload to main video and fix thumbnail bug

CHANGELOG.md, templates/components/products/options/textarea.html
Removed whitespace appearing in a textarea (multi-line text field) product option. This whitespace appeared regardless of default placeholder text, or lack thereof.
- [STRF-4497](https://jira.bigcommerce.com/browse/STRF-4497)
=> fix(storefront): STRF-4497 Removed default whitespace in textarea product option.

templates/components/category/sidebar.html, templates/pages/category.html
Fixing faceted search display
Product layout when price list disabled & no faceted search enabled
https://jira.bigcommerce.com/browse/STRF-4679
Faceted Search Disabled/Price list disabled
Faceted Search Disabled/Price list enabled
Faceted Search enabled - price list enabled/disabled
=> STRF-4679 - fixing faceted search display

CHANGELOG.md, templates/components/blog/post.html
Blog summary content was being escaped, resulting in space characters to show up as `&nbsp;`. Now that content is being un-escaped like content in blog posts.
Note that this does not apply to all whitespace characters. Tabs are not treated as "tabs" in the summary and will not show up. Newlines are not part of the blog summary.
- [STRF-4786](https://jira.bigcommerce.com/browse/STRF-4786)
- [Handlebars HTML Escaping](http://handlebarsjs.com/#html-escaping)
Before:
After:
=> fix(storefront): STRF-4786 Do not escape blog summary HTML.

CHANGELOG.md, templates/components/amp/common/store-logo.html
⚠️  this does not fix then entire issue ⚠️ 
Store logo is distorted on AMP pages on mobile or desktop. We were not respecting the logo settings when specified.  There is still an issue however where if the image is larger than 250x50 then it doesn't get sized according to css properly. 
below is an example of it still being incorrect for too large of a logo
- [STRF-4804](https://jira.bigcommerce.com/browse/STRF-4804)
@mattolson @mjschock @Ubersmake
=> fix(storefront): STRF-4804 Fix Store Logo image size for Amp Pages

CHANGELOG.md, templates/components/products/price-range.html, templates/components/products/price.html, templates/components/products/product-view.html
We are adding schema.org offer tags on div's that schema.org doesn't care about what price was
it only cares about what price currently is afaict  I need to validate still that price-range schema works.
- [STRF-2456](https://jira.bigcommerce.com/browse/STRF-2456)
Fixed product schema with "was" and "currently" prices
=> fix(storefront): STRF-2456 Fixing Schema Org meta tags

assets/js/theme/common/product-details.js
This PR fixes the following issue:
```
jbruni@vm:~/cornerstone$ stencil bundle
Validating theme...
Running ESLint...
/home/jbruni/cornerstone/assets/js/theme/common/product-details.js
73:13  warning  Unexpected console statement  no-console
✖ 1 problem (0 errors, 1 warning)
```
N/A
N/A
=> Fix ESLint "no-console" warning

CHANGELOG.md
Adding Performance Improvements (Cornerstone 2.0) to CHANGELOG.md.
- #1229
=> Added Cornerstone 2.0 to CHANGELOG.md

templates/components/products/product-view.html
We should still show the ratings section when there are no reviews. We just don't want to show the schema meta tags with it.
@mattolson @mjschock @bigcommerce/storefront-team
=> fix(content): STRF-2456 Fix product rating reviews

assets/js/theme/common/product-details.js
address STOCK_LEVEL_DISPLAY_SHOW_WHEN_LOW 
setting for skus. We were not properly switching back and forth
between skus that were above and below their own respective
threshholds.
- [CATALOG-2913](https://jira.bigcommerce.com/browse/CATALOG-2913)
in order for this to work completely, this FE change depends on a BC pr 
please see ticket for additional info.
=> fix(catalog): CATALOG-2913 individual low inventory count for skus

assets/js/theme/account.js, assets/js/theme/common/product-details.js
The value of `this.context` is `undefined` within WishList class instance, in the product and account pages. The class `constructor` expects a `context` parameter, but no parameter is provided when the instance is created from "product-details.js" and "account.js".
This has no side-effect when no customization is made to the theme. But any customization will expect `this.context` to have the `context` data, rather than `undefined`.
I have reported it here, but it seems it has been ignored or not understood:
- https://github.com/bigcommerce/cornerstone/commit/31bdddbf64293d85192cae00e966d531f527b150#r29038225
Thank you.
=> Avoid undefined context in WishList instance

CHANGELOG.md, templates/components/amp/products/product-view.html, templates/pages/amp/product.html
This ticket effectively re-adds the logic in this PR https://github.com/bigcommerce/cornerstone/pull/1242.
We determined the test that caused us to roll back was incorrect.
=> fix(storefront): STRF-4866 Fix missing quantity/selection for AMP product Page

CHANGELOG.md, templates/components/carousel.html
Cornerstone has an issue where the first image in a carousel appears to reload on wrap. This "reload" happens despite the browser not making any new GETs.
This behavior is fixed by changing the Slick Carousel's lazy load technique back from `ondemand` to `anticipated`.
Slick Carousel's documentation has, at time of this PR, removed mentions of `anticipated` as a lazyLoad technique: https://github.com/kenwheeler/slick/blob/a2aa3fec335c50aceb58f6ef6d22df8e5f3238e1/README.markdown. The only two documented options are `ondemand` and `progressive`. `progressive` is markedly worse than `ondemand` in terms of performance. However, `anticipated` is still used to determine logic in `slick.js`, in both 1.8.1 and 1.9.0:
1.8.1: https://github.com/kenwheeler/slick/blob/ee7d37faeb92c4619ffeefeba2cc4c733 …
=> Changed Slick Carousel lazyLoad technique to Anticipated.

CHANGELOG.md, templates/components/products/bulk-discount-rates.html, templates/components/products/options/input-checkbox.html, templates/components/products/options/input-file.html, templates/components/products/options/input-numbers.html, templates/components/products/options/input-text.html, templates/components/products/options/product-list.html, templates/components/products/options/set-radio.html, templates/components/products/options/set-rectangle.html, templates/components/products/options/set-select.html, templates/components/products/options/swatch.html, templates/components/products/options/textarea.html
**Fixed issues with PR #1223** @junedkazi 
In certain circumstances, product option elements end up with the same ID causing a clash, stopping some options being selected.
Each option component has been given a descriptive ID to prevent the clash. As the add to cart action relies on the name attribute, this does not interfere with the cart system.
[Video of issue before changes](https://www.useloom.com/share/1e740a49826f44cdbd56f81bd01bd7d3)
[Video after changes](https://www.useloom.com/share/9fe6d969da9445da91532da6f301de23)
=> Fix duplicate IDs occurrence in product options in certain situations

CHANGELOG.md, assets/scss/components/stencil/navUser/_navUser.scss, templates/components/common/currency-selector.html
The arrow on the currency selector dropdown is left aligned when it needs to be right aligned.
#1254 
**Before**
**After**
=> Fix arrow placement on currency selector dropdown

CHANGELOG.md, webpack.common.js
Add webpack alias for lazysizes module so the minified library is bundled. End up saving ~10KB.
**Before**
**After**
=> Add alias for lazysizes module to bundle minified library

CHANGELOG.md, templates/components/search/quick-results.html
In theme options, if "Restrict to Login" for price display is set true, and a user searches the store while logged in, prices don't display and "Log in for pricing" message displays.
Pass the {{customer}} variable to the card component, allowing pricing to display while searching the site after logging in.
- #1240 
**Before**
**After**
=> Fix prices not showing in quick search while logged in when "Restrict to Login" for price display is true

CHANGELOG.md, assets/js/theme/product/reviews.js, assets/scss/components/foundation/tabs/_tabs.scss, config.json, schema.json, templates/components/products/description-tabs.html, templates/pages/product.html
Adds an option to display customer reviews in the details tabs area on product pages.
**False, desktop**
**False, tablet**
**False, mobile**
**True, desktop**
**True, tablet**
**True, mobile**
=> Display product reviews in tabbed content region of product page

CHANGELOG.md, templates/components/products/product-view.html
When a product has no images Cornerstone will display a default "No Image" image.
This image is zoomable, like other product images. And clicking on the image (if you can manage to click the 0x0 <a/> element) will open the full-size version of the image in the current view.
This PR removes that behavior. If a product has no images and thus displays the "No Image" image, the "No Image" image is treated like placeholder text. It does not zoom. It has no link.
- [STRF-5007](https://jira.bigcommerce.com/browse/STRF-5007)
Product Details Page:
Quick View:
Product Details Page:
Quick View:
=> Disable zoom and link for default "No Image" image.

templates/components/products/options/product-list.html, templates/components/products/price-range.html, templates/components/products/price.html
Some additional PDP pricing fixes to address missing class names so that they are more consistent, and some trivial formatting changes. The missing classes also broke tests so this should fix that. Tested such locally.
This is additional changes we found were needed during testing following:
https://github.com/bigcommerce/cornerstone/pull/1262
STRF-4701
=> STRF-4701 - Additional fixes to address missing class names

CHANGELOG.md, templates/components/products/modals/writeReview.html
Duplicate ID's were in the DOM on the write review form. This was happening because ID's weren't 
being passed to the form components.
**Before**
`{{> components/common/forms/text name="revfromname" label=(lang 'products.reviews.form_write.name') value=product.reviews.author}}`
**After**
`{{> components/common/forms/text id="writeReview-name" name="revfromname" label=(lang 'products.reviews.form_write.name') value=product.reviews.author}}`
- #1265 
**Before**
**After**
=> Fix duplicate input ID's in product review form

CHANGELOG.md, templates/components/products/product-view.html
Revert changes to disable zoom and link behavior on "No Image" image: https://github.com/bigcommerce/cornerstone/pull/1278
This naively assumed that a product without an image would only have variants without images. This isn't the case, and was caught by one of the data sets in ProductOptionRuleUITest::testProductOptionRules
- [STRF-5007](https://jira.bigcommerce.com/browse/STRF-5007)
=> Revert #1278

CHANGELOG.md, assets/js/theme/product/reviews.js, assets/scss/components/foundation/tabs/_tabs.scss, config.json, schema.json, templates/components/products/description-tabs.html, templates/pages/product.html
Revert "Display product reviews in tabbed content region of product page:" #1273 
This is pretty awesome and needs to be revisited, but will not make it into 2.2.0. Current issues are:
* Default behavior has changed for non-tabbed reviews. Reviews should be *hidden* by default when opening a product page.
* When reviews are tabbed, they still have the "Hide Reviews" option, which is unnecessary in this configuration.
- [#1273](#1273)
=> Revert #1273

CHANGELOG.md, webpack.dev.js, webpack.prod.js
I've found that the usage of `webpack.DefinePlugin` at Cornerstone's Webpack configuration is wrong:
```javascript
new webpack.DefinePlugin({
'process.env.NODE_ENV': 'development',
}),
```
According to official DefinePlugin documentation, _if the definition value is a string, it will be used as a code fragment_.
The plugin _does a direct text replacement_. The recommended way, broadly used, and also referred in official documentation, is to wrap the string in a `JSON.stringify` call:
```javascript
new webpack.DefinePlugin({
'process.env.NODE_ENV': JSON.stringify('development'),
}),
```
This way, in code, `process.env.NODE_ENV` will be properly substituted by the string `"development"`, instead of the literal code snippet `development`, which results in a `'development' is not defined` …
=> Fix Webpack 4 DefinePlugin config

CHANGELOG.md, webpack.common.js
Just some minor cleanup for consistency in `webpack.common.js` by removing unnecessary quotes from single string properties and use single quotes for theme bundle output path. Added benefit of removing ESLint errors thrown in Atom.
- `Strings must use singlequote. (quotes) 45:39`
- `Unnecessarily quoted property 'lazysizes' found. (quote-props) 63:13`
- `Unnecessarily quoted property 'pace' found. (quote-props) 64:13`
=> Fix minor ESLint errors in webpack.common.js

CHANGELOG.md, assets/scss/layouts/header/_header.scss
When reducing margin around the store logo parent container `.header-logo`, this can cause an issue on mobile where the logo overlaps the cart link, preventing the ability to click the link. This setting resolves that issue, while also not having any impact on stores that don't reduce the margin around the store logos.
- #1249 
- https://forum.bigcommerce.com/s/question/0D51B00003vvzbmSAA/cart-button-not-working-on-mobile-version-for-cornerstone-light
- https://forum.bigcommerce.com/s/question/0D51B00004P6KUFSA3/cart-clickable-link-doesnt-work-on-mobile-cornerstone-theme
**Before**
**After**
=> Fix cart link not being clickable on mobile when white space reduced around store logo

CHANGELOG.md, assets/js/theme/common/product-details.js, assets/scss/components/stencil/price/_price.scss, templates/components/products/price-range.html, templates/components/products/price.html
Updated PDP element styling for pricing related elements to use classes instead of in-line styling. The in-line styling does not play nicely with Google AMP.
https://jira.bigcommerce.com/browse/STRF-5084
*Google AMP Test on PDP with this Update is Passing*
=> fix(storefront): STRF-5084 - Fixed PDP pricing element styling so it works with Google AMP

CHANGELOG.md, templates/components/amp/css/base.html, templates/components/amp/products/product-options.html, templates/components/amp/products/product-view-details.html, templates/components/amp/products/product-view.html
- Moved the image on our Google AMP PDP above the product details section and moved the details inside the Google AMP iFrame so they can be adjusted by the product options JS.  This change corrects the pricing JS updates on the PDP when on an amp page. 
- Added the new pricing label hidden css classes to the base styling for google amp pages as it was missing on category pages causing the pricing elements to not hide properly.
https://jira.bigcommerce.com/browse/STRF-5101
The following shows that both PDP and Category are still passing Google Amp's test page:
To see the price updating in action visit this page and select different colors of size "small":
http://jasonzamora1531160478-testington.my-integration.zone/amp/1-l-le-parfait-jar/
This image shows the broken styling on the google …
=> fix(storefront): STRF-5101 - Fixes for product pricing JS for Google AMP on both PDP and PLP

CHANGELOG.md, assets/js/theme/common/product-details.js
#1220 but with an additional guard for non-existent tab names.
This only works on page load. Because the hash isn't technically an HTML anchor, browsers have no idea what "anchor" to view and will end up doing nothing.
Additionally, the guard for non-existent tab names might not be necessary. As far as the code is concerned the JS will attempt to operate on nothing. But `$activeTab.length > 0` definitely makes sure it doesn't run.
- PR: #1220 
- Issue: #1136 
Tab:
Definitely Not a Tab:
=> Open product tabs on load.

CHANGELOG.md, assets/js/theme/product/reviews.js, assets/scss/components/foundation/tabs/_tabs.scss, config.json, schema.json, templates/components/products/description-tabs.html, templates/components/products/reviews.html, templates/pages/product.html
Restores the changes in #1273 with the desired changes in #1281.
Adds an option to display customer reviews in the details tabs area on product pages.
- #1273 
- #1281 
Diff between this PR and the original PR/commit: https://github.com/bigcommerce/cornerstone/compare/b7370c96f044dc9019d36f3dda4483bf572e85c6...d250b521c8b9de929cdeaf5539c87604bcd72b3b
Before:
After, Current Product Review behavior:
After, Product Reviews in tabs:
=> Revisiting 'Display product reviews in tabbed content region of product page'

CHANGELOG.md, templates/components/products/product-view.html
Cornerstone shows bulk discounts available on all products that have rules associated with them, regardless of the "Enable Bulk Discount?" setting in Display Settings in Store Settings > Display.
This is reliant on a change to expose `settings.bulk_discount_enabled` to the Stencil context: https://github.com/bigcommerce/bigcommerce/pull/25352
If Bulk Discounts are enabled, bulk discounts will show on product pages with bulk discount rules associated with them, as they do now.
If Bulk Discounts are disabled, bulk discounts will not show up, even if a product has a bulk discount rule applied to it.
- [STRF-4969](https://jira.bigcommerce.com/browse/STRF-4969)
Product **Without** bulk discounts:
Product **With** bulk discounts, Bulk discounts **Disabled**:
Product **With** bulk discounts, …
=> Show bulk discounts only if enabled through store settings.

CHANGELOG.md, assets/js/theme/search.js
Added an "active" style for search result page sections/tabs.
- #1313
=> Style active section in search results.

templates/components/products/description-tabs.html
A fix for #1302. The product review tab (if enabled) should not be shown if a product has no reviews.
- #1302
=> Only show review tab when there are reviews.

CHANGELOG.md, assets/js/app.js
app.js currently includes `blog.js` code on the `blog_post` page class, rather than `blog-post.js` code. This fixes that.
=> Fix blog_post import statement in app.js

CHANGELOG.md, assets/js/test-unit/theme/carousel.spec.js, assets/js/theme/common/carousel.js, templates/components/carousel.html
Currently the carousel on the homepage having "dots" even if the carousel has only one slide. This PR is fixing this issue and dots will appear only if there are multiple slides.
- [Slick Docs](http://kenwheeler.github.io/slick/)
=> show dots only if carousel has more than one slide

CHANGELOG.md, assets/scss/components/stencil/productCarousel/_productCarousel.scss
New products are currently not left aligned. This PR will change the css of the product carousel to fix the alignment of the carousel.
It is expected that in the homepage, the featured, new and popular products show up left aligned.
=> change css for product productCarousel -> slick-track

CHANGELOG.md, assets/scss/components/stencil/navUser/_navUser.scss
In certain cases, the mini cart dropdown was displaying basically entirely out of the viewport. This corrects that problem. I also noticed an alignment problem with the mini cart css arrow and the cart quantity badge in mobile viewports. This alignment problem was there before the dropdown viewport fix but became more apparent, so this squashes that.
- #1264 
**Viewport fix, before (gif)**
**Viewport fix, after (gif)**
**Mobile alignment, before**
**Mobile alignment, after**
=> Corrects mini cart display issues

CHANGELOG.md, templates/components/products/tabs.html
#1290, but with a changelog entry (and screenshots in a PR).
- #1290
Screenshots are identical, but they're here for the record. The real fix is in *when* these attributes are set, which is what was fixed in #1290.
=> Changelog for #1290

templates/components/products/tabs.html
Just like the `is-active` class is being set for the "Customers Also Viewed" product tab initial rendering, we should also take care of the initial accessibility (`aria`) attributes for them.
- No links. Just look how the `is-active` class is handled, in the very same template file.
=> Fix initial aria attributes for 'Customers Also Viewed' products tab

CHANGELOG.md, templates/components/products/description-tabs.html
A fix for the fix (#1318) for review tabs.
The issue that arose is that when "Product reviews in tabs" is enabled that tab simply doesn't show up.
If a product has no reviews the tab still won't show up.
What probably happened with the screenshots in #1318 is that they were done through Edit Theme Files, which wasn't reflected/copied over for the code in that PR.
- #1318
=> Fix for the fix for review tabs.

lang/en.json, templates/components/account/navigation.html, templates/pages/account/payment-methods.html
Add Payment Methods to Account
- new page called Payment Methods under Account
- visibility of page to be controlled server side (experiment)
- empty for now, more content coming in future pull requests
https://jira.bigcommerce.com/browse/PAYMENTS-3143
@bigcommerce/payments @junedkazi
=> feat(payments): PAYMENTS-3143 Add Payment Methods to Account

CHANGELOG.md, assets/js/theme/product/image-gallery.js
Fixed issue with Cornerstone product image zoom functionality. If images were too small (less than 500px), zoomed image would not show properly. 
Solution: Set up a checkImage() function to check image size before easyzoom-flyout. If image is less than image container (~500px), easyzoom-flyout is hidden, else, easyzoom functions normally.
- [MERC-3743](https://jira.bigcommerce.com/browse/MERC-3743)
**Previous Zoom Function (bug)**
*Image of bug*
*Gif of bug*
**Current Zoom Function (Fix)**
=> fix(catalog): MERC-3743 Fix zoom behavior for small images in gallery

CHANGELOG.md, assets/scss/components/stencil/productCarousel/_productCarousel.scss
Reverting #1321 until we can find a better solution for all cases. New products were left-aligned, but once there were four products the fourth product would be pushed into a new row.
The caveat here is that merchants who are displaying less than four new products on Cornerstone should probably keep the changes to `_productCarousel.scss` in ca0f3cdf9bce4e32cd6fd897440d7debb3095e5d.
- [#1321]
=> Undo New Products left align from 2.3.0.

CHANGELOG.md, templates/pages/account/orders/invoice.html
Logo img in the invoice is missing. This change will add logo img to the invoice
=> change src for invoice logo image

CHANGELOG.md, stencil.conf.js
Detailed description has been written and discussed at issue https://github.com/bigcommerce/stencil-cli/issues/379
This change helps to prevent that issue to happen, because the time to be [ready for receiving messages from `stencil-cli`](https://github.com/bigcommerce/cornerstone/blob/2.3.2/stencil.conf.js#L54-L67) is dramatically reduced.
- [bigcommerce/stencil-cli GitHub issue 379](https://github.com/bigcommerce/stencil-cli/issues/379)
=> Require Webpack config only when used

CHANGELOG.md, templates/components/common/forms/select.html
This is fixing the country name options entities on the account signup form.
This fix is for Cornerstone / Other themes will need to be updated by 3rd parties such as Pixel Union
https://jira.bigcommerce.com/browse/STRF-5396
Countries with symbols & punctuation in the name are not encoding, for example:
`"Cote d&#039;Ivoire"`
**updated theme file template/components/common/forms/select.html**
**-Line 11 Was:** <option {{#if selected}} selected {{/if}} value="{{value}}">{{label}}</option>
**-Line 11 Now Is:** <option {{#if selected}} selected {{/if}} value="{{value}}">{{{label}}}</option>
=> Countries with symbols & punctuation in the name are not encoding

CHANGELOG.md, templates/components/amp/common/store-logo.html
AMP store logo didn't show up. This pr should fix that issue by setting "sizes"n attribute correctly.
- [AMP docs](https://www.ampproject.org/docs/design/responsive/art_direction)
=> Amp page error

CHANGELOG.md, templates/components/account/navigation.html
While viewing an order, the account menu item for "Orders" remains a label. This fix creates a link to allow customers to return easily to the orders status page.
#1330 
**Before**
**After**
=> Add link to order status in account menu when viewing order

CHANGELOG.md, assets/js/theme/common/product-details.js
Safari only does one iteration in the current`for of` loop. This change will create a new FormData object and append valid entries using a standard for loop instead.
Before:
After:
=> fix(storefront): STRF-5282 Unable to add products to cart with 2 or more non-required File Upload options using Safari

assets/js/theme/cart.js
Fix missing function expression name eslint warning from #1338
=> Fix eslint warning in cart.js focus event from #1338

CHANGELOG.md, assets/js/app.js, templates/layout/base.html
Here's the blueprint for more easily mapping custom templates to javascript modules (#1339) in `app.js`.
=> Blueprint for Mapping Custom Templates to JavaScript Modules

CHANGELOG.md, templates/components/products/options/product-list.html, templates/components/products/options/set-radio.html, templates/components/products/options/set-rectangle.html, templates/components/products/options/swatch.html
If an option set includes multiple similar options group for ex: multiple color options in one set, than any selection in any set reflects only on the first group.
=> added unique id for swatch options

CHANGELOG.md, assets/scss/components/vendor/slick/_slick.scss
Things get interesting on the product page image thumbnail carousel when there are a lot of images on that product.
Specifically, when there are more than 22 images the carousel navigation dots will overlap with the image thumbnails.
The way margins are set up, with a window wide enough that Cornerstone will no longer expand out, there will be up to 17 navigation dots per row. These numbers are lower on a narrower view. Using Chrome, this is reduced to 11.
This fix is only for making sure navigation dots don't overlap thumbnail images. The fix also increases the space between the thumbnails and the dots. Only navigation dots on the product page are affected. Carousel navigation on other pages, like the home page, is not.
As an aside, navigation with multiple rows will always seem weird, …
=> Fix carousel dots overlapping thumbnails on Product page.

CHANGELOG.md, schema.json
Cornerstone - Update Schema labels and organization;
Updated the labels and organization of cornerstone of schema.json entries. 
In preparation for launching Store Design, the merchandising team performed an audit on the cornerstone settings that are available finding a large number of usability gaps. As a short-term solution, the team made the following changes focusing on providing a better legibility of the setting.
- Update labels on all entries to use updated, consistent language
- Provide better organization by creating new groupings of settings
- User clarity and consistency
- [MERC-3746](https://jira.bigcommerce.com/browse/MERC-3746)
- [Store Design Spread Sheet](https://docs.google.com/spreadsheets/d/1cgpYVzrd2X1MAOvPKJjkdAX5iqn …
=> MERC-3746 cornerstone schema change

templates/components/page/contact-us-form.html, templates/pages/contact-us.html
This is my first ever submission like this on GitHub. Please tell me if I've got it all wrong.
The contact form is single page, which means it is very hard for people to track form submissions on systems like Google Analytics. There is no success page to track it as a goal.
I've developed a way to hook into the page and detect user activity via JavaScript, this JavaScript can directly send a signal to Analytics so that it can track submissions. 
But my solution, and probably anyone elses requires some minor edits to the theme.
The code needs to detect if certain elements are present. These elements indicate if the page has been submitted, or if the submission had errors (also useful to track). However the theme does not include an easy way to find those elements, and there are not always …
=> Add div and id attributes so that contact form steps can be tracked

CHANGELOG.md, assets/scss/components/stencil/navPages/_navPages.scss, templates/components/common/navigation-dropdown.html, templates/components/common/navigation-list-alternate.html, templates/components/common/navigation-list.html, templates/components/common/navigation-menu.html
A new PR for #1335 
> activePage is a active class which will be applied when any page is active. For example. If you visit any category page then this "activePage" class will be activated and that particular category name will be highlighted in different color.
The active page has the same styling as a navigation link on hover.
#1335 
Before:
After:
Before:
After:
Before:
After:
Before:
After:
=> taruntds's "Added "activePage" as a active class in navigation menu and web pages"

CHANGELOG.md, templates/components/products/options/input-checkbox.html
Added hidden input for checkbox to represent "No" for unchecked checkboxes.
=> added hidden input with no value for a checkbox

CHANGELOG.md, templates/components/common/store-logo.html
The logo is high priority content and need not be lazyloaded. In fact, it could benefit from preloading.
-Remove lazyload capability on logo image
~-If the logo _is_ an image, preload it~ will do this later
- [STRF-5475](https://jira.bigcommerce.com/browse/STRF-5475)
ping @mattolson @junedkazi @bc-zoharmuzafi
=> STRF-5475 Stop lazyloading store logo

CHANGELOG.md, package.json
This plugin is about 18 months out of date, the latest versions have some valuable fixes especially for iOS.
=> Update lazysizes to 4.1.2

CHANGELOG.md, templates/components/carousel.html
-Don't lazyload first slide (avoids FOUC and weird behavior)
-Tiny refactor replacing multiple #if statements with #and
~-rel=preload tag for first carousel slide (if present) to improve download time~ will do this later
- [STRF-5474](https://jira.bigcommerce.com/browse/STRF-5474)
ping @junedkazi @mattolson @bc-zoharmuzafi
=> STRF-5474 Improve performance of first carousel slide

CHANGELOG.md, config.json, schema.json
This adds support for customizing the look and feel of the Paypal and Braintree checkout buttons on the cart (and other) pages. Some of the options are mutually exclusive, but there's currently no way to represent that in the schema--those mutually exclusive options will simply fail to render buttons on the page, so it falls on the merchant to discover that their payment buttons don't render and select options that do. This new section is hidden when the merchant does not have Paypal or Braintree enabled as a payment gateway.
- [PAYMENTS-3071](https://jira.bigcommerce.com/browse/PAYMENTS-3071)
=> PAYMENTS-3071 Add the schema and config options for paypal smart button configuration

schema.json
Copy changes to the new Payment Buttons section, as well as some small copy tweaks to other sections.
Also fixes a bug that causes the Checkout page header background color setting to disappear if "Use background image" is not checked.
- [MERC-4097](https://jira.bigcommerce.com/browse/MERC-4097)
=> MERC-4097 Copy changes, rearrange Payment Buttons section

CHANGELOG.md, templates/components/common/breadcrumbs.html
In late August, Google updated how they processed breadcrumbs, causing schema markup to begin throwing errors when you run a site through their structured data testing tool.
**While this PR resolves those errors, it will require `{{url}}` being made available for the last [Breadcrumbs Object](https://stencil.bigcommerce.com/docs/breadcrumbs-object)** I'm not sure what that would take on your guys end, but here's the code that will help cross the finish line once that's made available.
**Before**
**With the fix, not quite fully resolved.**
**With the fix and a URL plugged into the meta tag, fully resolving the errors thrown.**
=> Fix errors in breadcrumb schema markup

CHANGELOG.md, config.json, schema.json, templates/components/carousel.html, templates/pages/home.html
Currently if you want to hide/disable the arrows on the homepage carousel, you'll need to use either CSS or add JavaScript to the bundle. This PR adds an option to the theme editor.
- https://forum.bigcommerce.com/s/question/0D51B00004StLS3SAN
- https://forum.bigcommerce.com/s/question/0D51B00003u0qGnSAI
- https://forum.bigcommerce.com/s/question/0D51B00003zdWYDSA2
**True (Default)**
**False**
**Theme Editor**
=> Add option to disable arrows on the homepage carousel

CHANGELOG.md, assets/scss/components/vendor/sweetalert2/_sweetalert2.scss
Spacing next to the cancel button on sweetalert2 modal notices was set to 0 on mobile. This PR adds a little breathing room next to the cancel button.
#1352 
**BEFORE**
**AFTER**
=> Fix spacing with SweetAlert cancel button on mobile

CHANGELOG.md, assets/js/theme/product/reviews.js
The product review modal currently returns an error message that fields are blank during pre-submit form field validation. This happens when the Subject and Comments fields have entries with 1 character. Code-wise, validation only passes when there is an input of minimum length 2.
This PR changes this so that the error message is accurate. If the forms are blank, the error message about form fields being blank will appear. If the forms are not blank, they won't.
=> Product review modal error message is now accurate.

.gitignore, CHANGELOG.md, assets/scss/components/stencil/heroCarousel/_heroCarousel.scss, assets/scss/components/stencil/productCarousel/_productCarousel.scss, templates/components/products/carousel.html
Loading Cornerstone inside an iframe on mobile safari will cause your web browser to become unresponsive. 
There look to be multiple issues at play, the first being some css changes as suggested in the linked ticket. I have also tracked down the setting which is causing another issue, it looks like something in this [block of code](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L595) is breaking on mobile safari in an iframe. 
You can reproduce this issue in isolation using the following codepen example.
Using the iPad emulator in xcode, open safari and navigate to the following page.
- https://codepen.io/pingoo/pen/BRVPxQ
Compare results against desktop web browser.
There is an open issue on Slick, the open source slider we are using.
- …
=> MERC-4196: Fixes issue with Slick slider for mobile safari

CHANGELOG.md, assets/js/theme/common/product-details.js
For some reason the quote item hash are changing. It is safer to use quote item id since it is immutable.
https://github.com/bigcommerce/cornerstone/pull/1387
- [STRF-4575](https://jira.bigcommerce.com/browse/STRF-4575)
Attach images 
or add image links here.
=> STRF-4575 Switch from quote item hash to id which is immutable

assets/js/test-unit/theme/common/payment-method.spec.js, assets/js/theme/account.js, assets/js/theme/common/payment-method.js
- Add optional card type to CVV validation helper to enforce strong type validation.
[PAYMENT](https://jira.bigcommerce.com/browse/PAYMENTS-3723)
- Wrong American Express CVV
- Right American Express CVV
- Wrong Visa CVV
- Right Visa CVV
@bigcommerce/payments @danieldelcore @bc-zoharmuzafi
=> Add optional card type validation for cvv (card managment)

CHANGELOG.md, templates/components/products/list-item.html, templates/components/products/list.html
In Cornerstone v2.6.0 compare buttons are missing from Category pages that use a List view instead of a grid.  This pr change the access level to the parent context when generating the products list display.
=> changed access level for parent context- products list display

CHANGELOG.md, assets/js/theme/common/collapsible.js
Rebased version of https://github.com/bigcommerce/cornerstone/pull/1299 by shotaK.
> #### What?
> 
> I've just duplicated a menu in `global.js` and in templates and supplied a proper context:
> 
> global.js
> ```
> menu('[data-menu]');
> menu('[data-menumobile]');
> ```
> It seemed to work fine, except when I was clicking the first menu items, the second menu items were opening. After some investigation, I've found out that the context was not specified for the targeted menu items. I've added the context to them and it worked fine.
This has no effect on Cornerstone as it is, but benefits anyone extending Cornerstone.
To test, make the following changes:
Change `/assets/js/theme/global.js` so that `menu()` is defined twice with two different contexts:
```
@@ -31,7 +31,8 @@ export default …
```
=> shotaK's Add context to the menu collapsible factory target elements

CHANGELOG.md, assets/scss/components/stencil/productCarousel/_productCarousel.scss
Changes to the New Products carousel in 2.5.2 changed how many products appeared as the view width became narrower and narrower. Specifically, it would always try to honor the number of columns set for the theme. This means that products with long words get less and less space as the view narrows, and particularly long words start overflowing into adjacent columns.
This change forces words to break if they hit the edge of the column.
This has also been verified to *not crash* Mobile Safari, which was the reason for #1371 in the first place.
- [STRF-5651](https://jira.bigcommerce.com/browse/STRF-5651)
- #1371
=> STRF-5651: Break product card titles on overflow.

CHANGELOG.md, templates/layout/base.html
Depends on https://github.com/bigcommerce/bigcommerce/pull/27154 in which we surface a new key in the context indicating if the shopper has an EU IP address.
This will only show the cookie notification for those shoppers, so that you don't bug shoppers when you aren't legally required to.
Leaving this in the theme code allows the behavior to be further customized by a theme developer if desired.
=> STRF-4612 only show cookie privacy notice for EU IP addresses

CHANGELOG.md, assets/js/theme/global.js, assets/js/theme/global/cart-preview.js, package.json, templates/components/common/navigation.html, templates/layout/base.html
This is the first step in improving storefront performance by moving most/all Cart interactions to the frontend.
This change moves all functionality related to calculating the cart quantity in the header to FE API calls, after the initial HTML loads.
In future PRs, we'll be able to actually turn off the loading of Cart details in the HTML in Cornerstone, which will improve performance, especially for large carts. However, this PR does *not* disable Cart data, it simply introduces the FE behavior.
The "last known" cart quantity is cached in `localStorage` so it loads quickly when the page loads and then it's quietly updated if new information is received from the API. There is a graceful fallback if `localStorage` is unavailable in the environment or otherwise fails (e.g. if the 5MB …
=> STRF-5640 - Load cart quantity in FE

CHANGELOG.md, config.json, templates/pages/cart.html
Disable loading the Cart resource unless we're on the cart page.
This was only used for loading the "quantity in cart", but in https://github.com/bigcommerce/cornerstone/pull/1379 we now do this with a frontend API call.
Turning this off will improve performance.
ping @junedkazi - just opening this for your convenience.
=> Disable loading of cart on non-cart pages

CHANGELOG.md, templates/components/common/share.html
defer loading of addthis for faster loading pages.
=> defer loading of addthis

CHANGELOG.md, templates/pages/cart.html
When cart has single product and it is removed - product removed event is not sent
https://jira.bigcommerce.com/browse/CP-4054
=> Fixed the issue - sending GA event for last product removed from CART.

CHANGELOG.md, templates/components/common/breadcrumbs.html
Fixed the position for breadcrumb elements to start with 1. instead of 0.
=> breadcrumbs last element

CHANGELOG.md, assets/js/theme/cart.js
This is a bug fix.
Context: change the quantity of a cart line item by manually editing the quantity input field value.
Currently, when a manual quantity change fails to succeed (for example, because it is greater than the maximum purchasable quantity), the quantity is reverted to **zero** in the input field.
It should rollback to the **previous value**. Not to zero.
This PR fixes this bug.
<hr>
It is quite simple to see what is the problem in the code:
- inside the quantity input `focus` event handler function, **`this`** is used as a reference to the event target element (jQuery binds the event target element to the event handler function context);
- as an **arrow function** is being used for the event handler function, `this` is **not** referencing the event target element, as it …
=> Fix cart item quantity change rollback

CHANGELOG.md, assets/scss/layouts/header/_header.scss
Currently the sale badge floats above menu on mobile. This change should make the header class higher than sale badge and the badge won't floats above menu on mobile.
=> changed z-index for header to higher

package.json
* Webpack 4.29.0 appears to have introduced a breaking change from the 5.0 branch.
* Lock down versions to the ones used during development of #1390 
* Fixes #1427 
- [Stack Overflow Question](https://stackoverflow.com/questions/54316059/bigcommerce-stencil-start-uncaught-error-module-parse-failed/54316525#54316525)
- [Github Issue](https://github.com/bigcommerce/cornerstone/issues/1427)
Loads fine in CLI now:
=> STRF-5934: Lock down webpack version

CHANGELOG.md
Changelog additions for Cornerstone 3.1.1.
- Downgrade Webpack to last known good version during development. [#1428](https://github.com/bigcommerce/cornerstone/pull/1428)
=> Changelog for Cornerstone 3.1.1.

assets/scss/components/vendor/slick/_slick.scss
If a product has more then 5 images. It will create slider but there is an issue about align of the slider arrows. 
**Before:** 
**After:**
=> To set proper align Product thumbnail image slider arrows

CHANGELOG.md, templates/components/cart/content.html, templates/components/cart/preview.html, templates/pages/account/add-return.html
Certain product options allow for user-submitted input, which in the case of JS can be executed on the Cart page. This value is now escaped properly on the Cart page. This is also addressed on the Returns page.
This also cleans up code related to Configurable Fields, which were removed in https://github.com/bigcommerce/cornerstone/pull/1407.
This does not address Custom Fields, which are entirely determined by the merchant.
- [STRF-5948](https://jira.bigcommerce.com/browse/STRF-5948)
=> fix(storefront): STRF-5948 Cleanup and XSS fix on Cart page.

templates/components/common/forms/date.html
Corrected the ID's to match the form fields with the labels for month and day. 
More info within the issue
- [Issue #1432 ](https://github.com/bigcommerce/cornerstone/issues/1432)
=> Correcting ID's in date.html form-fields

CHANGELOG.md, templates/components/products/new.html, templates/components/products/product-view.html, templates/components/products/quick-view.html, templates/components/products/tabs.html, templates/pages/amp/category.html, templates/pages/amp/product.html, templates/pages/brand.html, templates/pages/category.html, templates/pages/product.html, templates/pages/search.html
These changes correct the scope of the settings object in several files.
In [this commit](https://github.com/bigcommerce/cornerstone/commit/55fc73eeb1edc6e140005ca811f090f06ab35435), the store settings object was improperly scoped using '../' unnecessarily in some instances. This causes defects in the quick view modal and poses risks for future development. Anything that can be toggled in the store settings does not appear in the quick view modal. This includes the product rating, social share links, and add to wish list button.
To replicate, go to the [Cornerstone demo theme](https://cornerstone-light-demo.mybigcommerce.com/), and quick view any product. 
N/A
=> Resolve settings scope passed to components

CHANGELOG.md
Changelog additions and edits for Cornerstone 3.2.1.
- Product description in Compare no longer shows escaped HTML. #1439 
- Removed newline in 3.2.0 changes.
=> Changelog for Cornerstone 3.2.1.

CHANGELOG.md, templates/components/products/card.html
Fixes an annoying modal scrollback issues
https://jira.bigcommerce.com/browse/CP-4140
=> fix(cp): CP-4140 fixes modal scroll issue from quickview button

CHANGELOG.md
More Changelog changes for Cornerstone 3.2.1.
- Removed href="#" from quick view list item. #1446 
On top of #1443
=> More Changelog changes for Cornerstone 3.2.1.

CHANGELOG.md, assets/scss/components/foundation/modal/_modal.scss
This change brings the add to cart modal to the proper location on mobile.
On mobile screens, the add to cart modal appears off-screen. This issue stems from an [edit made to the modal.scss file](https://github.com/bigcommerce/cornerstone/pull/1390/commits/5347914d46c24b1732a8e44e9270ed94bc295cf2) where the left, top, and transform CSS properties were removed.
To replicate, go to any product on the Cornerstone demo theme, for example, the [Able Brewing System](https://cornerstone-light-demo.mybigcommerce.com/all/able-brewing-system/), resize your window to a width under 551px, and add the product to your cart.
The edit made to the modal.scss file appears to be a fix to center the small modal. This issue can be resolved by setting margin to 0, while keeping the left, top, and transform …
=> Resolve add to cart modal mobile isssue

CHANGELOG.md, stencil.conf.js, webpack.common.js, webpack.dev.js
When Webpack compilation fails, `stencil bundle` blindly ignores it.
As a result, the generated theme ZIP file does not contain the `assets/dist` folder (just like in issue https://github.com/bigcommerce/stencil-cli/issues/379)
Step-by-step from fresh Cornerstone, below.
In this example, we will simply add a line of JavaScript code which Babel will fail to understand:
```sh
git clone https://github.com/bigcommerce/cornerstone.git
cd cornerstone
npm ci
stencil bundle
echo 'console.log(<h1>Hi</h1>); // eslint-disable-line' >> assets/js/app.js
stencil bundle
```
In our real-world scenario, the **Webpack build failed** for other reasons, and we didn't need to shut up ESLint as in this example (the code passed in ESLint checks). Our scenario is more complex to reproduce. It requires other …
=> Fail stencil bundle on Webpack compile errors

config.json, schema.json, templates/components/common/breadcrumbs.html, templates/pages/blog.html, templates/pages/category.html, templates/pages/contact-us.html, templates/pages/page.html
Add option to hide breadcrumbs, page heading, category heading, contact page heading and blog page heading. 
[MERC-4566](https://jira.bigcommerce.com/browse/MERC-4566)
**Turning off breadcrumbs**
**Turn off page heading**
**Turn off category page heading**
**Turn off contact page heading**
**Turn off blog page heading**
=> MERC-4566 Add option to hide breadcrumbs and page title

CHANGELOG.md, templates/pages/auth/login.html, templates/pages/auth/new-password.html
Disables implicit autocomplete on password entry forms for Sign In and when changing passwords when signed in as a customer.
When the autocomplete attribute is not on the form element, autocomplete is _implicitly_ enabled: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
The impetus for this change is increased security for PCI compliance. See https://portswigger.net/kb/issues/00500800_password-field-with-autocomplete-enabled.
=> Explicitly disable autocomplete in password entry input fields.

CHANGELOG.md, assets/js/test-unit/theme/cart.spec.js, assets/js/theme/cart.js
Update product qty in cart page by typing the new qty (not using the arrow), didn't work and the cart was keeping the old qty after refreshing. This pr fix this functionality.
=> fixed update product qty by typing the new qty in the cart page

CHANGELOG.md, templates/components/faceted-search/facets/multi.html
This pull request uses the handlebars helper {{ sanitize }} to remove HTML tags from facets' titles on category pages. 
- [Issue](https://github.com/bigcommerce/cornerstone/issues/1416)
=> Sanitize faceted search item's title

assets/js/theme/global/mobile-menu-toggle.js
Change the event handler to correctly call `this.onSubMenuClick`. Without this fix, mobile navigation is not showing/hiding siblings correctly.
=> Fix submenu click on mobile navigation

assets/js/test-unit/theme/common/faceted-search.spec.js, assets/js/test-unit/theme/common/url-utils.spec.js, assets/js/theme/common/faceted-search.js, assets/js/theme/common/url-utils.js
Product filtering Price Filter clears other filters below it (or after in the query URL).
https://jira.bigcommerce.com/browse/ES-156
`Note:` Please verify the URL params with selected Facets in each below image.
Image 1: **Resultant Products with all 3 brands and price range with 10-55 and `Field01` with 3 colors**.
Image 2: **Resultant Products with 3 brands and price range with 20-50 and `Field01` with 3 colors.**
Image 3: Now only with 2 brands and price range with 20-40 and `Field01` with 3 colors. But, due to the price range filter only 2 colors products are displayed.
@bigcommerce/cp-dt
=> fix(CP): ES-156 Fixed the filtering issues with price range filter selection

CHANGELOG.md
- Added entries for upcoming release.
- Moved changelog entry for #1426 , which was inserted in during merge. That PR was opened after 3.0.0.
- Cleaned up some spacing so that links render properly on entries for #1341 and #1347.
=> Changelog updates for Cornerstone 3.4.1, and some minor fixes.

CHANGELOG.md, templates/components/amp/products/ratings.html, templates/components/common/quick-search.html, templates/components/common/search-box.html, templates/components/products/add-to-cart.html, templates/components/products/description-tabs.html, templates/components/products/description.html, templates/components/products/product-view.html, templates/components/products/ratings.html, templates/components/products/reviews.html, templates/components/search/advanced-search.html, templates/layout/amp.html, templates/layout/base.html, templates/pages/account/orders/all.html, templates/pages/amp/category.html, templates/pages/brand.html, templates/pages/cart.html, templates/pages/category.html, templates/pages/home.html, templates/pages/search.html
Related:
https://github.com/bigcommerce/cornerstone/pull/1193
https://github.com/bigcommerce/cornerstone/pull/1478
This removes legacy "snippet" locations which were intended for CMS functionality which was never built. These have been deprecated in favor of [Widgets](https://developer.bigcommerce.com/api-docs/storefront/widgets/widgets-overview).
This should cause no functional change, and is purely for "cleanup" purposes so that developers are not confused by the presence of these.
ping @bigcommerce/storefront-team @bigcommerce/merc-team
=> MERC-3425 - Remove all legacy "snippet" locations

CHANGELOG.md, templates/components/common/cart-preview.html
Dropdown cart does not show discounts.
#1467 
**BEFORE**
**AFTER**
=> Fix dropdown cart not showing discounts

CHANGELOG.md, assets/scss/components/stencil/heroCarousel/_heroCarousel.scss
Hero carousel text is displaying with an underline on small screen sizes.
#1303 
**BEFORE**
**AFTER**
=> Fix mobile banner text displaying with underline on mobile

CHANGELOG.md, assets/js/theme/product.js, templates/components/products/bulk-discount-rates.html
Currently, the Bulk Pricing link doesn't work from a Quick View modal. Clicking on the "Buy in bulk and save" link effectively closes the Quick View modal.
This PR replicates the behavior for Write a Review from Quick View. Now, clicking on the "Buy in bulk and save" link from Quick View will open the Product page and immediately open the Bulk Pricing modal.
Before:
After:
=> Fix to open Bulk Pricing modal from Quick View.

assets/js/theme/common/payment-method.js, templates/pages/account/add-payment-method.html, templates/pages/account/edit-payment-method.html
Includes `currency_code` field within the Account > Payment Methods section.
We are wanting to send the shopper selected currency code whenever a shopper adds/edits a new payment method.
- [PAYMENTS-4228](https://jira.bigcommerce.com/browse/PAYMENTS-4228)
=> feat(payments): PAYMENTS-4228 include currency_code field in Account > Payment Methods page

schema.json
The `Star review icon (full)` and `Star review icon (empty)` settings were swapped (such that `Star review icon (full)` was associated with `icon-ratingEmpty`). This corrects that issue. 
[MERC-4895](https://jira.bigcommerce.com/browse/MERC-4895)
=> MERC-4895: Fix swapping of Star review icon (full/empty) settings

CHANGELOG.md, assets/js/theme/product/reviews.js
Previously when config.json had show_product_reviews_tab as true the reviews link when clicked would do nothing.  This fix should make it so that instead the reviews tab is opened and window is directed to it.
https://jira.bigcommerce.com/browse/STRF-5521
=> STRF-5521 PDP Product Reviews Link Not Clickable

CHANGELOG.md, assets/js/theme/common/select-option-plugin.js, package-lock.json, package.json
Update jQuery version to latest.
- [STRF-6720](https://jira.bigcommerce.com/browse/STRF-6720)
=> chore(storefront): STRF-6720 Update jQuery to 3.4.1

CHANGELOG.md, templates/layout/base.html
The <head> of the storefront contains a bunch of empty stuff when you llook at it in prod - this removes some of that which makes it a little easier to develop on Cornerstone.
=> Clean up whitespace in layout/base.html

templates/components/common/header.html, templates/pages/amp/category.html, templates/pages/brand.html, templates/pages/brands.html, templates/pages/category.html, templates/pages/home.html, templates/pages/product.html, templates/pages/search.html
Enable the following regions in cornerstone for enabling adding new content via widgets onto these pages:
(1) Homepage
(2) Brand
(3) Brands
(4) Category
(5) Product Page
(6) Search Page
[MERC-4842](https://jira.bigcommerce.com/browse/MERC-4842)
=> MERC-4842 Add additional regions

CHANGELOG.md, templates/components/cart/content.html, templates/pages/cart.html
This should avoid double inclusion of some of the analytics code. (eg. facebook pixel)
https://jira.bigcommerce.com/browse/CHECKOUT-4118
Before:
After:
@bigcommerce/storefront-team @lord2800 @megdesko
=> CHECKOUT-4118 Remove remote_api_scripts from the templates

CHANGELOG.md, templates/components/account/returns-list.html
This should be else if as this is basically a switch statement.
=> chore(storefront): STRF-6780 clean up returns-list.html conditional logic

package-lock.json
used 
```
>  C02X424CJG5M:cornerstone sandeep.ganapatiraju$ npm -v
> 6.4.1
> C02X424CJG5M:cornerstone sandeep.ganapatiraju$ node -v
> v8.16.0
```
```
and generated this package lock updated by running npm install on current master
=> more package lock update after npm install

CHANGELOG.md, package-lock.json, package.json
Update babel/polyfill to latest, as it's 6 months out of date.
Next, we'll need to replace it: https://babeljs.io/docs/en/babel-polyfill
=> Update babel/polyfill to 7.4.4

CHANGELOG.md, templates/components/products/options/input-text.html, templates/components/products/options/textarea.html
Including the maxlength attribute on text input options and multi line text options if a max length value has been defined by the merchant.
https://jira.bigcommerce.com/browse/STRF-6042
=> STRF-6042 add maxlength to text options

CHANGELOG.md, lang/en.json, templates/pages/account/return-saved.html
Previously return instructions did not appear after submitting a return request and one would need to edit the template file in return-saved.html to display return instructions even if they had configured returns instructions in the control panel.  This pull request is to fix that issue.
- [Link 1](https://jira.bigcommerce.com/browse/STRF-3591)
=> STRF-3591 add return instructions in return-saved.html

CHANGELOG.md, templates/components/common/share.html
=> Fix broken conditional statement in share.html

CHANGELOG.md, templates/components/common/share.html
Display like button when it is enabled through control panel.  This pull request is to fix a bug where the facebook like button would not display when enabled.
- [Link 1](https://jira.bigcommerce.com/browse/STRF-3382)
=> STRF-3382 display facebook like button when enabled

CHANGELOG.md, assets/js/theme/account.js
Fix incorrect DOM selectors causing the payment method form on the account page from working properly in Safari.
- [PAYMENTS-4520](https://jira.bigcommerce.com/browse/PAYMENTS-4520)
@bigcommerce/payments @bigcommerce/storefront-team
=> PAYMENTS-4520 Fix incorrect DOM selectors causing the payment method form on the account page from working properly in Safari

CHANGELOG.md, templates/layout/amp.html, templates/layout/base.html
This variable does not return anything, so it should not be here.
There is no head.rsslinks in the context.
- [STRF-7084](https://jira.bigcommerce.com/browse/STRF-7084)
=> chore(storefront): STRF-7084 remove RSS links from head

CHANGELOG.md, templates/components/category/shop-by-price.html
It is possible for a category to have an insufficient number of items to generate price ranges. If the theme is customized to display the "Shop by Price" sidebar and the category does not generate a price range, only the heading is displayed. This change ensures there are price ranges available before displaying the heading and price ranges. 
N/A
Example of heading displayed with no price ranges.
=> Prevent heading from displaying when no price ranges are available

CHANGELOG.md, templates/components/products/card.html
Removing unneeded `demo` conditional logic which is no longer used. Fixes a bug which was preventing product card images from being clicked.
=> Fix bug where image is not clickable in product card

CHANGELOG.md, assets/scss/components/vendor/slick/_slick.scss, templates/components/products/carousel.html
Pulling in @mattcoy-arcticleaf 's product carousel fix from https://github.com/bigcommerce/cornerstone/pull/1458 together with a slick carousel iOS/Safari fix from https://github.com/kenwheeler/slick/issues/2834#issuecomment-389590661.
Fixes styling issues in several spots where slick carousel is used.
See original PR.
=> mattcoy-arcticleaf's patch/product carousel responsiveness

CHANGELOG.md, templates/components/cart/content.html
Deleted whitespaces inside if statements (content.html). This was reported in https://github.com/bigcommerce/cornerstone/issues/1528
=> deleted white spaces in if statements (content.html)

assets/js/theme/global.js, assets/js/theme/global/object-fit-polyfill.js, assets/scss/components/citadel/cards/_cards.scss, assets/scss/components/stencil/productView/_productView.scss, package-lock.json, package.json
Cornerstone 4.0 introduced a bug in which images which are particularly tall (portrait) are stretched on PDPs and PLPs:
This fixes that using `object-fit: contain`.
=> Fix tall images on PDPs and PLPs

CHANGELOG.md, assets/js/theme/global/mobile-menu-toggle.js
Currently, the aria-hidden attribute is being added to the main menu (id="menu") with a value of true. This breaks screen-reader capabilities as it hides the entire menu from the accessibility tree.
Additionally, this attribute is unneeded and redundant in this instance because the menu is being hidden with CSS (display: none). This also goes against MDN best practices for the attribute (see link below). Having the menu hidden with CSS is sufficient for hiding it from the accessibility tree.
This Pull Request removes the code that toggles the aria-hidden attribute on the menu (and sets it to true on page load).
- [Open Issue #1558 ](https://github.com/bigcommerce/cornerstone/issues/1558)
- [MDN Best Practices for Aria-hidden](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ …
=> Remove ‘aria-hidden’ attribute from main menu

CHANGELOG.md, assets/js/theme/brand.js, assets/js/theme/category.js, assets/js/theme/global/compare-products.js, assets/js/theme/search.js
This pull request implements a bug fix.
It requires "**_Product Filtering_**" to be **turned on** for the store.
When we select a faceted search filter, Cornerstone updates the page without reloading. It does an AJAX request and updates the URL using the History API. Some sections of contents are updated, with the HTML contents returned in the AJAX call response.
The problem is when we do this faceted search filter selection when we already have a few products selected for comparison, and the "Compare" link at the top header is appearing and active, with the number of selected products.
After the faceted search dynamic update described above is performed, the "Compare" link becomes out of sync with the updated contents. The "Compare" link keeps showing the same product count, and has the …
=> Reset compare products counter after faceted search updates page content

CHANGELOG.md, templates/components/products/price-range.html, templates/components/products/price.html, templates/components/products/product-view.html
It was found that we are not properly marking up some fields that are available on a product page for Google Structured Data.  This PR fixes some of our markup and adds some additional markup.
The current errors seen on most product pages (which have reviews added to the product) is:
Also found a bug where if a price range is being displayed then the "offer availability" property does not display correctly:
JIRA ticket:
https://jira.bigcommerce.com/browse/STRF-6450
Google Structured Data (Product) information:
https://developers.google.com/search/docs/data-types/product
Screenshot having applied my updated cornerstone bundle to my production store that I used to generate the error images above.  The product is displaying a price range:
Note only 1 warnings is now seen. This remaining …
=> STRF-6450 - Updates to Product Page Template for Google Structured Data

assets/scss/components/stencil/cart/_cart.scss, assets/scss/components/stencil/productView/_productView.scss, schema.json, templates/components/products/product-view.html
Fixes issue where thumbnails could not resize
[MERC-3688](https://jira.bigcommerce.com/browse/MERC-3688)
=> MERC-3688: Fix thumbnail image sizes

CHANGELOG.md, assets/js/theme/product/reviews.js
There was an issue that was affecting Klaviyo in regards to product reviews as they were loading a third party script and the validator was validating against the third party script's email input field instead of the email input field that belonged to the writeReview-form css class.  This pr is to fix that issue so that a third party script can be on the page and a user can still post a review.
- [Link 1](https://jira.bigcommerce.com/browse/STRF-7487)
=> STRF-7487 fix registerValidation function to always validate on writeReview-form email field

CHANGELOG.md, assets/scss/components/stencil/cart/_cart.scss
When viewing the cart page on mobile or tablet, the cart item headings are not respecting the body text configuration value defined by the user.
**Before**
**After**
=> MERC-5570: Body text color doesn't effect some cart item headings for mobile and tablet

.travis.yml, package-lock.json, package.json
Updating the stencil-cli dependency version to latest in order to support node 10.
=> chore: bumping stencil-cli forward for node 10 support

CHANGELOG.md, assets/scss/components/stencil/writeReview/_writeReview.scss
Update the review modal image styling to make sure the image shows full-width.
- [STRF-7334](https://jira.bigcommerce.com/browse/STRF-7334)
Before:
After:
=> STRF-7334 - Fix image sizing on review modal

README.md
There was a typo of  `page` instead of `pages` - I changed it to `pages`
=> fix typo using `page` instead of `pages`

CHANGELOG.md, package-lock.json, package.json, webpack.common.js
Fixing this error on `stencil start`:
```
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:
npm install --save core-js@2    npm install --save core-js@3
yarn add core-js@2              yarn add core-js@3
```
=> Fix corejs warning

CHANGELOG.md, assets/js/theme/global/cart-preview.js, package-lock.json, package.json
Fix the cart quantity calculation for bundled products by pulling in stencil-utils 5.0.1.
This will stop bundled products from being added to the quantity-in-cart for the cart preview, which will make it match the quantity reported on the cart page.
Also: small refactor to explicitly request cart by ID.
=> Fix cart quantity for bundled items

package-lock.json, package.json, webpack.common.js
Reasons to upgrade to core-js version 3 are many, mainly the improved Babel integration.
In our case, we had a theme failing on Internet Explorer 11, and it boiled down to the fact that core-js version 2 does not provide polyfill for `NodeList.forEach` method. Version 3 of core-js provides this polyfill.
If only Cornerstone was using core-js version 3 out of the box, we would not have ran into that issue.
- [Advantages of core-js version 3](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#what-changed-in-core-js3)
:arrow_down: Comparison from core-js's README for v2 and v3:
- https://github.com/zloirock/core-js/tree/v2#iterable-dom-collections
- https://github.com/zloirock/core-js/tree/v3#iterable-dom-collections
<hr> …
=> Upgrade core-js to version 3

assets/js/test-unit/theme/global/modal.spec.js
As written at [`assets/js/theme/global/jquery-migrate.js`](https://github.com/bigcommerce/cornerstone/blob/4.3.0/assets/js/theme/global/jquery-migrate.js):
```js
// Needed because we use Foundation 5.5, which expects jQuery 2.x. However,
// rather than bringing in all of jquery-migrate, we're cherry picking individual
// fixes needed for Foundation.
```
This is also true for the **testing environment**. Foundation 5.5 still expects jQuery 2.x, and the need for jquery-migrate is the same.
However, Foundation is used at [`assets/js/test-unit/theme/global/modal.spec.js`](https://github.com/bigcommerce/cornerstone/blob/4.3.0/assets/js/test-unit/theme/global/modal.spec.js), but jquery-migrate is not loaded.
The purpose of this PR is to fix this situation. It includes the missing jquery-migrate …
=> Add jquery-migrate to Modal test

templates/components/products/price.html
Fixes `itemprop` availability meta tag for price including tax case in price.html component. This is to address the `availability` not being set in a Google Structured Data test on PDP only when price is including tax.
This was missed in updates on STRF-6450.
https://jira.bigcommerce.com/browse/STRF-7604
**master** - This is the google structured data test with store set to display prices including taxes on PDP:
**On my branch** - This is the same PDP test for prices including tax:
=> STRF-7604 - Fix remaining itemprop availability tag for pricing

CHANGELOG.md, assets/js/theme/common/faceted-search.js
Tested on store: https://williamkwon1576004500-testly-the-third.my-integration.zone/
Previously, the browser back button would not navigate pagination properly when faceted search was enabled but now it does.
- [Link 1](https://jira.bigcommerce.com/browse/STRF-7232)
**Screenshots (if appropriate)**
https://imgur.com/a/MtmIeIR
=> Fix to make browser back button navigate pagination properly when faceted search is enabled

CHANGELOG.md, config.json, schema.json
Cornerstone bold uses #ffffff(white) for the alert box text color, this makes it very hard to see. This ticket changes the default Cornerstone bold alert text color to #333333 and makes the text color editable from the theme-editor
- [STRF-4418](https://jira.bigcommerce.com/browse/STRF-4418)
Before:
After:
=> feat(storefront): STRF-4418 allow alert text color editing from theme editor and update default alert text color for Bold variation

CHANGELOG.md, assets/js/theme/account.js, assets/js/theme/cart.js, assets/js/theme/cart/shipping-estimator.js, assets/js/theme/global/sweet-alert.js, package-lock.json, package.json
Bump SweetAlert2 to the latest version.
- https://github.com/sweetalert2/sweetalert2/releases/tag/v7.0.0
- https://github.com/sweetalert2/sweetalert2/releases/tag/v8.0.0
- https://github.com/sweetalert2/sweetalert2/releases/tag/v9.0.0
=> SweetAlert2 v6.11.5 -> 9.5.4

assets/js/theme/wishlist.js
When a user is logged out and we try to create a wishlist from a PDP page the server attempts to redirect due to the shopper being logged out. Whilst this will work in blueprint, it breaks the user flow on cornerstone, which ends up with the shopper eventually logging in and creating a wishlist without the selected product in it. After discussion with product we have decided to remove the modal for creating a new wishlist 
https://jira.bigcommerce.com/browse/CHECKOUT-4233
@bigcommerce/storefront-team @davidchin
=> fix(checkout): CHECKOUT-4233 Cannot add wishlist with item when logged out

CHANGELOG.md, assets/scss/components/vendor/sweetalert2/_sweetalert2.scss, templates/components/common/alert-modal.html
Resolve visual regression introduced in  #1617.
**BEFORE**
**AFTER**
=> Resolve visual regression in error modal icon animation

package-lock.json, templates/components/faceted-search/show-more-facets.html
Product filters that have more than 10 values and are configured within the control panel to not display the product count on the storefront still shows product counts in the "View More" facets modal.
- https://jira.bigcommerce.com/browse/ES-98
**`Before fix:`**
`Store (local)`: https://my-dev-store-740294812.store.bcdev/
Product count is being displayed on the "more" modal when `Display Product Count` is not selected on Product Filtering.
**`After fix:`**
`Store (integration)`: https://sumayyahasgar1579809024-testington.my-integration.zone/
Product count no longer being displayed  on the "more" modal when `Display Product Count` is not selected on Product Filtering
1. Go to https://sumayyahasgar1579809024-testington.my-integration.zone/ …
=> feat(search): ES-98 Product filters configured to not display product count show a count when you use the "More" modal

CHANGELOG.md, lang/en.json, templates/components/blog/post.html
Make "read more" link for blog posts translatable by adding string to english language file.
Reference: #1623
=> Add translation key for "read more" blog post link

CHANGELOG.md, assets/js/theme/common/product-details.js
When you manually input a quantity and press enter, it triggers a decrease to the quantity. This PR addresses this problem.
#1616
=> Prevent triggering quantity change when pressing enter

templates/components/faceted-search/facets/range.html
Price filter always displays in expanded mode ignoring CP Setting. With this fix, Price filter honors the CP settings.
- [https://jira.bigcommerce.com/browse/ES-721](ES-721)
Case 1: Expanded
Case 2:  Collapsed
=> feat(search): ES-721 fixed the issue for price filter collapse CP settings

templates/components/faceted-search/facets/hierarchy-children.html, templates/components/faceted-search/facets/hierarchy.html, templates/components/faceted-search/facets/multi.html, templates/components/faceted-search/selected-facets.html
As part of fixing the encoding issues for ES-97, we found that html characters are being displayed in stencil theme. This fix will address it.
- [https://jira.bigcommerce.com/browse/ES-97](ES-97)
Broken "RefineBy" facet names
---------------------------------
Fixed "RefineBy" facet names
-------------------------------
=> feat(search): ES-97 fixed the html special chars issue in facet names

lang/en.json, templates/components/common/cookie.html, templates/layout/base.html
Removing the "EU Cookie Notification" feature which would show a notice to EU visitors to the site that cookies are used as part of the experience.
This is being removed as BigCommerce has adapted to changing interpretations of GDPR, and have determined that this feature is no longer useful to merchants who are seeking to be compliant with data privacy regulations.
Merchants are recommended to consider our new [Shopper Consent Tracking feature
](https://support.bigcommerce.com/s/article/Store-Settings#security) and consider our other guidance related to local laws:
https://support.bigcommerce.com/s/article/General-Data-Protection-Regulation#learning
https://support.bigcommerce.com/s/article/Implementing-CCPA-with-BigCommerce
As always, merchants are advised to seek their own counsel …
=> Remove "cookie notification" feature as it is no longer useful

assets/js/theme/search.js, templates/components/search/content-count.html, templates/components/search/content-listing.html, templates/components/search/product-count.html, templates/pages/search.html
This PR contains a number of bug fixes related to the Search Results page navigation.
If fixes #1170 and #1312 by separating the current navigation **page** between "Products" and "News & Information" tabs. It becomes possible, for example, to be at "page 3" in one tab, and at "page 1" in the other tab.
It also improves the fix to #1442, provided by commit 5322976e. Now, the back button also works when there is a switch between "Products" and "News & Information" tabs, when navigating backwards.
And it also fixes the dynamic loading of search results for the "News & Information" tab. The AJAX load/update only worked for the "Products" tab. Now, it works also for the "News & Information" tab.
It also fixes the annoying "re-load" of the search results immediately after the first load of the …
=> Search Results: fix navigation issues

templates/components/common/forms/text.html
Top 20 bug reports that while user can set the max length for the account sign up fields it is not respected in the storefront
https://jira.bigcommerce.com/browse/STRF-5678
To test:
1. Navigate to Control Panel -> Advanced Settings -> Account Sign up 
2. Change max length on any text field (for example Address 1 field)
3. Navigate to storefront and click on Register
4. Type in the field with defined max length and observe how it is not allowing you enter more characters than specified in max length
ping @bigcommerce/storefront-team @bigcommerce/artemis-dt
=> fix(storefront): STRF-5678 fixed the check for max length in create account fields

templates/components/faceted-search/facets/hierarchy.html, templates/components/faceted-search/facets/multi.html, templates/components/faceted-search/show-more-facets.html
Faceted search filters that include ampersand (&) breaks 'Show More' links. 
With this fix, now we can have Facets with `&` symbol and `Show More` link works fine.
- [ES-466](https://jira.bigcommerce.com/browse/ES-466)
1. Login to CP
2. Navigate to Products
3. Edit few Products and add a `Custom Field` (with same name like _ Custom & Color _) and with different values for each product and save the Products.
4.  Navigate to Products->Product Filtering
5. Enable the newly created facet.
6. Click the settings of this facet filter and change the value for `show` to 5 items and save
6. Go to SF and click on the `Show More` link for this new filter and the popup window shows all the filter values.
1. List of all Facets:
2. Facet with `&` in the name & value
3. `Show More`  link displays the …
=> feat(search): ES-466 Facets with & symbol works now

templates/components/cart/content.html, templates/components/cart/preview.html, templates/components/products/product-view.html
Due to a recent change input fields on products are sanitised. This means that in cornerstone the expected values weren't rendered as expected
https://jira.bigcommerce.com/browse/CHECKOUT-4828
@bigcommerce/checkout @bigcommerce/storefront-team @abhijethbc
=> fix(customers): CHECKOUT-4828 Special characters to render properly on the cart modal pop up

assets/js/theme/global/cart-preview.js
If we get a 404 for the cart, set the quantity to 0 for the cart preview.
Fixes a bug where the quantity will not update back to 0 after a successful checkout.
- [STRF-8295](https://jira.bigcommerce.com/browse/STRF-8295)
=> Reset cart quantity to 0 if we get a 404 for the cart

templates/components/search/heading.html, templates/components/search/quick-results.html, templates/pages/search.html
Special Characters are displaying as Unicode when using the Storefront Search as shown in the below ticket. 
This is because search term was not escaped before displaying. With this fix, search query is properly escaped/sanitized before displaying in the SF. 
- [STRF-8350](https://jira.bigcommerce.com/browse/STRF-8350)
1. Login to CP
2. Navigate to Storefront
3. Upload the theme file (**Cornerstone-4.5.0_Fix_8350**) with the fix attached to the above ticket (**STRF-8350**) and apply it
4. Search in the Storefront with a term which has special character in it like ```test's```  or ```test"s```
5. Search results page will not display any unicode/un-escaped characters
1. searched with single quote (')
2. searched with double quote (")
3. quick search modal also showing escaped search term …
=> feat(search): STRF-8350 Fixed the special characters display issue in the search results page

templates/components/products/reviews.html
Special characters are not rendered for product review titles and text on storefront
Special characters in product review titles and texts are displaying html entities. The entities that are occurring are generally for single quotes and ampersand.
https://jira.bigcommerce.com/browse/CATALOG-5557
=> fix(catalog): CATALOG-5557 Special characters are not rendered for product review

package-lock.json, templates/components/common/forms/checkbox.html, templates/components/common/forms/date.html, templates/components/common/forms/multiline.html, templates/components/common/forms/number.html, templates/components/common/forms/password.html, templates/components/common/forms/radio.html, templates/components/common/forms/select.html, templates/components/common/forms/selectortext.html, templates/components/common/forms/text.html
Reverts bigcommerce/cornerstone#1655
Going to revert this for now since it is causing issues with the zipcode field. This will require some backend changes to support this change. 
We will come back to this change once the backend changes are in place.
=> Revert "Account form classes"

templates/components/common/social-links.html
This PR adds an rel=“noopener” attribute to the social media links to help avoid any performance or security issues when using the target=“_blank” attribute. See https://web.dev/external-anchors-use-rel-noopener/
=> Add rel="noopener" to social links

package-lock.json, package.json
Latest lazysizes updates dependencies and resolves a security issue.
https://snyk.io/vuln/SNYK-JS-LAZYSIZES-567144
=> Bump lazysizes to 5.2.1

templates/components/faceted-search/facets/hierarchy.html, templates/components/faceted-search/facets/multi.html
Product filters are not expanded or collapsed in category listing, brand listing & search results page when product filters for SF are turned on. 
Currently, we are not able to expand/collapse the filters since, `replace` helper returns empty string when the input does not have the special character `&` in it. Thus collapsible divs are having same id and thus its broken this feature in the product filters. 
In the below image, both the `data-collapsible` in the html source is same for both `Catrgory` & `Brand` filters.
- [https://jira.bigcommerce.com/browse/ES-1192](ES-1192)
Steps:
1. Login to CP
2. Use the theme file (`Cornerstone-4.6.1_fix_ES-1192.zip`) uploaded in the above issue
3. Upload & Publish the theme by navigating to Storefront
4. Navigate to Products, choose any product 
5. …
=> feat(search): ES-1192 fixed the replace helper to expand and collapse the product filters

assets/scss/components/stencil/cart/_cart.scss, templates/components/common/cart-preview.html
Adding additionalCheckoutButtons on the cart-preview and respective scss
In order to displays wallet buttons on the drop-down section from the cart icon on the storefront
[**INT-2593**](https://jira.bigcommerce.com/browse/INT-2593)
[**INT-2370(research)**](https://jira.bigcommerce.com/browse/INT-2370)
[**BCApp PR**](https://github.com/bigcommerce/bigcommerce/pull/35536) needs to be merge first
=> feat(payments): INT-2593 Display wallet on drop-down section from cart icon

templates/components/faceted-search/facets/hierarchy.html, templates/components/faceted-search/facets/multi.html
Custom filter without '&' is not collapsable
Since custom filter without `&` and if it has `empty space` between the words (`Ex: Custom Size`), the `data-collapsible` element is broken in the html source. With this fix, 
- [https://jira.bigcommerce.com/browse/ES-1322](ES-1322)
1. All the filters are collapsed
2. Standard filters are expanded 
3. Both custom filters are expanded
4. One custom collapsed (custom filter without `&` in it) and other one is expanded (custom filter with `&` in it)
5. One custom collapsed (custom filter with`&` in it) and other one is expanded (custom filter without `&` in it)
=> fix(search): ES-1322 fixed the collapse and expand issue for custom filter without no special characters

assets/js/polyfills.js, assets/js/theme/global/sweet-alert.js, package-lock.json, package.json, templates/components/common/polyfill-script.html, templates/layout/base.html, webpack.common.js
I'm trying to improve performance by reducing the size of the main JS bundle when loaded on modern browsers.
I've taken [this approach](https://philipwalton.com/articles/loading-polyfills-only-when-needed/), meaning I do some basic feature detection to indicate if the shopper is using a modern browser, and if they aren't, I polyfill the `core-js` library and any other polyfills. This saves a lot of download + parsing of extraneous JS for most users. 
I've polyfilled liberally rather than trying to isolate the extra polyfills necessary based on Cornerstone's usage of ES6 features - this is because I couldn't find a great way to automate this, and it would make the theme harder to maintain if not automated.
~I also bundled in a jQuery version bump to [address a …
=> [PERFORMANCE] Optimize polyfills

README.md
ping @bc-themes @bigcommerce/storefront-team
=> Add documentation about polyfilling strategy to readme

templates/components/products/videos.html
This change adds to product page YouTube videos a YouTube URL parameter that suppresses 3rd party "Related Videos" at the end of each video's run. During the June Town Hall Q&A, this was named by one user as a problem that forced them to move their videos to Vimeo. With this URL parameter, only same-channel videos will appear as related videos.
YouTube's [IFrame Player API](https://developers.google.com/youtube/player_parameters) explains how this URL parameter works: "...if the rel parameter is set to 0, related videos will come from the same channel as the video that was just played."
For an Ecommerce site, this is an improvement and should reduce the possibility to sending traffic to someone else's store through YouTube 3rd party videos. Since video.html is used by both AMP and non-AMP …
=> Suppress 3rd party Related Videos on YouTube videos

assets/scss/layouts/products/_productList.scss, assets/scss/layouts/products/_productSaleBadges.scss, templates/components/products/list-item.html
@bc-themes 
Fixed Cornerstone not showing Sale badge in list view. 
In your page builder you have theme styles. In Global section you need to scroll opened modal window to Products paragraph. Here you can select display style list or grid. When grid is selected Sale Badges are seen on products that have a discount. But if you select list, product items will not have Sale Badges.
For now it is fixed - the user can see Sale Badges on items this discount in list view and in a grid view.
I added code that checks is this item on sale and need badge in html file of product list item. Also I updated styles for badges displaing in product list item
https://jira.bigcommerce.com/browse/STRF-5072
=> fix(Storefront): STRF-5072 Cornerstone not showing Sale badge 

assets/scss/layouts/footer/_footer.scss
@junedkazi 
Horizontal scrolling on some resolutions, for example, on iPad.
When social links in the footer turned on and they aligned to the right, unnecessary horizontal scroll appears. It was so because of position styles of social links block (was shifted to the right) and his width.  
- ...
=> fix(Storefront): BCTHEME-3 Horizontal scrolling on some resolutions

assets/scss/layouts/products/_productList.scss
Misalignment of Product Listings on Category pages when using the list Display Style.
When your products renders in list mode and you have product without description, this products buttons are shifted to the left on desktop and have misaligning on mobile. It was fixed with setting 100% with to the list item 
- [jira ticket](https://jira.bigcommerce.com/browse/BCTHEME-28)
desktop bug (second product)
desktop fix  (second product)
mobile bug (second product)
mobile fix  (second product)
=> fix(Storefrront): BCTHEME-28 Misalignment of Product Listings on Category pages when using the list Display Style

assets/scss/layouts/products/_productView.scss
Cornerstone: Enabling Facebook Likes causes iframe overlap in WYSIWYG.
Facebook Likes causes iframe with like button overlap Description section. Because of that you can not interact with product description text and and follow links in this description.
As I understood from the https://developers.facebook.com/docs/plugins/like-button styles  of a like button can be modified from the third side. So changing the styles of its iframe may cause unpredictable style effects.  So I decided that overriding iframe styles is not the best decision. It is more reliable to set z-index for description under the like button  to shift this description in higher layer and make it clickable.
Here is [task](https://jira.bigcommerce.com/browse/BCTHEME-12) where we have screenshot with a bug. And also I …
=> fix(BC Themes): BCTHEME-12 Cornerstone: Enabling Facebook Likes causes iframe overlap in WYSIWYG

CHANGELOG.md
Adding the following entries to the `CHANGELOG.md` for previous release 4.7.0:
- Document polyfilling strategy in readme. [#1696](https://github.com/bigcommerce/cornerstone/pull/1696)
- Optimize polyfills to reduce download sizes on newer browsers as a way to improve performance. [#1669](https://github.com/bigcommerce/cornerstone/pull/1669)
- Fixed the expand/collapse behavior for Custom filters thad do not have an '&' in their name. [#1693](https://github.com/bigcommerce/cornerstone/pull/1693)
- Line breaks are getting stripped from 'Return Instructions' printed to the storefront. [#1692](https://github.com/bigcommerce/cornerstone/pull/1692)
- Fixes Acount Orders Ship/Bill page to correctly display '&' instead of the encoded version: '&amp'. …
=> Adding change log entries for Release 4.7.0

assets/scss/components/stencil/productView/_productView.scss
On Stencil themes, product list options do not have a set max height. This affects merchants that add a large amount of items to their product list options as it increases the length of the product page and pushes the add to cart button far down the page.
https://jira.bigcommerce.com/browse/BCTHEME-36
ping @yurytut1993 @junedkazi
=> fix(bctheme): BCTHEME-36 Product List Options Do Not Have a Max Height

templates/components/cart/content.html
In `templates/components/cart/content.html` the gift certificate image `alt` and `title` tags are not translatable.
This PR fixes that
=> cart content make gift certificate alt and title translatable

config.json
Change the default layout shape for PayPal smart buttons from `pill` shape to `rect` (which is similar to shape of Checkout Button)
[https://developer.paypal.com/docs/archive/checkout/how-to/customize-button](https://developer.paypal.com/docs/archive/checkout/how-to/customize-button/#button-styles)
Settings
Before
After
=> fix(payments): PAYPAL-528 SPB - change the shape

assets/scss/layouts/products/_productSaleBadges.scss
Cornerstone has 3 types of sale badge - sash, topleft and burst. On hover product with sale badge it must change color that user can setup in storefront panel (color_hover_product_sale_badges settings option in config.json). sash & topleft affecting this value, but burst not. I have added styles for burst sale badge and now hover works on all sale badges
@BC-tymurbiedukhin  @golcinho @junedkazi 
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-2)
=> fix(Cornerstone): BCTHEME-2 Sale badge "Burst" does not change colour on hover

assets/scss/layouts/products/_productView.scss
@BC-tymurbiedukhin @golcinho @junedkazi 
Facebook button (that is in iframe) is not assigned to its container - in case when we have big description of a product, in Quick View mode, when scrolling modal window all content is moving as expected, but button stays on its place. So I updated styles of the button's block in modal window of Quick View
You can see videos with bug and fix in the [Ticket](https://jira.bigcommerce.com/browse/BCTHEME-117)
=> fix(bctheme): BCTHEME-117 Facebook button going out of its container during scrolling in modal

templates/components/amp/products/card.html, templates/components/products/card.html, templates/components/products/list-item.html
@BC-tymurbiedukhin @golcinho @bc-alexsaiannyi @junedkazi 
Update CornerStone to Utilize Existence of sale_price property for Determining Product/Variant Sale Status.
I have changed the way how we check product status - on sale or not. And when sale properties (sale_price_with_tax & sale_price_without_tax) are not exist or their value equal to 0 - product status is NOT on sale. In other case we should add a sale badge
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-45)
=> feature(bctheme): BCTHEME-45 Update CornerStone to Utilize Existence of sale_price property for Determining Product/Variant Sale Status

assets/scss/components/stencil/navPages/_navPages.scss, templates/components/common/navigation-dropdown.html, templates/components/common/navigation-list-alternate.html, templates/components/common/navigation-list.html
@BC-tymurbiedukhin @junedkazi @golcinho 
In Cornerstone we have mobile menu with nested categories if they exist. For now we can not go to the subcategory page if it has its own subcategories (has arrow to dropdown). I have created a wrapper for arrow and replaced data attributes from link on this wrapper. Javascript uses this attributes to open/close nested subcategories. 
So now link is responsible for redirect and arrow responsible for open/close nested subcategories. Also I updated icon wrapper styles to stretch it to the end of the row for comfortable toggling nested categories. 
Styles wrote carefully and not affecting alternate menu styles (by default in config.json navigation_design option value is simple).
In [Ticket](https://jira.bigcommerce.com/browse/BCTHEME-50) you can see 2 …
=> feature(bctheme): BCTHEME-50 ability to load subcategories and expand them if there are other categories beneath it

assets/js/theme/common/collapsible.js, templates/components/common/navigation-list-alternate.html, templates/components/common/navigation-list.html, templates/components/common/navigation-menu.html, templates/components/common/navigation.html
Screen readers are inaccurately reading menu labels (category and pages) within the main navigation.  These menus should have aria labels attached for screen readers to correctly read each element.
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-66)
ping @bc-alexsaiannyi @junedkazi
=> fix(storefront): BCTHEME-66 Add aria labels to menu links

templates/components/common/paginator.html
Pagination on Cornerstone is announced as a number ("1", "2"...) with no additional context.
These links should have an appropriate label in order to make the content useful ("Page x of y")
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-82)
=> fix(storefront): BCTHEME-82 Add labels for PLP pagination

assets/scss/components/stencil/productView/_productView.scss, templates/components/products/product-view.html
On PDPs the "Write a Review" link should be labeled as a "button" rather than a "link".
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-126)
=> fix(storefront): BCTHEME-126 'Write a Review' should have role 'button'

assets/scss/layouts/products/_productView.scss
To avoid space on the left side of the screen when we have a huge description on a product, as suggested in the task, I made description block on the whole screen. So I just removed styles that make this block on the half of the screen width on large displays
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-56)
before
after
=> feature(bctheme): BCTHEME-56 Long Product Descriptions Cause Large White Space Under Product Image

assets/js/theme/common/product-details.js, assets/js/theme/global.js, templates/layout/base.html, templates/pages/product.html
We currently inject the entire `theme_settings` context object which is wasteful, especially since we only use 3 keys from it. I've optimized this import to be [only what's used.](https://github.com/bigcommerce/cornerstone/search?q=themeSettings&unscoped_q=themeSettings)
Before:
After:
=> Optimize themeSettings injection

assets/scss/components/foundation/breadcrumbs/_breadcrumbs.scss, templates/components/common/breadcrumbs.html
Currently breadcrumbs do not have any labels to identify them as breadcrumbs.
In order to allow screen readers to navigate effectively, regions within pages should be sufficiently labeled.
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-81)
[Accessibility doc](https://www.w3.org/TR/wai-aria-practices/examples/breadcrumb/index.html)
=> fix(storefront): BCTHEME-81 Add aria label for breadcrumbs

assets/js/theme/product/image-gallery.js
This PR fixes issue with viewing a product with multiple images. When User clicks on other available images the alt text doesn't change and continues to display a text for the default image.
- [STRF-8521](https://jira.bigcommerce.com/browse/STRF-8521)
[Alt Text Images Fixed](https://github.com/bigcommerce/cornerstone/files/4987117/alt.text.images_fixed.zip)
=> fix(storefront:)STRF-8521 add correct alt text on image change in product view

assets/scss/components/foundation/accordion/_accordion.scss, templates/components/faceted-search/faceted-search-navigation.html, templates/components/faceted-search/facets/hierarchy-children.html, templates/components/faceted-search/facets/hierarchy.html, templates/components/faceted-search/facets/multi.html, templates/components/faceted-search/facets/range.html, templates/components/faceted-search/facets/rating.html, templates/components/faceted-search/index.html, templates/components/faceted-search/selected-facets.html, templates/components/faceted-search/show-more-facets.html
The current HTML markup for the link to clear faceted search element's items is invalid as it is located inside a button. This update moves the clear link outside the navigation button, so it no longer violates W3C markup standards (see below for a screenshot of the error message). This update also adds padding so the title of the filter does not overlap with the clear button.
Additionally, this update componentizes the faceted search navigation. Previously, the faceted search navigation code was repeated in the exact same code across 3 different templates.
Lastly, this update cleans up some extraneous whitespace (for consistency with the rest of the codebase) and otherwise questionable code.
The only visible change to the theme is, as stated above, the padding adjustment to prevent the …
=> Move clear link outside of Faceted Search navigation button

CHANGELOG.md, assets/scss/layouts/footer/_footer.scss
This PR fixes overlaping in footer columns that can appear when entering long texts without spaces. Also ms vendor prefix was added since overflow-wrap doesn't work in IE11.
- [BC-THEME43](https://jira.bigcommerce.com/browse/BCTHEME-43)
=> fix(storefront):BCTHEME-43: fix overlaping on footer columns

CHANGELOG.md, assets/js/polyfills.js, assets/js/theme/common/product-details.js, assets/js/theme/common/utils/ie-helpers.js, package-lock.json, package.json
This PR fixes 2 issue that prevent a User to add product to cart on IE11:
- [HTMLInputElement.labels](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/labels) that are used is not supported in IE11 which leads to mentioned in ticket description error
-FormData Object is badly supported in IE11 as well so [polyfill](https://www.npmjs.com/package/formdata-polyfill) has been added to secure things in IE.
- [BCTHEME-154](https://jira.bigcommerce.com/browse/BCTHEME-154)
[BCT154_IE11 Add to Cart Fix](https://github.com/bigcommerce/cornerstone/files/5023338/BCT154_IE11.Add.to.Cart.fix.zip)
=> fix(storefront)BCTHEME-154: fix issue with add product to cart on IE11

CHANGELOG.md, assets/scss/layouts/products/_productView.scss, templates/components/products/product-view.html
Now when you tabbing through page product images fill receive focus firstly before focusable items in product details block (for example write review link). 
To do this I moved block with images above details block in html. Because of using floats in css, changing block position didn't affect visual presentation of layout. But on mobile I should have details block higher than images block. So I have to use flex and change the order of details block to set him at the top using order: -1. Tabbing on mobile is not necessary, so order on mob devices might be not important.
Alternative variant - have 2 similar details html blocks - one above images block and one under. On mobile version will be active above block, and on desktop under block …
=> feature(storefront): BCTHEME-134 Incorrect focus order on PDPs

CHANGELOG.md, assets/scss/layouts/footer/_footer.scss, lang/en.json, templates/components/common/footer.html, templates/components/common/subscription-form.html
@BC-tymurbiedukhin @bc-alexsaiannyi 
Added visually hidden h2 in footer for screen readers. Now users can understand that they navigate through footer block. 
Also I changed footer section headers from h5 to h3 for more proper semantics 
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-133)
h2
h3
=> feature(storefront): BCTHEME-133 Improper footer heading hierarchy

CHANGELOG.md, templates/components/amp/products/card.html, templates/components/products/card.html, templates/pages/brands.html, templates/pages/compare.html
We have product link wrapped in h4 tag which is unnecessary. It can be possible just to remove h4, but I decided to change h4 to span for saving style class which was setted on h4, and now it is setted on span.
Also I should mention that typography styles little bit changed after disabling h4. But we don't have heading already - so we don't need heading styles. I think it is correct - now product name link has similar typography styles with other links in cornerstone. 
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-142)
main page grid cards
compare page cards
brand page cards
=> feature(storefront): BCTHEME-142 Unnecessary heading on product cards

CHANGELOG.md, templates/pages/sitemap.html
Changes sitemap list titles from h3 to h2
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-157)
=> feature(storefront): BCTHEME-157 Improper heading hierarchy on Sitemap

CHANGELOG.md, templates/components/cart/content.html
Updated cart item title tag from h3 to h2 on Cart Page
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-158)
=> feature(storefront): BCTHEME-158 Improper heading hierarchy on Cart page

assets/js/test-unit/theme/carousel.spec.js, assets/js/theme/common/carousel.js, lang/en.json, templates/components/carousel.html, templates/components/products/carousel.html
@BC-tymurbiedukhin  @bc-alexsaiannyi 
Carousel now has arrows with dynamic aria-labels. It tells the user on what exactly slide he will go when click on arrow, and how many slides in carousel. Also refactored code
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-68)
left arrow init
right arrow init
left arrow after slide forward
right arrow after slide forward
Also I changed behaviour of products carousel a little bit (at the bottom of the homepage). Now click on arrow triggers moving slides by one. And carousel in a loop now. This is necessary for correct aria-labels of arrows. Or maybe we can use 
"Previous" and "Next" for aria-labels in this carousel
product carousel now   
product carousel before
=> feature(storefront): BCTHEME-68 Add tooltips for carousel "Previous" and "Next" buttons

CHANGELOG.md, assets/js/theme/common/product-details.js, assets/js/theme/global/modal.js, templates/components/common/modal.html, templates/components/products/product-view.html
@BC-tymurbiedukhin  @bc-alexsaiannyi 
Now when user open a product details modal it has automatically focused on first element (close button). When user tabbing through modal elements focusable will be only modal elements, while user click close button.
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-74)
[product_details_modal_trap.zip](https://github.com/bigcommerce/cornerstone/files/5015024/product_details_modal_trap.zip)
=> feature(storefront): BCTHEME-74 As a shopper I want to have the add to cart modal immediately have keyboard focus

assets/scss/layouts/header/_header.scss
Actual result: On mobile logo centering in screen when nav menu is expanded
Expected result: On mobile logo centering in header when nav menu is expanded
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-166)
=> fix(storefront): Fix main logo display on mobile with expanded menu

CHANGELOG.md, assets/scss/layouts/header/_header.scss
This PR fixed issue with missing logo on Mobile devices and tablets.
- [BCTHEME-150](https://jira.bigcommerce.com/browse/BCTHEME-150)
=> fix(storefront): BCTGHEME-150 fix missing logo on mobile and tablets

lang/en.json, templates/components/cart/content.html
On the cart page, the remove item "x" should be a button rather than the current implementation as a link.
Additionally, this button should have an appropriate label.
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-125)
=> fix(storefront): BCTHEME-125 Cart remove 'X' should be a button

CHANGELOG.md, assets/js/theme/search.js, assets/scss/components/stencil/search/_search.scss, assets/scss/tools/_mixins.scss, assets/scss/tools/_tools.scss, lang/en.json, templates/pages/search.html
Search page tabs status (selected) was not announced by screen reader. Now it is working. Also I added a hint how to change selected tab using left and right arrows/
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-156)
first tab selected
second tab selected (hint text)
video example
[search_tabs.zip](https://github.com/bigcommerce/cornerstone/files/5090034/search_tabs.zip)
=> feature(storefront):  BCTHEME-156 Selected state on search page not announced

CHANGELOG.md, templates/components/carousel-content.html
Each slide in the homepage carousel contains an h1 tag for the slide headings.  These headings are inconsistent with guidelines for page hierarchy. Instead of h1 tags, carousel headings should be h3 or h4
[Jira Ticket](https://jira.bigcommerce.com/browse/BCTHEME-139)
=> fix(storefront): BCTHEME-139 Unnecessary heading tag in carousel

CHANGELOG.md, lang/en.json, templates/components/category/shop-by-price.html, templates/components/category/sidebar.html
The link text provided for the links present under "Shop By Price" is insufficient to describe what the links are in reference to.
The link text should have more meaningful text in order to provide users with useful information - (ex: "Range of $0.00 to $51.00")
[Jira Ticket](https://jira.bigcommerce.com/browse/BCTHEME-153)
=> fix(storefront): BCTHEME-153 Insufficient link text

CHANGELOG.md, assets/js/theme/global/quick-search.js, templates/components/common/navigation-menu.html, templates/components/common/navigation.html, templates/components/common/quick-search.html
The id "search_query" is used twice to describe attributes within the same page.
Duplicate ARIA IDs are common validation errors that may break the accessibility of labels, e.g., form fields, table header cells. Unique ID's differentiate each element from another and prevent invalid markup, wherein only the first instance gets acted upon by client-side scripting, or where assistive technologies typically only reference the first one accurately.
[Jira Ticket](https://jira.bigcommerce.com/browse/BCTHEME-159)
-
=> fix(storefront): BCTHEME-159 IDs used in ARIA and labels are not unique

CHANGELOG.md, templates/components/products/tabs.html
This PR adds valid ARIA roles for Related Products Tab li elements
- [BCTHEME-160](https://jira.bigcommerce.com/browse/BCTHEME-160)
=> BCTHEME-160: add valid ARIA role for Related Products tab

CHANGELOG.md, assets/scss/components/stencil/productView/_productView.scss
This PR has fix for hidden cart icon on Android Chrome. Seems like it is a bug in browser calculations of some width
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-35)
=> fix(storefront): BCTHEME-35 Cornerstone - Cart link not visible on mobile Chrome depending on swatch image size

CHANGELOG.md, assets/scss/components/stencil/productView/_productView.scss, assets/scss/components/stencil/search/_search.scss, assets/scss/tools/_aria.scss, assets/scss/tools/_mixins.scss, assets/scss/tools/_tools.scss, templates/components/products/product-view.html, templates/pages/search.html
Write a review link on a PDP should not be focused twice
[Jira Ticket](https://jira.bigcommerce.com/browse/BCTHEME-194)
=> fix(storefront): BCTHEME-194 Review link in quick modal focused twice

CHANGELOG.md, assets/scss/components/stencil/productView/_productView.scss, assets/scss/tools/_theme_focus.scss, assets/scss/tools/_tools.scss
Fixed next group of issues:
https://jira.bigcommerce.com/browse/BCTHEME-177
https://jira.bigcommerce.com/browse/BCTHEME-180
https://jira.bigcommerce.com/browse/BCTHEME-181
https://jira.bigcommerce.com/browse/BCTHEME-183
https://jira.bigcommerce.com/browse/BCTHEME-182
I took Chrome focus styles as a base and changed it outline color for it to be acceptable for light and dark themes.
We can use this focus styles as a base and rewrite it for custom cases if we will need
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-196)
light theme contrast
dark theme contrast
carousel arrows focus
carousel dots focus
cart buttons focus
options focus
=> feature(storefront): BCTHEME-196 Create unified focus styling in Cornerstone

.github/workflows/pull_request_review.yml
Making a few improvements to the GitHub action which does a test bundle.
* Better docs/comments
* Better name
* Support "master" or "main" branch as new forks will use `main`
* https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/
* https://github.com/github/renaming
* ~Use node 12~ waiting for new version of CLI to release first
* Add both a ruby gem cache as well as an npm cache to speed things up (CLI install is most of the time spent currently)
=> Refactor GitHub action for Bundle Test

CHANGELOG.md, assets/js/theme/global/quick-search.js, templates/components/common/navigation.html
Expanded/Collapsed state of Search link is not notify by screen reader.
Notifications and alerts of content changes, errors, and status updates are important aspects of a website or web application’s usability.
https://www.w3.org/WAI/GL/wiki/Using_the_WAI-ARIA_aria-expanded_state_to_mark_expandable_and_collapsible_regions
[Jira Ticket](https://jira.bigcommerce.com/browse/BCTHEME-171)
=> fix(storefront): BCTHEME-171 State of search link not announced

CHANGELOG.md, assets/scss/components/foundation/modal/_modal.scss, templates/components/common/modal/modal-close-btn.html
Cross icon is not on the center of button
[Jira Ticket](https://jira.bigcommerce.com/browse/BCTHEME-211)
=> fix(storefront): BCTHEME-211 Cross icon on close button missalignment

CHANGELOG.md, assets/scss/components/citadel/cards/_cards.scss
When card buttons in focus they becomes transparent and without outline. This styles we have from class .button. We can not remove this class, because it has styles from page bilder. So for now I override needed styles.
p.s. 
revert css value not supported in some browsers, such is ie 11 and opera. In this browsers focused buttons just will not be transparent. In other focused buttons will have default browser styles. In nearest future we will create our own Cornerstone focus styles with will work in all browsers. For now - just switching to default
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-191)
=> fix(storefront): BCTHEME-191 Incorrect styles for focused buttons in grid card product item

CHANGELOG.md, assets/scss/layouts/header/_header.scss
Logo has no visible focus state styles. I have changed some link styles to become focus styles visible 
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-167)
text logo desktop
text logo mobile
image logo desktop
image logo mobile
=> fix(storefront): BCTHEME-167 Focus not visible on logo element

.github/workflows/pull_request_review.yml
Node 12 is now supported for Stencil CLI, so we'll use it for this action going forward.
=> Update GitHub Action to use Node 12

.github/workflow-examples/automatic_deployment_production.yml, .github/workflow-examples/poll_for_changed_configuration.yml
Add a few examples of useful GitHub actions for theme development.
1. Automatically deploy theme to a production store on merge to master/main
2. As a scheduled job, check for changes to the production store's configuration and create a PR back to the repo to keep things in sync
=> Add examples of useful GitHub Actions for theme development

.browserslistrc, babel.config.js, webpack.common.js
Cornerstone had webpack config that overrides babel for the browsers list support. That list was updated to target the browsers, that are in the documentation 
https://support.bigcommerce.com/s/article/Themes-Supported-Browsers
=> fix(storefront): STRF-8607 Unified browsers list that we support

assets/js/test-unit/theme/common/faceted-search.spec.js, assets/js/theme/cart.js, assets/js/theme/catalog.js, assets/js/theme/common/faceted-search.js, assets/js/theme/global/quick-search.js, package-lock.json, package.json
…
Changed the behaviour of the stencil utils event handlers. Target element is now taken not from event.currentTarget, but passed from the stencil-utils eventemitter.
https://jira.bigcommerce.com/browse/STRF-8599
=> fix(storefront): STRF-8599 Drop Jquery: Replaced event's current target to the element passed from utils(on hook)

assets/scss/components/stencil/applePay/_applePay.scss
Change the width size for apple pay button in order to avoid button size varies
[Ticket](https://jira.bigcommerce.com/browse/INT-3211)
Desktop
Safari responsive mode emulating iPhone 8 Plus
=> fix(payments): INT-3211 Change width size for apple pay button

config.json, templates/components/account/messages-list.html, templates/components/account/order-contents.html, templates/components/account/orders-list.html, templates/components/account/payment-methods-list.html, templates/components/cart/content.html, templates/components/cart/modals/gift-wrapping-form.html, templates/components/common/cart-preview.html, templates/components/common/quick-search.html, templates/components/faceted-search/facets/range.html
Updated cornerstone theme to be compatible with the handlebars v4. Most changes are applied due to changed logic in the calculating `../` and `=` character is now HTML escaped. 
https://github.com/handlebars-lang/handlebars.js/blob/master/release-notes.md#v400---september-1st-2015
https://jira.bigcommerce.com/browse/STRF-8626
https://jira.bigcommerce.com/browse/STRF-8630
Several times tried to do that using functional tests. Couldn't get a case, when the tests weren't failing. I've got, that latest master(e1270850b1b083d762b339e57096b2c06be53ef3) and these changes have same amount errors(except 1 case on master). Links I'm able to provide in private
=> feat(storefront): STRF-8630 update cornerstone to be compatible with handlebars v4

CHANGELOG.md, assets/scss/components/citadel/actionBar/_actionBar.scss
This PR has fix for selects styles for their outline on focus to be visible
[Ticket](https://jira.bigcommerce.com/browse/BCTHEME-185)
sort-box.html
content-sort-box.html
=> fix(storefront): BCTHEME-185 Sort By dropdowns need visual focus border

CHANGELOG.md, assets/scss/layouts/header/_header.scss
This PR fixes issue with not optimised logo size and how it's been displayed on different Store versions.  When Logo is set to Origin and Mobile Store in use Logo is moved to flex-start position. The problem is related only for origin size since image has different css class in this case `.header-logo-image-unknown-size`. Due to using of flexbox we can fix this with its properties.
Origin ticket has been also opened in terms of overlapping Navigation Menu while using specific (custom) size Logo. It's been fixed earlier thanks to @yurytut1993 on [PR#1800](https://github.com/bigcommerce/cornerstone/pull/1800).Pics are attached.
- [BCTHEME-279](https://jira.bigcommerce.com/browse/BCTHEME-279)
=> fix(storefront): BCTHEME-279 fix logo displaying

CHANGELOG.md, assets/js/theme/global/compare-products.js, assets/js/theme/product/image-gallery.js
Reduce lodash usage (and bundle size) by utilizing the object spread operator to clone imgObj in image-gallery.js when setMainImage() runs.
**BEFORE**
**AFTER**
=> Reduce lodash usage in compare-products.js and image-gallery.js

.gitignore
In https://github.com/bigcommerce/stencil-cli/pull/662 we split the `.stencil` file into 2 separate config files, so I added these files to .gitignore here.
STRF-8747
=> STRF-8747: add new stencil config files to .gitignore

assets/js/theme/global/quick-view.js, package-lock.json, templates/components/common/share.html, templates/components/products/product-view.html, templates/layout/base.html
Instead of adding global JS to make sure social icons load, we will instead hide them from quick view. Making this change as the previous approach introduced a performance regression.
Normal PDP:
Quick view:
Depends on [`stencil-utils` release](https://github.com/bigcommerce/stencil-utils/pull/144) and https://github.com/bigcommerce/bigcommerce/pull/38045
=> Hide social sharing icons from quick view

CHANGELOG.md, lang/en.json, templates/components/cart/totals.html
This PR moves tax field on Cart when Tax is set to be inclusive. It  adds feature parity with Blueprint and improves Customer experience.
- [BCTHEME-116](https://jira.bigcommerce.com/browse/BCTHEME-116)
=> feat(storefront): BCTHEME-116 move tax field after grand total when tax inclusive

CHANGELOG.md, templates/layout/base.html, templates/pages/product.html
Pressing on quick view, image changes not reflected
- https://jira.bigcommerce.com/browse/STRF-8769
- https://jira.bigcommerce.com/browse/BCTHEME-295
=> STRF-8769 Quick View - Image and price changes not reflected if an image is assigned to variant/sku

CHANGELOG.md, assets/js/theme/product/image-gallery.js
Selecting product options doesn't update image on PDP in Internet Explorer
[Jira ticket](https://jira.bigcommerce.com/browse/BCTHEME-104)
=> fix(storefront): BCTHEME-104 Selecting product options doesn't update image on PDP in Internet Explorer

CHANGELOG.md, assets/js/theme/cart.js, assets/js/theme/common/cart-item-details.js, assets/js/theme/common/product-details-base.js, assets/js/theme/common/product-details.js, assets/scss/components/foundation/modal/_modal.scss, templates/components/cart/content.html, templates/components/cart/modals/configure-product.html
This PR fixes an issue with showing product options that are out of stock on Cart Page while hiding them on Product Page. The issue was caused that on Cart Product attributes weren't updated. It was addressed by initiating **ProductDetails Class** on  editing Cart Options via `cartEditOptions` method. It using `updateProductAttributes` method for handle this case.
`productAttributes.optionChange` method from stencil-utils requires productId as its first param. Using itemId instead leads to sending request with undefined and received empty response (the scree's attached). Therefore it was also changed on productId. 
And selector  for `$changedOption`  has been replaced from currentTarget on event.target.Since first one returns us modal instead of option and leads to missing elements …
=> fix(storefront): BCTHEME-11 hide product options that are out of stock on cart

CHANGELOG.md, assets/scss/components/stencil/adminBar/_adminBar.scss
This PR has fix for header on mobile when admin bar is enabled
[BCTHEME-301](https://jira.bigcommerce.com/browse/BCTHEME-301)
before
after
=> fix(storefront): BCTHEME-301 Header content placed out of the header block on mobile

CHANGELOG.md, assets/js/theme/search.js, templates/components/category/sort-box.html, templates/components/products/filter.html, templates/components/search/content-sort-box.html
This PR has fix for search page sorting. It has fix for both product sorting and content sorting.
Two hidden inputs were added to control search query and active tab of the search page (product or content)
Form submits from stencil utils.
[BCTHEME-85](https://jira.bigcommerce.com/browse/BCTHEME-85)
bug on products or content request after submitting sort form looks the same, because sending request from content tab will reload page on content tab
fix product
fix content
=> fix(storefront): BCTHEME-85 “Sort by” dropdown selection not reflected on search results page for News and Information tab

CHANGELOG.md, assets/scss/components/citadel/forms/_forms.scss, templates/components/amp/products/options/set-rectangle.html, templates/components/amp/products/options/swatch.html, templates/components/products/options/set-rectangle.html, templates/components/products/options/swatch.html
This PR addresses issue with misaligned tooltip. When product has required options and customer clicks  on "Add it on Cart" button without selection a tooltip with message is misaligned. To fix this issue html wrapper has been added as well some css.
- [BCTHEME-30](https://jira.bigcommerce.com/browse/BCTHEME-30)
=> fix(storefront): BCTHEME-30 fix misaligned tooltip for required product option

CHANGELOG.md, templates/components/amp/css/category.html
This PR has fix for destorted images of product cards on category page. Now all images will be contained in card space
[BCTHEME-87](https://jira.bigcommerce.com/browse/BCTHEME-87)
ios
android
=> fix(storefront): BCTHEME-87 Product images squashed in Category view in AMP

assets/js/theme/common/utils/safe-string.js, assets/js/theme/product/reviews.js
This change introduces a utility function to Cornerstone that parses strings with HTML entities safely.
When https://github.com/bigcommerce/paper-handlebars/pull/110 and https://github.com/bigcommerce/paper/pull/215 are deployed, all strings injected into jsContext will have unsafe characters escaped to prevent XSS. This means any string pulled directly from jsContext and surfaced to the storefront user will display HTML entities if it has escaped characters. 
There are values that can be controlled exclusively by the merchant/developer that should be parsed so that they're rendered correctly.
The product review modal is one example; it uses injected strings that are managed from the lang files. Since the strings include escaped single quotes, HTML entities will be displayed to the …
=> fix(storefront): BCTHEME-313 Parse HTML entities in jsContext

CHANGELOG.md, templates/pages/cart.html
New PayPal credit banner on the cart page above the checkout button
[Ticket](https://jira.bigcommerce.com/browse/PAYPAL-823)
=> feat(payments): PAYPAL-823 Add new banner on the cart page

CHANGELOG.md, assets/js/theme/common/utils/pagination-utils.js, assets/js/theme/wishlist.js, templates/components/account/wishlist-item-list.html, templates/components/common/paginator.html, templates/pages/account/wishlist-details.html
This PR adds pagination for Wishlist item.
Response with Pagination Wishlist Object:
```
{
"previous": null,
"next": 2,
"current": 1,
"links": [
{
"number": 1,
"url": "/wishlist.php?0%5Baction%5D=viewwishlistitems&0%5Bwishlistid%5D=1&page=1"
},
{
"number": 2,
"url": "/wishlist.php?0%5Baction%5D=viewwishlistitems&0%5Bwishlistid%5D=1&page=2"
}
]
}
```
- [BCTHEME-304](https://jira.bigcommerce.com/browse/BCTHEME-304)
=> feat(storefront): BCTHEME-304 add pagination for Wish Lists

CHANGELOG.md, assets/scss/components/citadel/forms/_forms.scss, assets/scss/settings/citadel/forms/_settings.scss
This PR fixes input placeholder color contrast in compliance with AA standard. It's using ` input-font-color`  from `config.json` for changing color through 3 Theme's variants:
`#666666` for Light, 
`#cccccc` for Bold,
`#4f3f2f` for Warm
- [BCTHEME-341](https://jira.bigcommerce.com/browse/BCTHEME-341)
=> fix(storefront): BCTHEME-341 fix placeholder contrast ratio according to AA standard

CHANGELOG.md, assets/js/theme/product/image-gallery.js, assets/scss/components/stencil/productView/_productView.scss
This PR has fix for product image zoom on PDP in IE11. The problem was because zoom image height and width were calculated as 0 in IE, so if statement with hiding zoom was truthful. Changing the method of calculating width and height fixed the problem
[BCTHEME-37](https://jira.bigcommerce.com/browse/BCTHEME-37)
in chrome calculations of image sizes was correct
but in ie11 old method of calculation returned 0
=> fix(storefront): BCTHEME-37 Cornerstone - Image Zoom Does Not Work on Internet Explorer

CHANGELOG.md, assets/js/test-unit/theme/common/payment-method.spec.js, assets/js/theme/common/product-details-base.js
This PR adds opportunity to narrow down price on option selection and show to Customer a price range for selected option if it's avalable. It's linked with [PRICE-14](https://jira.bigcommerce.com/browse/PRICE-14).
- [BCTHEME-306](https://jira.bigcommerce.com/browse/BCTHEME-306)
After:
Before:
=> feat(storefront): BCTHEME-306 show price range on option selection

CHANGELOG.md, templates/components/cart/content.html
This PR has fix for long loading of product images on Cart Page. The reason of this issue is using wrong path to images from cdn - they are full size instead of being optimized for small size of cart item. Improvement is that for common resolution displays used 100x100 images and for high resolution displays used 200x200 images
[BCTHEME-16](https://jira.bigcommerce.com/browse/BCTHEME-16)
images were taking from the wrong srcset url because of no size attribute it it
after changing lazyload field sent to responsive-img component, lazysizes library sets sizes attributes to the images and correct url from src set is taken
=> fix(storefront): BCTHEME-16 Cornerstone - loading of thumbnail image delayed on cart page 

CHANGELOG.md, assets/js/theme/cart.js
This PR addresses issue with not being able to change product quantity on Cart page using keyboard multiple times.
- [BCTHEME-193](https://jira.bigcommerce.com/browse/BCTHEME-193)
the video is attached to the ticket as well.
https://user-images.githubusercontent.com/67792608/103279357-425aad80-49d6-11eb-881c-1b9e7d382faa.mov
=> fix(storefront): BCTHEME-193 fix not being able to change product qty with keyboard multiple times

CHANGELOG.md, templates/components/common/body.html
This PR fixes an issue with not defining main region on pages by using HTML5 semantic tag `main`; for supporting this on IE11 `role='main' `has been [explicitly](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main) added  to ensure it is accessible in screen readers like JAWS. 
- [BCTHEME-345](https://jira.bigcommerce.com/browse/BCTHEME-345)
=> fix(storefront): BCTHEME-345 define a main region on pages

CHANGELOG.md, assets/js/theme/cart/shipping-estimator.js, templates/components/cart/shipping-estimator.html
This PR fixes an issue when shipping estimator error message are not announced by screen reader. aria-live="assertive" has been added to maximize compatibility based on MDN.
- [BCTHEME-346](https://jira.bigcommerce.com/browse/BCTHEME-346)
https://user-images.githubusercontent.com/67792608/102997339-86106b80-452d-11eb-9f4e-32adbe703346.mov
=> fix(storefront): BCTHEME-346 add announcement for shipping estimator error messages

CHANGELOG.md, assets/js/theme/common/carousel/index.js, assets/js/theme/common/carousel/utils/index.js, assets/js/theme/common/carousel/utils/tooltipSetup.js, assets/scss/common/_focus-tooltip.scss, assets/scss/common/index.scss, assets/scss/components/foundation/modal/_modal.scss, assets/scss/components/stencil/heroCarousel/_heroCarousel.scss, assets/scss/components/vendor/slick/_slick.scss, assets/scss/settings/vendor/slick/_settings.scss, assets/scss/theme.scss, templates/components/carousel.html
This PR implements slider buttons tooltips. Also it has fix for prev next arrows aligning.
[BCTHEME-343](https://jira.bigcommerce.com/browse/BCTHEME-343)
arrows aligning before
arrows aligning after
=> feature(storefront): BCTHEME-343 No tooltips provided for carousel buttons

CHANGELOG.md, templates/components/common/cart-preview.html
This PR adds empty cart notification for screen reader in cart preview
[BCTHEME-342
](https://jira.bigcommerce.com/browse/BCTHEME-342)
=> feature(storefront): Empty cart message not read by screen reader

CHANGELOG.md, assets/js/theme/common/carousel/utils/setTabindexes.js, templates/components/carousel-content.html, templates/components/carousel.html
This PR has update for slide button in carousel. If button added to slide - it use link from page builder and the slide is div tag. In case we have no button whole slide is the link
[BCTHEME-344](https://jira.bigcommerce.com/browse/BCTHEME-344)
=> feat(storefront): BCTHEME-344 Carousel buttons do not receive focus

CHANGELOG.md, assets/js/theme/auth.js, lang/en.json, templates/pages/auth/create-account.html
This PR addresses the issue on Windows/Edge browser when screen reader announces a hidden content for Google reCAPTCHA. It probably connects that some browsers can [treat](https://www.powermapper.com/tests/screen-readers/labelling/iframe-title/) iframes as focusable elements and read its URL when they receive focus.
- [BCTHEME-155](https://jira.bigcommerce.com/browse/BCTHEME-155)
the video is also uploaded to ticket itself.
[Edge_windows_recaptcha.mov.zip](https://github.com/bigcommerce/cornerstone/files/5795214/Edge_windows_recaptcha.mov.zip)
=> fix(storefront): BCTHEME-155 fix recaptcha announcement for hidden content

CHANGELOG.md, assets/scss/tools/_theme_focus.scss
This PR fixes issue with Insufficient non-text contrast for active focus on buttons like add to cart, proceed to checkout etc.
Used color in line with AA standard.
- [BCTHEME-379](https://jira.bigcommerce.com/browse/BCTHEME-379)
=> fix(storefront): BCTHEME-379 fix non-text contrast on add to cart button

CHANGELOG.md, assets/js/theme/common/product-details.js, templates/components/products/add-to-cart.html
This PR improves announcement by Screen Reader when User clicks on button 'Add to Cart'. Hidden description has been added for Add to Cart button on Modal window (quickView) and PDP. Role status is being added on button's click.
- [BCTHEME-369](https://jira.bigcommerce.com/browse/BCTHEME-369)
https://user-images.githubusercontent.com/67792608/104591877-02eabd00-5676-11eb-80fd-baa5118ab8e6.mov
https://user-images.githubusercontent.com/67792608/104591881-054d1700-5676-11eb-8caf-12e27095983c.mov
=> fix(storefront): BCTHEME-369 fix announcement on adding to cart by screen reader

CHANGELOG.md, config.json, package-lock.json
Updating theme/variant verticals as outlined in BCTHEME-387.
Updated config.json file to meet the requirements outlined in BCTHEME-387 to help remerchandise our Themes on our public marketplace
https://jira.bigcommerce.com/browse/BCTHEME-387
- n/a
n/a
=> BCTHEME-387: Updates Cornerstone variants to meet the updated verticals 

CHANGELOG.md, assets/js/theme/search.js, package-lock.json, package.json
Updated Stencil Utils to 6.8.1 and removed changes from https://github.com/bigcommerce/cornerstone/pull/1910/files
- [STRF-8948](https://jira.bigcommerce.com/browse/STRF-8948)
=> STRF-8948 Fix Sort By on Search Page

CHANGELOG.md, assets/js/theme/category.js, lang/en.json, templates/components/category/shop-by-price.html
This PR fixes screen reader's announcement for selecting Shop by price filter. 
- [BCTHEMEW-368](https://jira.bigcommerce.com/browse/BCTHEME-368)
https://user-images.githubusercontent.com/67792608/105489917-aeba8b00-5cbc-11eb-93fb-86ecca528ea9.mov
=> fix(storefront): BCTHEME-368 fix announcement for shop by price filter selection

CHANGELOG.md, assets/js/theme/catalog.js, assets/js/theme/category.js, assets/js/theme/search.js
This PR addresses focus issue on SortBy element after reloading page. It can be seen as a solution before implementing partly page update mechanism. At the moment, new method `arrangeFocusOnSortBy` has been added to CatalogPage Class and can be used on pages where sortBy select is presented (such as category or search). CatalogPage constructor helps to set up event listener that tracks if sortBy is active and keeps it on LocalStorage  in that case.
- [BCTHEME-207](https://jira.bigcommerce.com/browse/BCTHEME-207)
https://user-images.githubusercontent.com/67792608/105361889-dbaa6780-5c02-11eb-8d58-c2bdc5bdf070.mov
=> fix(storefront): BCTHEME-207 fix focus on sort by

CHANGELOG.md, lang/en.json, templates/pages/compare.html
The PR fixes hard-coding phrase in html and moves it to en.json
- [BCTHEME-385](https://jira.bigcommerce.com/browse/BCTHEME-385)
=> fix(storefront): BCTHEME-385 move a phrase from html to en.json

CHANGELOG.md, assets/js/theme/common/carousel/index.js, assets/js/theme/global/quick-view.js, assets/scss/components/stencil/heroCarousel/_heroCarousel.scss, assets/scss/components/stencil/productCarousel/_productCarousel.scss, templates/components/products/product-view.html
This PR integrate accessibility to product images slider on PDP
[BCTHEME-390](https://jira.bigcommerce.com/browse/BCTHEME-390)
https://user-images.githubusercontent.com/66325265/105369070-dd782900-5c0a-11eb-8201-96cb8373cb15.mov
=> feat(storefront): BCTHEME-390 Integrate accessibility scripts to product images slider on PDP

CHANGELOG.md, templates/components/products/options/product-list.html
when a Product has multiple Pick List Options, the "none" option cannot be selected for both. This has been confirmed on both V2 and V3 Pick List Options
[Jira Ticket](https://jira.bigcommerce.com/browse/BCTHEME-354)
https://user-images.githubusercontent.com/66319629/106131081-e1f09480-616a-11eb-957d-8ec048e19906.mov
=> fix(storefront): BCTHEME-354 If multiple Pick List Options are applied, customers cannot select 'none' on both

CHANGELOG.md, templates/components/amp/products/options/input-checkbox.html, templates/components/products/options/input-checkbox.html
Required checkbox error popup blocks the checkbox field. This occurs if you attempt to add a product to cart without selecting a required checkbox. 
[Jira Ticket](https://jira.bigcommerce.com/browse/BCTHEME-356)
=> fix(storefront): BCTHEME-356 Required checkbox message blocks the checkbox

CHANGELOG.md, assets/js/theme/common/faceted-search.js, assets/js/theme/global/modal.js, templates/components/carousel.html
This PR adds focus trap on show more modal with filter options
[BCTHEME-391
](https://jira.bigcommerce.com/browse/BCTHEME-391)
This flow can be present on PLP
https://user-images.githubusercontent.com/66325265/106426431-42831880-646e-11eb-8d58-ab0ad35df03b.mov
search page
https://user-images.githubusercontent.com/66325265/106426472-5169cb00-646e-11eb-9d3c-e79a94d60749.mov
and brands
https://user-images.githubusercontent.com/66325265/106426487-5af33300-646e-11eb-8221-b6dfdd0de070.mov
=> feat(storefront): BCTHEME-391 Move focus on filter items Modal after show more button was clicked and accessibility refactoring

CHANGELOG.md, assets/js/theme/common/product-details.js, config.json, lang/en.json, schema.json, schemaTranslations.json, templates/components/common/requireness-msg.html, templates/components/products/options/swatch.html, templates/components/products/product-view.html
This PR adds setting to Page builder that provides/hides a text along with color swatches on  a Store. When it's set to 'Show' User'll see swatch name on picking an option. Screen Reader will announce it as well. All this will do Shopper Experience much better.
To achieve this handlebars logic has been divided on 2 parts:
-using dynamicComponent for all options except Swatches,
-add explicitly swatch component with flag that can be manipulate of  Show swatch name setting.
- [BCTHEME-381](https://jira.bigcommerce.com/browse/BCTHEME-381)
https://user-images.githubusercontent.com/67792608/106276306-12563280-6240-11eb-97de-249d9ff2f142.mov
https://user-images.githubusercontent.com/67792608/106276322-17b37d00-6240-11eb-9480-d953b9a33a33.mov …
=> feat(storefront) BCTHEME-381 add sufficient & informative text along with the color swatches

CHANGELOG.md, templates/components/products/options/set-radio.html
Preventing duplicate ids in case of more than one radio groups
[Jira](https://jira.bigcommerce.com/browse/BCTHEME-398)
=> fix(storefront): BCTHEME-398 Make every product option group id unique

CHANGELOG.md, assets/js/theme/common/product-details.js, templates/components/common/alert/alert-info.html
This PR fixes issue with updating Discount Banner when product is added to Cart on PDP. After adding product to cart we reload page if banner is presented. The same behaviour is also added for modal close button since it returns us to PDP as well.  For categories that don't contain any promotions there won't be extra reloading.
**Note:** there is a discount banner for kitchen category products in the the attached videos. 
- [BCTHEME-264](https://jira.bigcommerce.com/browse/BCTHEME-264)
https://user-images.githubusercontent.com/67792608/106008058-9d5bef00-60bf-11eb-8d06-08b0092ab1c1.mov
https://user-images.githubusercontent.com/67792608/106008107-a77ded80-60bf-11eb-935e-2b3d30cb2073.mov
=> fix(storefront): BCTHEME-264 fix update discount banner on PDP

CHANGELOG.md, templates/components/products/options/set-radio.html
If options are not required, on the storefront the "None" option is selected automatically and cannot be deselected if another option is chosen.
[Jira](https://jira.bigcommerce.com/browse/BCTHEME-400)
=> fix(storefront): BCTHEME-400 If product options are not required, the 'None' option will remain selected even if another option is chosen

CHANGELOG.md, lang/en.json, templates/components/common/responsive-img.html
Add alt attribute for no image placeholders
[Jira](https://jira.bigcommerce.com/browse/BCTHEME-334)
=> fix(storefront): BCTHEME-334 Add alt attribute for no image placeholders

CHANGELOG.md, templates/components/amp/products/ratings.html, templates/components/products/ratings.html
Due to [w3c](https://www.w3.org/TR/wai-aria-1.1/#img) alt text is acceptable for role image, but if it affects validation we can use second approach - aria-label attribute for element with role image. It has the same result for screen reader and successfully pass validation. Due to [mdn](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Role_Img) alt also acceptable, but all examples using aria-label, so it should be the best solution.
[BCTHEME-401](https://jira.bigcommerce.com/browse/BCTHEME-401)
=> fix(storefront): BCTHEME-401 Category pages are creating alt attribute within the span tag

CHANGELOG.md, assets/scss/components/stencil/cart/_cart.scss
This PR fixes a cut off on Cart button when using browser zooming up to 400%.
- [BCTHEME-362](https://jira.bigcommerce.com/browse/BCTHEME-362)
https://user-images.githubusercontent.com/67792608/108060908-38f9d300-7060-11eb-8697-6f72d0a6c2a5.mp4
https://user-images.githubusercontent.com/67792608/108060915-3a2b0000-7060-11eb-8f8f-8c6f20a8c31e.mov
https://user-images.githubusercontent.com/67792608/108060918-3bf4c380-7060-11eb-88bc-05098b6e9bcc.mov
=> fix(storefront): BCTHEME-362 fix cut off cart button on zooming 400

CHANGELOG.md, assets/scss/components/stencil/navPages/_navPages.scss
Moved padding styles to `.navPage-subMenu-item` which will provide equal distance between dropdown menu categories.
- [BCTHEME-392](https://jira.bigcommerce.com/browse/BCTHEME-392)
https://user-images.githubusercontent.com/67792608/109015446-cb801f00-76bd-11eb-9409-f64c0ef1ae02.mov
https://user-images.githubusercontent.com/67792608/109015468-cfac3c80-76bd-11eb-97d4-4dea7aef5d48.mov
https://user-images.githubusercontent.com/67792608/109032067-fd00e680-76cd-11eb-9beb-6bc247d7a273.mov
=> fix(storefront): BCTHEME-392 fixed line breaks on Dropdown Menu

CHANGELOG.md, templates/components/products/card.html
This PR added unique identifiers  on product cards to make a search of specific product card more convenient.
- [BCTHEME-347](https://jira.bigcommerce.com/browse/BCTHEME-347)
=> fix(storefront): BCTHEME-347 Add unique identifiers to product cards

CHANGELOG.md, templates/components/blog/post.html
The 'read more' link text does not define complete purpose of the link. The blog heading should be associated with it.
[Jira](https://jira.bigcommerce.com/browse/BCTHEME-426)
=> BCTHEME-426: Insufficient link text for "Read More" links

CHANGELOG.md, templates/components/common/subscription-form.html
Screen reader doesn't read 'Your email address' for newsletter sign up as a mandatory edit field as required.
[Jira](https://jira.bigcommerce.com/browse/BCTHEME-422)
=> BCTHEME-422: Announce email field as mandatory

CHANGELOG.md, assets/scss/layouts/header/_header.scss
The "Skip to main content" link is not visible when it receives focus on any page other than the home page.
[Jira](https://jira.bigcommerce.com/browse/BCTHEME-420)
=> BCTHEME-420: 'Skip to main content' is not visible

CHANGELOG.md, lang/en.json, templates/components/cart/content.html
The following button labels should be associated with respective product name:
- Increase quantity
- Decrease quantity
- Remove item from cart
[Jira](https://jira.bigcommerce.com/browse/BCTHEME-427)
=> fix(storefront): BCTHEME-427 Insufficient button label on cart page

CHANGELOG.md, assets/scss/components/stencil/navUser/_navUser.scss
After this PR merged Search input will appear after clicking on top menu Search button 
[BCTHEME-403](https://jira.bigcommerce.com/browse/BCTHEME-403)
=> fix(storefront): IE11 - Clicking on Search Does Not Display Search Bar

templates/components/common/share.html, templates/components/products/product-view.html
Remove 3rd-party dependency on [AddThis](https://www.addthis.com/) which provides social sharing functionality.
Instead, links have been replaced with the native URL formats for each service.
Google+ sharing functionality has been removed, as Google+ no longer exists.
- [STRF-5798](https://jira.bigcommerce.com/browse/STRF-5798)
FYI @bc-as @bigcommerce/themes-team
=> Remove AddThis for social sharing, replace with provider sharing links

CHANGELOG.md, assets/js/theme/common/product-details.js
This PR removes extra horizontal scroll on swatch options and supports changes made in BCTHEME-395. The issue with scroll appears when product options are placed close to Viewport. Its scaled images at this time are visually hidden but take place in DOM  beyond a screen size. This causes a scroll. To fix this behaviour we add a function on loading a page and if the there is no enough space for scale images to be placed we move them to the left part of the screen.
- [BCTHEME-431](https://jira.bigcommerce.com/browse/BCTHEME-431)
There are videos with behaviour on mobiles with iOS and Android platforms
https://user-images.githubusercontent.com/67792608/112800203-04723180-9078-11eb-96a1-79bea9dbdce7.mov
https://user-images.githubusercontent.com/67792608/112800342-31bedf80-9078-11eb-9521-45c9a1 …
=> fix(storefront): BCTHEME-431 remove horizontal scroll on swatch options PDP

CHANGELOG.md, templates/components/faceted-search/facets/hierarchy.html
Category facet does not show product count next to it when the count is `0`.  
In theme file we have a check to show product count for `Category` facet only if it is greater than `0`. Since, for our use case the count is `0`, it's not shown. So, I have removed the `if` block to show the count always. For all other facets we show the count always. Only for `Category` it is different. To keep consistency across all facets this fix is made.
- [ES-2138](https://jira.bigcommerce.com/browse/ES-2138)
_Note: Please use the theme file (`Cornerstone-5.3.0_ES-2138_Fix.zip`) uploaded to ES-2138._ 
Steps:
Login to CP
Navigate to Storefront -> My Themes, upload the theme file & apply it
Follow the steps provided in the ticket 
Observe that product count is shown next to `Category` facet
**After Fix:** …
=> fix(search): ES-2138 fixed count showing issue for category facet

CHANGELOG.md, assets/js/theme/common/models/forms.js
This PR fixes an issue when User could fill in an email address with spaces on creating New Account or Account Settings pages. If the entered email  is not valid(spaces, line breaks and tabs) User can not submit a form. The video how it works now is attached to the main ticket.
- [BCTHEME-349](https://jira.bigcommerce.com/browse/BCTHEME-349)
https://user-images.githubusercontent.com/67792608/113595290-7ed71e80-9641-11eb-9700-49d3b42bea74.mov
https://user-images.githubusercontent.com/67792608/113595438-ad54f980-9641-11eb-9be4-529182ab4983.mov
=> fix(storefront): BCTHEME-349 improve email validation for forms

CHANGELOG.md, config.json, schema.json, schemaTranslations.json, templates/components/common/footer.html
This PR addresses the issue with SSL Site Seal that is described in [BCTHEME-118](https://jira.bigcommerce.com/browse/BCTHEME-118)
Current solution consists from 2 step:
1. we deprecate  previous settings in Page Builder for SSL Seal;
2. add new global region for SSL Site Seal where a html widget can be placed.
- [BCTHEME-445](https://jira.bigcommerce.com/browse/BCTHEME-445)
=> feat(storefront): BCTHEME-445 replace page builder ssl settings with new global region for html widget

CHANGELOG.md, assets/js/theme/common/aria/radioOptions.js
This PR adds extended keyboard support for radio buttons. Such behaviour is based on [W3C](https://www.w3.org/TR/wai-aria-practices/examples/radio/radio-1/radio-1.html) & includes:
- Pressing on right/down arrow keys moves focus and checks the next radio button in the group
- Pressing on left/up arrow keys | moves focus and checks the previous radio button in the group
- [BCTHEME-447](https://jira.bigcommerce.com/browse/BCTHEME-447)
Here you can find a video before and after changes. Moving cross options is made with arrow keys.
https://user-images.githubusercontent.com/67792608/113392996-af4b5e00-939e-11eb-8006-e4ca01ad9eec.mov
https://user-images.githubusercontent.com/67792608/113393127-e1f55680-939e-11eb-9162-1b176a17eff6.mov
=> fix(storefront): BCTHEME-447 extends keyboard support for radio buttons

CHANGELOG.md, assets/js/theme/common/carousel/utils/getActiveSlideInfo.js, assets/js/theme/common/carousel/utils/handleImageAspectRatio.js, assets/js/theme/common/carousel/utils/handleImageLoad.js, assets/js/theme/common/utils/ie-helpers.js, assets/scss/components/stencil/heroCarousel/_heroCarousel.scss
This PR implements improvements for analyzing homepage carousel images in context of their aspect ratio (to scale vertical and square images) and replace failed to laod images with placeholder
[BCTHEME-446](https://jira.bigcommerce.com/browse/BCTHEME-446)
https://user-images.githubusercontent.com/66325265/113266246-bcecdf00-92dd-11eb-8fa3-1d9c070ca454.mov
https://user-images.githubusercontent.com/66325265/113266255-c1b19300-92dd-11eb-883f-83c90f2f724b.mov
=> feat(storefront): BCTHEME-446 Improve performance of analyzing homepage carousel images

CHANGELOG.md, templates/components/amp/css/header.html
This PR has fix for missing Hamburger Menu Icon on Google AMP Pages. It was implemented via background image with svg burger icon. '#' in URLs starts a fragment identifier. '#' was changed to %23. That is the value of escaped '#' character.
[BCTHEME-434](https://jira.bigcommerce.com/browse/BCTHEME-434)
=> fix(storefront): BCTHEME-434 Hamburger Menu Icon missing on Google AMP Pages

CHANGELOG.md, templates/components/common/body.html, templates/pages/account/add-return.html, templates/pages/account/inbox.html, templates/pages/account/orders/all.html, templates/pages/account/returns.html, templates/pages/amp/category.html, templates/pages/auth/account-created.html, templates/pages/blog.html, templates/pages/brand.html, templates/pages/brands.html, templates/pages/cart.html, templates/pages/category.html, templates/pages/compare.html, templates/pages/contact-us.html, templates/pages/errors/403.html, templates/pages/errors/404.html, templates/pages/errors/generic.html, templates/pages/gift-certificate/balance.html, templates/pages/gift-certificate/purchase.html, templates/pages/gift-certificate/redeem.html, templates/pages/page.html, templates/pages/search.html
This PR removes duplicates for main tag on store pages due to using a main tag with elements that have id="main=content".
- [BCTHEME-449](https://jira.bigcommerce.com/browse/BCTHEME-449)
=> fix(storefront): BCTHEME-449 remove main tag duplicates

CHANGELOG.md, assets/js/theme/common/carousel/constants.js, assets/js/theme/common/carousel/index.js, assets/js/theme/common/carousel/utils/activatePlayPauseButton.js, assets/js/theme/common/carousel/utils/analizeSlides.js, assets/js/theme/common/carousel/utils/arrowAriaLabling.js, assets/js/theme/common/carousel/utils/dotsSetup.js, assets/js/theme/common/carousel/utils/getActiveSlideIdxAndSlidesQuantity.js, assets/js/theme/common/carousel/utils/index.js, assets/js/theme/common/carousel/utils/refreshFocus.js, assets/js/theme/common/carousel/utils/tooltipSetup.js, assets/js/theme/global/quick-view.js
This PR implements control of focus behaviour on carousels. Also it has some performance updates that helped to implement correct focus order in all cases (for example on breakpoint event)
[BCTHEME-425](https://jira.bigcommerce.com/browse/BCTHEME-425)
https://user-images.githubusercontent.com/66325265/114144303-db765a00-991d-11eb-82d8-ca6379439619.mov
=> feat(storefront): BCTHEME-425 Incorrect focus order for product carousels

.github/workflow-examples/automatic_deployment_production.yml, .github/workflow-examples/poll_for_changed_configuration.yml
A recent release of stencil-cli broke these GitHub Actions examples, as the CLI arguments now require a channel ID in order to proceed without user interaction.
I am hardcoding this channel ID to `1`, which is the default storefront on every store. This will be the appropriate default for 99% of users for now, and those who wish to update it can adjust their functions accordingly.
=> fix(storefront): DEV-426 Fix GitHub workflows for default storefront

CHANGELOG.md, assets/js/theme/cart.js, assets/js/theme/common/product-details.js, assets/js/theme/global/cart-preview.js, assets/js/theme/global/modal.js, assets/scss/components/stencil/applePay/_applePay.scss, assets/scss/components/stencil/cart/_cart.scss, assets/scss/components/stencil/previewCart/_previewCart.scss
Inline block display for preview cart button styling overrode conditional display of Apple Pay button and resulted in an empty button when Apple Pay was not available. Applied conditional rules used from cart styling to preview cart.
[Jira](https://jira.bigcommerce.com/browse/BCTHEME-325)
Apple Pay disabled 
Apple pay enabled
=> fix(storefront): BCTHEME-325 Apple pay button displaying needs to be fixed

CHANGELOG.md, assets/scss/common/_focus-tooltip.scss, assets/scss/settings/global/color/_color.scss, config.json
@bc-alexsaiannyi @BC-tymurbiedukhin @yurytut1993 @bc-azvierieva 
This PR fixes the problem of low contrast of the tooltip to achieve accessibility AA Complaince. Updated color for tooltip in dark CornerStone theme.
- [BCTHEME-457](https://jira.bigcommerce.com/browse/BCTHEME-457)
Bold(dark) theme:
Light and Warm themes:
=> fix(storefront): BCTHEME-457 Update focus tooltip styles contrast to achieve accessibility AA Complaince

CHANGELOG.md, templates/components/amp/products/product-view-details.html, templates/components/amp/products/reviews.html, templates/components/common/breadcrumbs.html, templates/components/products/price-range.html, templates/components/products/price.html, templates/components/products/product-view.html, templates/components/products/reviews.html, templates/pages/amp/product.html, templates/pages/product.html
This PR changes http://schema.org for https://schema.org. `http://` will be supported for the foreseeable future, but figured why wait for that to be phased out.
- [Schema.org FAQ (#19 Should we write 'https://schema.org' or 'http://schema.org' in our markup?)](https://schema.org/docs/faq.html#19)
- #2038
=> Use https:// for schema markup

assets/js/theme/search.js, templates/pages/search.html
This PR adds announcement of search results on search page after page load
[BCTHEME-423](https://jira.bigcommerce.com/browse/BCTHEME-423)
https://user-images.githubusercontent.com/66325265/113125794-a6804e00-921f-11eb-92d3-20f75c101faf.mov
=> fix(storefront): BCTHEME-423 Search result on search page not notified by screen reader

CHANGELOG.md, config.json, schema.json, schemaTranslations.json
Added paypal banner widgets to page builder
-https://jira.bigcommerce.com/browse/PAYPAL-968
=> feat(payment): PAYPAL-968 added banner widgets to page builder

CHANGELOG.md, assets/js/test-unit/theme/global/modal.spec.js, assets/js/theme/cart.js, assets/js/theme/common/faceted-search.js, assets/js/theme/common/product-details.js, assets/js/theme/global/modal.js, assets/js/theme/global/quick-view.js, assets/js/theme/product.js, assets/scss/components/vendor/sweetalert2/_sweetalert2.scss, templates/components/common/store-logo.html
For now focus trap exists on the most important theme modal. This PR scales this feature for all modals.
[BCTHEME-476](https://jira.bigcommerce.com/browse/BCTHEME-476)
Here are some new examples
https://user-images.githubusercontent.com/66325265/117110766-4dac5400-ad8f-11eb-9ce3-f4915869d38e.mov
https://user-images.githubusercontent.com/66325265/117110778-53a23500-ad8f-11eb-97cb-c2a7643d12d9.mov
https://user-images.githubusercontent.com/66325265/117110834-66b50500-ad8f-11eb-8c02-7f2dc6de0f95.mov
=> feat(storefront): BCTHEME-476 Scale focus trap for all modals

CHANGELOG.md, assets/js/theme/cart.js, templates/pages/cart.html
@BC-tymurbiedukhin @bc-alexsaiannyi @yurytut1993 
This PR fixed the gap of translating the cancel button on cart page inside the modal popup. It is expected that after adding files with translations (for example it.json), translations are applied to the names of the cancel button.
- [BCTHEME-496](https://jira.bigcommerce.com/browse/BCTHEME-496)
=> fix(storefront): BCTHEME-496 Translation Gap: Delete from Cart confirmation popup.

CHANGELOG.md, assets/js/theme/cart.js, lang/en.json, templates/pages/cart.html
This PR adds a translation instead of hard-coded text. 
- [BCTHEME-512](https://jira.bigcommerce.com/browse/BCTHEME-512)
=> fix(storefront): BCTHEME-512 add translation for invalid quantity value error on cart

CHANGELOG.md, assets/js/theme/common/models/forms.js, assets/js/theme/common/product-details.js, assets/js/theme/common/utils/form-utils.js, assets/scss/components/citadel/forms/_forms.scss, assets/scss/components/stencil/productView/_productView.scss, lang/en.json, templates/components/amp/css/form.html, templates/components/products/add-to-cart.html
This PR addresses an issue that appears if product quantity value is incorrect (not digital value). In this case after User clicks on Increase/Decrease button NaN is shown in the field. The problem has been fixed by applying nod validation plugin for this field.
- [BCTHEME-459](https://jira.bigcommerce.com/browse/BCTHEME-459)
Sorry for bad  video quality)
https://user-images.githubusercontent.com/67792608/117249352-18187100-ae4a-11eb-94ee-80fa1d50480f.mov
with Screen Reader:
https://user-images.githubusercontent.com/67792608/117249375-1d75bb80-ae4a-11eb-9b9d-32042d5f124b.mov
=> fix(storefront): BCTHEME-459 fix product quantity change error

CHANGELOG.md, assets/js/theme/account.js, assets/js/theme/brand.js, assets/js/theme/category.js, assets/js/theme/compare.js, assets/js/theme/global/compare-products.js, assets/js/theme/search.js, lang/en.json, templates/components/brand/product-listing.html, templates/components/category/product-listing.html, templates/components/search/product-listing.html
@BC-tymurbiedukhin 
@bc-alexsaiannyi 
@yurytut1993 
It is expected that after adding files with translations (for example it.json), the translations will be applied to the error message that will appear when you select one product and click on the "Compare" button.
- [BCTHEME-490](https://jira.bigcommerce.com/browse/BCTHEME-490)
=> fix(storefront): BCTHEME-490 Translation Gap: Compare products error message

CHANGELOG.md, templates/pages/compare.html
@BC-tymurbiedukhin @yurytut1993 @bc-alexsaiannyi 
It is expected that after adding files with translations (for example **it.json**), translations are applied to the names of the Description, Rating and Availability fields.
- [BCTHEME-492](https://jira.bigcommerce.com/browse/BCTHEME-492)
For example, if the selected language is **Italian**:
and if **english** is selected:
=> fix(storefront): BCTHEME-492 Translation Gap: Compare page fields (Description, Rating and Availability).

CHANGELOG.md, templates/components/amp/common/store-logo.html, templates/components/amp/css/header.html
@BC-tymurbiedukhin @yurytut1993 @bc-alexsaiannyi 
Fixed display of the logo for all screen sizes. Tested on horizontal and vertical logo variations.
- [BCTHEME-479](https://jira.bigcommerce.com/browse/BCTHEME-479)
**Horizontal logo bug**:
**Horizontal logo fixed**:
**Vertical logo bugs**:
**Vertical logo fixed**:
=> fix(storefront): BCTHEME-479 Logo on AMP Product details page (PDP) does not fit header

CHANGELOG.md, assets/scss/components/stencil/productView/_productView.scss, templates/components/products/add-to-cart.html
@bc-alexsaiannyi @BC-tymurbiedukhin @yurytut1993 @bc-azvierieva 
Fixed alignment of "Add to cart" and "Wishlist" buttons on all screen sizes.
- [BCTHEME-477](https://jira.bigcommerce.com/browse/BCTHEME-477)
=> fix(storefront): BCTHEME-477 Add to cart button and Wishlist should be on one line on desktop

CHANGELOG.md, assets/js/theme/cart.js, assets/js/theme/cart/shipping-estimator.js, lang/en.json, templates/components/cart/shipping-estimator.html
@BC-tymurbiedukhin @yurytut1993 @bc-alexsaiannyi 
It is expected that after adding files with translations (for example it.json), translations are applied to the shipping error messages.
- [BCTHEME-535](https://jira.bigcommerce.com/browse/BCTHEME-535)
=> fix(storefront): BCTHEME-535 Translation Gap: Cart -> Shipping estimator error messages.

CHANGELOG.md, assets/js/theme/wishlist.js, lang/en.json, templates/components/account/add-wishlist.html
@BC-tymurbiedukhin @yurytut1993 @bc-alexsaiannyi 
It is expected that after adding files with translations (for example it.json), translations are applied to the error message when creating a new wishlist without a wishlist name.
- [BCTHEME-507](https://jira.bigcommerce.com/browse/BCTHEME-507)
=> fix(storefront): BCTHEME-507 Translation Gap: Account -> Wish List -> Name required message.

CHANGELOG.md, templates/components/products/options/swatch.html
If you create an unrequired Swatch Option on a product, the "None" swatch is automatically added to the page, but is unable to be selected. When selecting "None", the action is ignored and the last valid swatch selection remains.
[Jira](https://jira.bigcommerce.com/browse/BCTHEME-452)
**Production store**
**Localhost**
=> fix(storefront): BCTHEME-452 Unable to select 'None' on unrequired Swatch Options

CHANGELOG.md, templates/components/common/share.html
Facebook social share was returning an error for blog pages, because ?u=`undefined`. getVar and assignVar works as expected, problem was in the url variable, that is undefined.
- [STRF-9126](https://jira.bigcommerce.com/browse/STRF-9126)
=> fix(storefront): STRF-9126 Facebook social share returns an error for blog pages

CHANGELOG.md, assets/js/theme/cart.js
This PR fixes possible shift on option change popup due to different animation speed. (see attached video)
- [BCTHEME-544](https://jira.bigcommerce.com/browse/BCTHEME-544)
https://user-images.githubusercontent.com/67792608/120655899-cdf7cf00-c48b-11eb-8862-8be90a338cb4.mov
https://user-images.githubusercontent.com/67792608/120655916-d0f2bf80-c48b-11eb-99f6-994c1c986236.mov
=> fix(storefront): BCTHEME-544 fix shift on change options modal on cart page

CHANGELOG.md, assets/js/theme/global/quick-view.js, assets/scss/components/stencil/productView/_productView.scss
This PR has fix for squashed slides - now slick activation works only after modal has display block and slick can calculate slide width
[BCTHEME-543](https://jira.bigcommerce.com/browse/BCTHEME-543)
=> fix(storefront): BCTHEME-543 Product images in quick view can be squashed

CHANGELOG.md, templates/components/products/card.html
This PR has fix for accessibility issue of unexpected opening quick view by pressing enter when compare checkbox in focus
[BCTHEME-601](https://jira.bigcommerce.com/browse/BCTHEME-601)
=> fix(storefront): BCTHEME-601 Enter press on Compare checkbox cause quick view opening

CHANGELOG.md
Modify changelog date format to match ISO 8601. Also adds a message with link to keep a changelog to explain why this change was made. Changes draft to unreleased as this is clearer what those changes are.
I'll raise further PRs against the changelog at a later date as there are some releases where the date doesn't match the tag creation date / github release date. I'd like to add the links to the version titles so they can be easily diffed. ~Pre-release versions also aren't recorded at all - unsure if we want to add those?~ Pre-releases aren't added see [here](https://github.com/bigcommerce/stencil-cli/blob/d9c0f3d3febdf4b51ae45a32fb534d726e3729f3/lib/release/release.js#L99)
I don't think this PR needs a changelog entry - that would be a little too meta :)
- …
=> Changelog format changes

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
one of my earlier prs sat for a long time as it was blocked on a changelog entry
this adds this requirement to the contributing documentation and the pr template
this will allow new contributors to make pull requests that meet requirements
and prevent delays
- [PR 1920](https://github.com/bigcommerce/cornerstone/pull/1920)
=> add changelog requirements

CHANGELOG.md, assets/js/theme/common/carousel/utils/getActiveSlideInfo.js, assets/js/theme/common/carousel/utils/handleImageAspectRatio.js, assets/js/theme/common/carousel/utils/handleImageLoad.js, assets/scss/components/stencil/heroCarousel/_heroCarousel.scss, templates/components/carousel-content.html, templates/components/carousel.html
This PR adds update for slide images and buttons so they can be both clickable on the same slide.
Also minor code updates were added to handlers related to slide images.
[BCTHEME-674](https://jira.bigcommerce.com/browse/BCTHEME-674)
=> feat(storefront): BCTHEME-674 Make Hero Carousel both slide and button clickable when button enabled

CHANGELOG.md, assets/js/theme/global/quick-view.js
The issue relates to foundation dropdown lib miscalculation. Due to several  Wishlist’s dropdown on PDP once User makes attempt to open up one of them foundation.dropdown lib captures several ‘instances’ of them and makes calculation of css styles based on wrong ‘instance’. This leads that in quickview modal dropdown menu is separated  from button. As a solution we’ve added listener on foundation dropdown open Event  that rewrites  specific css style on its ‘original’ value. Once User leaves/closes  a Modal we clear our dropdown listener.
- [BCTHEME-708](https://jira.bigcommerce.com/browse/BCTHEME-708)
https://user-images.githubusercontent.com/67792608/127316138-8fca4399-e53b-4589-ad2a-c7d351eb7289.mov
=> fix(storefront): BCTHEME-708 fix wishlist dropdown shift in quickview modal

CHANGELOG.md, templates/components/common/subscription-form.html
Entering in a blank email address in the newsletter field is accepted and takes the customer to a thanks for subscribing page. The redirect with success message is to subscriber.php whereas using a valid email in the field works as expected and redirects to subscriber.php?result=success
[Jira](https://jira.bigcommerce.com/browse/BCTHEME-671)
=> fix(storefront): BCTHEME-671 Empty email input in newsletter field does not trigger an error

CHANGELOG.md, templates/components/amp/products/product-view-details.html
This PR adds functionality to display release date information for pre-order products on AMP pages.
- [BCTHEME-668](https://jira.bigcommerce.com/browse/BCTHEME-668)
=> fix(storefront): BCTHEME-668 Google AMP feature request - Add in release date info for preorder products

CHANGELOG.md, templates/components/account/payment-methods-list.html
As for current realisation, AdyenV2 (ent) customers will not be allowed to edit or add cards at "My Account" -> "Payment Methods" section. However, they are able to see card details and delete cards. That is why we should clarify these circumstances for them.
To do so, we need to add description below "Adyen" name (retrieved from "display_name" at payment method data)
[ADYEN-242](https://jira.bigcommerce.com/browse/ADYEN-242)
**Before:**
**After:**
=> feat(payment): ADYEN-242 Added notice to Adyen vaulted cards at My account page

CHANGELOG.md, assets/scss/components/stencil/heroCarousel/_heroCarousel.scss
This PR adds style updates for correct positioning of carousel placeholder which appears if slide image failed to load
[BCTHEME-856](https://jira.bigcommerce.com/browse/BCTHEME-856)
=> fix(storefront): BCTHEME-856 Fixed images placeholder on hero carousel shifted on mobile when slide has content

CHANGELOG.md, assets/scss/layouts/footer/_footer.scss, templates/components/common/geotrust-ssl-seal.html
This PR has fix for flickering text content color when sliding carousel.
Also geotrast component and its related styles were removed here as they already not in use.
[BCTHEME-855](https://jira.bigcommerce.com/browse/BCTHEME-855)
https://user-images.githubusercontent.com/66325265/133618925-3c3588c4-9221-47fd-857b-430e200c3ba7.mov
https://user-images.githubusercontent.com/66325265/133618957-ff70794b-9aa0-42ed-a9a1-eac72f197acc.mov
=> fix(storefront): BCTHEME-855 Sliding carousel with products cause footer headers flickering

CHANGELOG.md, assets/js/theme/cart.js, templates/components/cart/additional-checkout-buttons.html, templates/pages/cart.html
This PR relates to an issue with additional checkout buttons that should disappear on applying 100% discount coupon and assists [PR](https://github.com/bigcommerce/bigcommerce/pull/42616) from PayPal Team.
- [PAYPAL-1058](https://jira.bigcommerce.com/browse/PAYPAL-1058)
=> fix(storefront): BCTHEME-355 fix additional checkout buttons

CHANGELOG.md, assets/js/theme/global/quick-search.js
The low debounce time on the search query is causing the search api to be hit after every character. Bump up the debounce time to lessen the frequency. 
https://jira.bigcommerce.com/browse/ES-2439
N/A
=> fix(search): ES-2439 change debounce wait time for search

CHANGELOG.md, assets/scss/components/stencil/productView/_productView.scss
This PR has fix for cutted outline of product images inslide slick slider.
[BCTHEME-851](https://jira.bigcommerce.com/browse/BCTHEME-851)
Also while fixing this issue another bug was found - in some cases page can jump when user click on product images on PDP (which can be wrapped by slick). [BCTHEME-894](https://jira.bigcommerce.com/browse/BCTHEME-894) was created and resloved here. 
https://user-images.githubusercontent.com/66325265/134634899-9a00beb4-8855-40e7-a7f1-5bbfd8ce773d.mov
https://user-images.githubusercontent.com/66325265/134634925-408649d2-ba53-4eab-817f-63a9a1d4dc26.mov
=> fix(storefront): BCTHEME-851 Product images on PDP has clipped outline

CHANGELOG.md, templates/components/common/store-logo.html
Update logo to use `srcset` to make sure the logo looks good at all screen sizes and pixel densities.
- [STRF-9454](https://jira.bigcommerce.com/browse/STRF-9454)
=> Use srcset for store logo so it looks good in more conditions

CHANGELOG.md, templates/components/common/navigation.html
This PR fixes the display of the currency dropdown.
- [BCTHEME-936](https://jira.bigcommerce.com/browse/BCTHEME-936)
=> fix(storefront): BCTHEME-936 Cannot see currency dropdown in storefront

CHANGELOG.md, assets/js/theme/global.js, config.json, schema.json, schemaTranslations.json, templates/layout/base.html
This PR removes setting Admin Bar from Cornerston because that setting will actually not do anything currently and is not controlled by the Theme anymore.
- [BCTHEME-912](https://jira.bigcommerce.com/browse/BCTHEME-912)
=> fix(storefront): BCTHEME-912 Admin Bar displays regardless of setting

CHANGELOG.md, templates/components/amp/products/product-view-details.html, templates/components/amp/products/reviews.html, templates/components/common/breadcrumbs.html, templates/components/products/price-range.html, templates/components/products/price.html, templates/components/products/product-view.html, templates/components/products/quick-view.html, templates/components/products/reviews.html, templates/components/products/schema.html, templates/pages/amp/product-options.html, templates/pages/amp/product.html, templates/pages/product.html
The LD+JSON approach to schema.org data has been widely used for years now. It offers a much clearer, more concise way of providing the data necessary for Rich Results to search engines, such as Google. 
This change cleans up some of the bugs with the existing microdata, such as the description starting with "Description 1 Review", the author being invalid in product reviews, and a missing "priceValidUntil" field. It also adds the number to the gtin field, making it more specific (IE. "gtin12" instead of just "gtin").
More importantly, it separates the microdata from the product content, allowing for users to edit their site's code without having to worry about breaking the delicate data structure. 
Lastly, it makes editing the actual structured data very easy. For example, if a merchant …
=> Replace schema microdata with LD+JSON tag

CHANGELOG.md, package-lock.json, package.json
This PR updates stencil-utils package to v.6.11.0.
- [BCTHEME-965](https://jira.bigcommerce.com/browse/BCTHEME-965)
=> fix(storefront): BCTHEME-965 Update stencil-utils package.

CHANGELOG.md, templates/components/blog/post.html, templates/pages/blog-post.html
Blog posts should use an H1 tag for a page header.
https://github.com/bigcommerce/cornerstone/issues/2178
=> Update blog component to use H1 tags on posts

CHANGELOG.md, assets/js/theme/common/product-details.js, assets/js/theme/global/currency-selector.js
This PR fixes a bug that did not update the currency in the cart the first time changed currency.
- [BCTHEME-1006](https://jira.bigcommerce.com/browse/BCTHEME-1006)
https://user-images.githubusercontent.com/83779098/160631189-23c52ddf-10df-42b9-8654-ed42de2ab68d.mov
https://user-images.githubusercontent.com/83779098/160631163-1d71eef6-4c20-4789-845f-e8c7c1ea288d.mov
=> fix(storefront): BCTHEME-1006 When price list price is set for currency, the cart does not respect product's price

CHANGELOG.md, lang/de.json, lang/es-419.json, lang/es-AR.json, lang/es-CL.json, lang/es-CO.json, lang/es-LA.json, lang/es-MX.json, lang/es-PE.json, lang/es.json, lang/fr.json, lang/it.json, lang/nl.json, lang/pt-BR.json, lang/pt.json, lang/sv.json
#2191 left behind some translations that are triggering warnings.
```
Warning: file: /Users/matt/Work/master/creativesafetysupply.com/lang/en.json doesn't have admin.maintenance_header, which is present in /Users/matt/Work/master/creativesafetysupply.com/lang/de.json
Warning: file: /Users/matt/Work/master/creativesafetysupply.com/lang/en.json doesn't have admin.maintenance_tooltip, which is present in /Users/matt/Work/master/creativesafetysupply.com/lang/de.json
Warning: file: /Users/matt/Work/master/creativesafetysupply.com/lang/en.json doesn't have admin.maintenance_showstore_link, which is present in /Users/matt/Work/master/creativesafetysupply.com/lang/de.json
Warning: file: /Users/matt/Work/master/creativesafetysupply.com/lang/en.json doesn't have admin.prelaunch_header, which is …
```
=> Remove translations for adminBar component

CHANGELOG.md, assets/js/theme/account.js
This PR makes changes that allow to prevent form submission and inform the user that the Country field must be selected.
- [BCTHEME-961](https://jira.bigcommerce.com/browse/BCTHEME-961)
https://user-images.githubusercontent.com/83779098/162431635-1e60565c-7b1b-45f0-a9bb-b32dab4ce9c5.mov
https://user-images.githubusercontent.com/83779098/162431622-fbace46a-e872-4057-becf-c88f34aee5de.mov
=> fix(storefront): BCTHEME-961 Stored Payment Methods form can be submitted without selecting a Country

.github/workflow-examples/automatic_deployment_production.yml, .github/workflow-examples/poll_for_changed_configuration.yml, .github/workflows/pull_request_review.yml
Bump the GitHub Actions bundled with the theme to use node 14 to support latest CLI versions.
=> Bump GitHub Actions to use node 14

CHANGELOG.md, lang/da.json, lang/no.json
https://github.com/bigcommerce/cornerstone/pull/2204 
`da.json` and `no.json` language files have an object for the admin bar component no longer present in Cornerstone, which created some warnings when starting a local dev server.
=> Remove adminBar translations from da/no lang files

CHANGELOG.md, templates/layout/empty.html
"The LANG tag (i.e. the lang="" attribute) is designed to signal screen readers pronunciation engines to switch to another language. For this reason [ tagging Web text as being in a particular language is required in WCAG 2.0 ]"(https://accessibility.psu.edu/foreignlanguages/langtaghtml/ )
- ✅  CHANGELOG.md entry added (required for code changes only)
- [BCTHEME-1103](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1103)
=> feat(bctheme): BCTHEME-1103  Add lang attribute to html tag in checkout

CHANGELOG.md, templates/components/products/options/product-list.html
When using a Product Pick List _without images_, the **None** option will not be selected by default if the option is unrequired.
- [BCTHEME-1110](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1110)
Proof of fix:
=> fix(storefront): BCTHEME-1110 Product Pick List "none" is not selected by default without images

CHANGELOG.md, templates/pages/blog.html
This PR adds Link Rel Next/Prev Tags to the blog page. 
The links of the `<link>` tag are not hyperlinks, they cannot be clicked, and the `<link>` element itself contains only attributes that indicate a link to some external document. They play a big role in promoting websites or blogs.
**Tickets / Documentation**
- [BCTHEME-1014](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1014)
=> fix(storefront): BCTHEME-1014 Blog Pages Do Not Include Link Rel Next/Prev Tags

CHANGELOG.md, config.json, templates/components/account/payment-methods-list.html
Adds the ability to display stored bank accounts in the Payment Methods section.
- [INT-5290](https://bigcommercecloud.atlassian.net/browse/INT-5290)
=> fix(payments): INT-5290 Fix Payment Methods to show stored Bank Accounts

CHANGELOG.md, templates/components/common/small-paginator.html
The pagination enumeration text at the bottom of the customer account orders page displays innacurately once there are 7 or more pages of orders. This is because the pagination.links does not always return the total list of pages which is expected, so we cannot rely on the length of that array as indicator for the total pages. Instead we will return a horizontal list of page numbers which are links to the corresponding page of orders. 
- [BCTHEME-1077](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1077?filter=-3)
Before: Notice the unexpected page count behavior
https://user-images.githubusercontent.com/5630999/181863853-8dfc2673-189f-41d8-8849-b16abd58f167.mp4
After: More control and clarity for the user …
=> fix(storefront): BCTHEME-1077 clarify customer order pagination

assets/scss/components/foundation/dropdown/_dropdown.scss, assets/scss/components/stencil/productView/_productView.scss, templates/components/amp/products/product-options.html, templates/components/common/wallet-buttons.html, templates/components/products/add-to-cart.html, templates/components/products/product-view.html
Added wallet buttons component for product details and quick view to add customers an ability to use apple pay, paypal etc. to speed up purchase process
- [PAYPAL-1579](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1579)
Customer will see the same component for both Product details Page and Quick view:
=> feat(payment): PAYPAL-1579 added wallet buttons component for product details and quick view

CHANGELOG.md, templates/pages/auth/account-created.html
This PR fixed escaping on created store account confirm message
[BCTHEME-1185](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1185)
=> fix(storefront): BCTHEME-1185 fixed escaping on created store account confirm message

CHANGELOG.md, templates/components/common/header.html
Currently, it's not possible to add a widget to a global region within the header. The only available region is `header_bottom--global`. This is in the header template so is on all pages but is actually outside of the <header> element so may be styled differently resulting it feeling like it's below the header, not at the bottom of the header.
As an app developer, I would like to request at least one global region be added inside the header.
Happy for this to be a discussion on the best way to do this and it's appropriate to add further global regions too, e.g. top of this file as an alternative to banners.
TBC
=> Add global region at the bottom of the navigation

CHANGELOG.md, package-lock.json, package.json
- Fixes to focus
- A performance boost for $.trim
https://blog.jquery.com/2021/03/02/jquery-3-6-0-released/
https://blog.jquery.com/2022/08/26/jquery-3-6-1-maintenance-release/
https://github.com/jquery/jquery/pull/5068
=> Bump jQuery to 3.6.1

CHANGELOG.md, assets/js/theme/common/faceted-search.js, assets/js/theme/common/nod-functions/min-max-validate.js, assets/js/theme/common/product-details-base.js, assets/js/theme/common/state-country.js, assets/js/theme/common/utils/form-utils.js
To help reduce the size of the bundle, I've removed the usage of `each`, `includes`, `isNaN`, `isNumber`, and `isObject`.
- assets/js/theme/common/faceted-search.js - `includes`
- assets/js/theme/common/product-details-base.js - `isObject` and `isNumber`
- assets/js/theme/common/state-country.js - `each`
- assets/js/theme/common/nod-functions/min-max-validate.js - `isNaN`
- assets/js/theme/common/utils/form-utils.js - `includes`
https://github.com/bigcommerce/cornerstone/issues/2163#issuecomment-1021373765
https://youmightnotneed.com/lodash
**BEFORE**
**AFTER**
=> Reduce lodash usage

CHANGELOG.md, package-lock.json, package.json
Bump stencil utils with fixed to broken add to cart and remove from cart ajax calls
- [STRF-10066](https://bigcommercecloud.atlassian.net/browse/STRF-10066)
https://user-images.githubusercontent.com/68893868/189340865-283ee913-0b83-4f0b-9fa7-89fbe2d1b448.mov
=> fix(storefront): STRF-10066 Fix broken add to cart button

CHANGELOG.md, config.json, schema.json, schemaTranslations.json
1) Added for `Products` checkbox `Show quick payment buttons`
2) Changed some translations
3) Added configuration for quick payment button sorting
4) Added subsections to show conditionally for the following groups of providers:
- PayPal PayLater
- PayPal APMs
- Google Pay
- Apple Pay
- Amazon Pay
- AfterPay
- Masterpass
- related PR https://github.com/bigcommerce/bigcommerce/pull/46248 should be merged first
In scope of the Epic: https://bigcommercecloud.atlassian.net/browse/PROJECT-4529 - Wallet Payment Buttons on the Product Detailed Page
https://bigcommercecloud.atlassian.net/browse/PAYPAL-1345
@bigcommerce/themes-team @bigcommerce/kyiv-payments-team
=> feat(payments): PAYPAL-1480 adding button settings to the page builder

CHANGELOG.md, config.json, lang/en.json, schema.json, schemaTranslations.json, templates/components/amp/products/card.html, templates/components/amp/products/product-view.html, templates/components/cart/content.html, templates/components/cart/preview.html, templates/components/cart/totals.html, templates/components/common/cart-preview.html, templates/components/common/navigation.html, templates/components/products/add-to-cart.html, templates/components/products/card.html, templates/components/products/list-item.html, templates/components/products/product-info.html, templates/components/products/product-view.html, templates/pages/cart.html, templates/pages/compare.html
This PR will remove the "restrict_to_login" theme configuration and replace it with the server-side "hide_price_from_guests" setting. This functionality is hidden behind the `Feature_HidePriceFromGuestsSetting` feature flag, so we will need coordination when this will be released in a new Cornerstone update on the marketplace.
- [STRF-9829](https://bigcommercecloud.atlassian.net/browse/STRF-9829)
**Channel Storefront Setting:**
**Product Cards:**
**Product Page:**
**Cart Page (if user creates cart while logged in and then logs out):**
ping @bigcommerce/themes-team
=> feat(storefront): STRF-9829 Migrate Cornerstone to new "Hide Price From Guests" functionality

CHANGELOG.md, assets/js/theme/common/product-details-base.js, templates/components/products/add-to-cart.html
Made PDP wallet buttons container hidden in cases when the product is not purchasable or out of stock
- [PAYPAL-1682](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1682)
=> feat-payment): PAYPAL-1682 hide PDP wallet buttons container when the product is not purchasable or out of stock

CHANGELOG.md, assets/js/theme/common/product-details.js
Made initial product details data update if the form is valid on page load. We have a case, when the form is valid by itself, but we don't have product details data to create 'Buy Now' cart for wallet buttons. This PR fixes the issue.
- [PAYPAL-1720](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1720)
Before:
After:
=> fix(payment): PAYPAL-1720 made initial product details data update if the form is valid on page load

CHANGELOG.md, templates/layout/base.html
Update the key render-blocking resources in `base.html` to be tagged as preloadable; this will result in [preload headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link) being sent for these resources.
Furthermore, when the Stencil storefront is behind Cloudflare, this will result in [HTTP 103 Early Hints](https://blog.cloudflare.com/early-hints/) being sent when appropriate, which can result in significant performance improvements for some clients.
Limiting this to only the most important, render-blocking resources for right now, as there is probably a point of diminishing returns or even nullifying the benefit if too many resources are tagged.
Outside of the theme, some Scripts in the Script Manager will also be preloaded.
- …
=> Update key assets with preload headers

CHANGELOG.md, assets/js/theme/account.js, assets/js/theme/auth.js
The configuration `delay:0` was originally added so that the page would focus/scroll to the earliest error. A validation may be returned after the page starts to scroll/focus to the earliest error and interrupt the scroll/focus. See https://github.com/bigcommerce/cornerstone/pull/2230#issuecomment-1181596748 
However, some merchants have reported that the instant validation is undesired because the user is not given a chance to complete the text input before being validated. From an accessibility standpoint this can cause confusion for some users. The default delay is .7 seconds - https://github.com/casperin/nod#delay - but this still seems pretty fast to me considering the merchant report, so I've changed it to .9.
The timeout gives all the validations a chance to be returned before …
=> fix(storefront): BCTHEME-1213 prevent immediate validation

CHANGELOG.md, config.json
`Show quick payment buttons` to True by default. 
- [PAYPAL-1781](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1781)
=> feat(payments): PAYPAL-1781 Set Show PDP setting to true by default

CHANGELOG.md, assets/js/theme/account.js, templates/pages/account/add-payment-method.html
Initialization of storefront-account-payments when experiment is on.
It initializes storefront-account-payments library when experiment is on, when experiment is off it renders default vaulting form.
[bcapp PR](https://github.com/bigcommerce/bigcommerce/pull/50179)
[library pr ](https://github.com/bigcommerce/storefront-account-payments/pull/1)
- [ADYEN-314](https://bigcommercecloud.atlassian.net/browse/ADYEN-314)
https://user-images.githubusercontent.com/79574476/205093421-a3712782-aec5-41e6-822d-349df4d4a6d6.mov
=> feat(payment): ADYEN-314 vaulting lib initialization

CHANGELOG.md, package-lock.json, package.json
Bumping stencil utils with BODL features and added /graphql-render endpoint
- [Stencil Utils Release items](https://github.com/bigcommerce/stencil-utils/releases/tag/6.13.0)
=> Bump Stencil Utils to 6.13.0

CHANGELOG.md, templates/components/account/order-contents.html
This PR fixes displaying shipping details in order details.
- [BCTHEME-1366](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1366)
[BCTHEME-1366]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront)L: BCTHEME-1366 Customer order summary with both physical and digital items shows shipping as null

CHANGELOG.md, templates/components/account/order-contents.html, templates/components/account/payment-methods-list.html, templates/components/cart/content.html, templates/components/common/currency-selector.html, templates/components/common/navigation-dropdown.html, templates/components/common/navigation-list-alternate.html, templates/components/common/navigation-list.html, templates/components/common/navigation-menu.html, templates/components/common/paginator.html, templates/components/common/payment-icons.html, templates/components/common/share.html, templates/components/common/small-paginator.html, templates/components/common/social-links.html, templates/components/common/wishlist-dropdown.html, templates/components/faceted-search/faceted-search-navigation.html, templates/components/faceted-search/facets/multi.html, templates/components/faceted-search/index.html, templates/components/faceted-search/selected-facets.html, templates/components/products/add-to-cart.html, templates/components/products/ratings.html, templates/pages/account/add-payment-method.html, templates/pages/compare.html
This PR refactors SVG use & removes `xlink:href` in favour to `href`. It's done according to the fact that SVG 2 [removed](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href) the need for the xlink namespace and `xlink:href` was deprecated. `xmlns` attribute is already presented on svg sprite which is [required](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg) by specs. 
- [BCTHEME-34](https://bigcommercecloud.atlassian.net/browse/BCTHEME-34)
- ...
[BCTHEME-34]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefont): BCTHEME-34 refactor svg attributes

CHANGELOG.md, templates/components/products/card.html, templates/components/products/list-item.html
This PR fixes appearance for Sold-out badges for tracking inventory on Product vs Variant levels.
- [BCTHEME-1171](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1171)
https://user-images.githubusercontent.com/67792608/214821866-f91c1c1d-473b-450d-b2a2-3d2e1ca16654.mov
[BCTHEME-1171]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront): bctheme-1171 fix sold-out badge appearance

CHANGELOG.md, assets/js/theme/common/product-details-base.js, lang/da.json, lang/de.json, lang/en.json, lang/es-419.json, lang/es-AR.json, lang/es-CL.json, lang/es-CO.json, lang/es-LA.json, lang/es-MX.json, lang/es-PE.json, lang/es.json, lang/fr.json, lang/it.json, lang/nl.json, lang/no.json, lang/pt-BR.json, lang/pt.json, lang/sv.json, templates/components/products/product-view.html
This PR fixes form.serialize() when changing product options.
After discussing with @vdm-kr, it was decided to get rid of the disabled attribute for the unavailable product option in the dropdown, since the user cannot switch between such options.
For an unavailable option, a corresponding message will be added to the select options.
- [BCTHEME-1184](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1184)
Bug:
https://user-images.githubusercontent.com/82589781/216034839-0c743930-1b67-47b1-ade0-7cf193f42905.mov
Fix:
https://user-images.githubusercontent.com/82589781/216038001-1a89155f-0ff1-40ff-9970-cd998278bb89.mov
[BCTHEME-1184]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront): BCTHEME-1184 form.serialize() ignores dropdown option elements that have the disabled attribute

CHANGELOG.md, lang/en.json, templates/pages/account/add-return.html
This PR fixes translation gap "Submit Return Request" button.
- [BCTHEME-1112](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1112)
Bug:
Fix:
[BCTHEME-1112]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront): BCTHEME-1112 Translation Gap: Submit Return Request button

CHANGELOG.md, assets/js/theme/global/modal.js
This PR fixes styles that applies to page after previewing Gift certificate.
- [BCTHEME-1346](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1346)
Bug:
https://user-images.githubusercontent.com/82589781/217244367-c89b4e38-7510-4fb2-b691-1292f3fa01cc.mov
Fix:
https://user-images.githubusercontent.com/82589781/217244416-e0b2d1ee-8a37-4563-99e0-9a4c425bb4dd.mov
[BCTHEME-1346]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront): BCTHEME-1346 Gift certificate CSS properties are applied to page after previewing Gift certificate on storefront

CHANGELOG.md, templates/components/products/add-to-cart.html
This PR fixes a bug with the display of the product quantity on the PDP
[- BCTHEME-1461](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1461)
Before:
After:
=> fix(storefront): BCTHEME-1461 A bug with the display of the product quantity on the PDP

CHANGELOG.md, assets/scss/components/stencil/applePay/_applePay.scss
Added classes for applepay button
https://bigcommercecloud.atlassian.net/browse/PAYPAL-2195
=> feat(payment): PAYPAL-2195 added classes for applepay button

CHANGELOG.md, templates/components/products/schema.html
Updates the `description` in the schema.org product schema to remove url encoding. This schema is output into a "rich snippet" script on the PDP which is used by 3rd party platforms for accessing product details in a consistent way.
The url encoding was resulting in undesired encoded characters showing up in places the description was used, like when linking a product to pinterest.
For example, I setup a product with a description that resulted in this value being printed into the HTML of the page:
```
"description": "Who%20doesn&#x27;t%20like%20a%20sugar%20skull%3F%0ATesting%20if%20I%20can%20break%20the%20output%20by%20adding%20a%20quote%20-%26gt%3B%20%22%22and%20single%20quote%20-%26gt%3B%20&#x27;%0Aand%20closing%20curly%20brace%20-%26gt%3B%20%7D%0Aand%20opening%20curly%20brace%20-%26gt% …
```
=> fix(storefront): STRF-10416 - Remove URL Encoding from Description in the Product Schema

CHANGELOG.md, templates/components/cart/content.html
This PR removes the "Change" button in the cart where other variations can be selected (but can't be saved). Selecting another variation doesn’t change the cart and the rule but confuses customers.
After setting up a promotion, the "Change" button is not needed, because it leads customers to misunderstand the promotion.
- [BCTHEME-1240](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1240)
Before
https://user-images.githubusercontent.com/83779098/233063726-1a7ab73c-1a63-4a50-9376-157c0485b268.mov
After
https://user-images.githubusercontent.com/83779098/233063762-6c0c0064-b70c-4039-8663-9847ac8ace17.mov
=> fix(storefront): BCTHEME-1420 If the gift is a variant, the button Change shows in cart, and other variant are visible

CHANGELOG.md, config.json, schema.json, schemaTranslations.json
Add ability to configure Bolt smart payment button on product details page
• [BOLT-576](https://bigcommercecloud.atlassian.net/browse/BOLT-576)
[BOLT-576]: https://bigcommercecloud.atlassian.net/browse/BOLT-576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(payment): BOLT-576 Add Bolt SPB support to cornerstone

CHANGELOG.md, templates/components/common/forms/multiline.html
Extra spaces are added to the `<textarea>` input in the multiline form component: `components/common/forms/multiline.html`
You can see this in the "Write a Review" modal "Comments" input box on the [Cornerstone demo store](https://cornerstone-light-demo.mybigcommerce.com/all/canvas-laundry-cart/)
This looks like same issue fixed in: [fix(storefront): STRF-4497 Removed default whitespace in textarea product option.](https://github.com/bigcommerce/cornerstone/pull/1222), and it can be fixed the same way.
Relevant PR's: https://github.com/bigcommerce/cornerstone/pull/1222
=> fix(storefront): Remove default whitespace from multiline input

CHANGELOG.md, assets/js/theme/cart.js
When a cart has both free gift products and standard products and all standard products are removed the cart page does not refresh to the “cart is empty” message and just shows a cart with no products in it.
- [CHECKOUT-7213](https://bigcommercecloud.atlassian.net/browse/CHECKOUT-7213)
cc @bigcommerce/checkout 
[CHECKOUT-7213]: https://bigcommercecloud.atlassian.net/browse/CHECKOUT-7213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(checkout): CHECKOUT-7213 refresh cart page if no item in the cart

CHANGELOG.md, templates/components/products/card.html, templates/components/products/list-item.html
We revert this PR since it added 2 bugs - BCTHEME-1473, 1481. The issue related to the fact that currently we don’t have an appropriate flag that shows if a product can be purchasable or not on PLP (screenshot#1). For instance, we have `can_purchase` flag for this purpose in PDP. Previously `show_cart_action` has been used in PLP according to our docs (screenshot#2).
- [BCTHEME-1171](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1171)
- [BCTHEME-1473](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1473)
- [BCTHEME-1481](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1481)
[BCTHEME-1171]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BCTHEME-1473]: …
=> fix(storefront): BCTHEME-1473 reverting PR for BCTHEME-1171

CHANGELOG.md, assets/js/polyfills.js, templates/layout/base.html, webpack.common.js
This pr is a fix for correct processing of invalid formData in iOS Safari 11.2. Two issues were covered here:
1. When formData is invalid but exists - polifill do not work, so additional checks were added to detect such browsers, like iOS 11.2 Safari
2. FormData polyfill should run after whatwg-fetch to correctly update fetch that should convert formData like object into blob. That is the reason why correctly collected formData object was unclear for server. So formData polyfill should run after whatwg-fetch declared in stencil-utils. It goes with main bundle so after main loaded formData polyfill can be added to the browser 
- [BCTHEME-1678](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1378)
https://github.com/bigcommerce/cornerstone/assets/66325265/48600629-6a2a-41b4-8704-b1f0b0 …
=> fix(storefront): BCTHEME-1378 fix add product to cart on iphone x (iphone version 11)

CHANGELOG.md, templates/components/cart/totals.html
change cart page template to display fees on cart page
- [CHECKOUT-7557](https://bigcommercecloud.atlassian.net/browse/CHECKOUT-7557)
- 
after change
[CHECKOUT-7557]: https://bigcommercecloud.atlassian.net/browse/CHECKOUT-7557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
ping @bigcommerce/team-checkout
=> feat(checkout): CHECKOUT-7557 display fees on cart page

CHANGELOG.md, templates/components/products/product-view.html
Displaying the Hidden Cart Source Input Field on PDP page
The "Add to Cart" button on the PDP page initiates a call to the remote/v1/add endpoint for adding items to the cart. To facilitate the creation of a cart with the order source set to 'buyButton,' it will display the hidden cart source input field, enabling the posting of the cart source value to the endpoint.
Here are all the scenarios related to determining whether the order source needs to be set as "buy_button." This PR is specifically focused on addressing scenario 5.
  | Scenario | Redirect To | Is set order source buy button?
-- | -- | -- | --
1 | Not cart in the session | Checkout | Yes
2 | A cart in the session | Checkout | No
3 | Not cart in the session | Cart | No (to change Yes in another PR)
4 | A cart in the session | …
=> feat(checkout): CHECKOUT-7176 Displaying the Hidden Cart Source Input Field on PDP page

CHANGELOG.md, schemaTranslations.json
Updating page builder menu items text to be in the correct case. Also replacing "&" with "and".
Before:
After:
=> fix(storefront): PSE-868 Pagebuilder menu items are in the wrong case

CHANGELOG.md, assets/scss/components/stencil/productView/_productView.scss, templates/components/products/add-to-cart.html
This PR fixes pre-orded text in Polish.
- [BCTHEME-1710](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1710)
**before**:
https://github.com/bigcommerce/cornerstone/assets/82589781/29f8ac33-1372-42d4-902e-ebe7da21eb1a
**after**:
https://github.com/bigcommerce/cornerstone/assets/82589781/4d2fad93-8028-47ba-8351-f6bc6b667a4f
[BCTHEME-1710]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront): BCTHEME-1710 Pre-Orded text in Polish looks cropped in the button on Product page

CHANGELOG.md, assets/js/theme/common/faceted-search.js
**What?**
This PR fixes a bug related to anchor links on category pages when product filtering is enabled.
**Tickets / Documentation**
- [BCTHEME-1757](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1757)
**Screenshots / Screen Recording**
**Before**
https://github.com/bigcommerce/cornerstone/assets/83779098/c17e3ef0-7726-46bf-85e4-447d9ec225a0
**After**
https://github.com/bigcommerce/cornerstone/assets/83779098/d206cadb-f7c9-421d-97f7-efb633c19131
[BCTHEME-1757]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront): BCTHEME-1757 Anchor links on category pages are not working when product filtering is enabled

CHANGELOG.md, templates/pages/category.html
This pull request corrects an HTML markup error introduced in https://github.com/bigcommerce/cornerstone/pull/2425 on the product listing page by fixing mismatched closing tags. It ensures the main element is properly closed with **`</main>`** and the div element encapsulating the "category_below_content" region closes with **`</div>`**.
=> Fix HTML markup for product listing and below content region

CHANGELOG.md, templates/components/cart/coupon-input.html, templates/components/cart/gift-certificate-input.html
This PR adds appropriate aria attributes to each element that controls expandable content that are specified by screen reader.
- [BCTHEME-1769](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1769)
https://github.com/bigcommerce/cornerstone/assets/82589781/aaf3aa3a-c3dd-4af2-8df8-ab9fcf179307
[BCTHEME-1769]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront): BCTHEME-1769 ADA Compliance - Expandable items should be read by screen reader

CHANGELOG.md, templates/components/cart/coupon-input.html, templates/components/cart/gift-certificate-input.html
Smal fix for [BCTHEME-1769](https://github.com/bigcommerce/cornerstone/pull/2422)
This PR adds translations to accessibility attributes for Coupon Code and Gift Certificates
[BCTHEME-1769]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront): BCTHEME-1769-2 ADA Compliance - Add translations to accessibility attributes for Coupon Code and Gift Certificates

CHANGELOG.md, config.json
This PR removes the **Cart Suggested Products** feature from the Cornerstone page in the Theme Marketplace
**Tickets / Documentation**
- [BCTHEME-1796](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1796)
[BCTHEME-1796]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront): BCTHEME-1796 Page Suggested Items still listed on Cornerstone

templates/components/products/product-info.html
Both a leading and trailing quote are already present in the code that calls this template, so this trailing " breaks the HTML. If you look at the source in the demo theme you'll see this behavior https://cornerstone-light-demo.mybigcommerce.com/shop-all/garden/
=> Extra quote mark

CHANGELOG.md, assets/scss/components/stencil/paymentMethods/_paymentMethods.scss
Added min-height for vaulted payment methods
Before:
After:
=> feat(payment): PAYPAL-3991 added min-height for vaulted payment methods

CHANGELOG.md, assets/js/theme/account.js, package-lock.json
line 414 of account.js should have a template literal
- ...
=> account.js template literal fix

CHANGELOG.md, templates/pages/account/add-address.html, templates/pages/account/addresses.html
The main body content of the Account Address pages flows outside the main body container:
This is happening because there is negative margin on `.account-body` but there is no padding to compensate for it. Some of the account pages([for example, orders/all.html](https://github.com/bigcommerce/cornerstone/blob/51750148ecc1158465328b0d7a128a6c3e697434/templates/pages/account/orders/all.html#L22)) use a wrapper element with class `account-content` to compensate for this negative margin, so I suggested doing the same on add-address.html and addresses.html.
Note: other account pages don't use the `account-content` class, and instead compensate for the negative margin by adding padding to other elements.
- [ X] CHANGELOG.md entry added (required for code changes only)
n/a
Current state:
Fixed:
=> fix(storefront): Prevent flow outside page container on account pages

CHANGELOG.md, templates/components/cart/preview.html
Remove `remote_api_scripts` from cart preview template which fixes duplicating `addToCart` event for Meta Pixel integration.
Previously we've added it to fix the legacy (UA) Google Analytics integration without realising it's duplicating Meta Pixel event. Since the legacy Google Analytics is sunset now, it's not a concern anymore, so it's safe to remove these scripts.
[DATA-11867](https://bigcommercecloud.atlassian.net/browse/DATA-11867)
PR where the issue was initially introduced: https://github.com/bigcommerce/cornerstone/pull/2281
- Manually tested on dev store. Verified that only one `addToCart` event is firing now when I adding a product from PDP or QuickView product form
[DATA-11867]: https://bigcommercecloud.atlassian.net/browse/DATA-11867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …
=> fix: DATA-11867 Fix duplicating add_to_cart meta pixel events

CHANGELOG.md, assets/js/theme/account.js, assets/js/theme/auth.js, assets/js/theme/cart.js, assets/js/theme/catalog.js, assets/js/theme/category.js, assets/js/theme/common/aria/radioOptions.js, assets/js/theme/common/carousel/utils/refreshFocus.js, assets/js/theme/gift-certificate.js, assets/js/theme/global/modal.js, assets/js/theme/search.js
This pull request addresses the usage of deprecated jQuery methods `.focus()`, as well as the binding of `.change()` and `.click()` for event listeners. The changes consolidate the event handlers into a single on-method call, improving the code's readability.
=> Address deprecated jQuery methods

CHANGELOG.md, assets/js/theme/global/mobile-menu-toggle.js, package-lock.json
Adds focus trapping for mobile nav dropdown
=> Mobile nav dropdown - focusTrap

CHANGELOG.md, assets/js/theme/common/product-details.js, templates/components/products/options/date.html
Jira: [BCTHEME-1870](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1897)
This PR fixes an issue with displaying the correct number of days when a specific date is selected
No Rollout/Rollback
https://github.com/user-attachments/assets/b496f6de-91b1-4a04-ab53-fe10994b19d4
https://github.com/user-attachments/assets/5b4a901a-1c9e-4fdd-8751-c0aad55008c1
[BCTHEME-1870]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront): BCTHEME-1897 Date Field Modifier - February showing 30th and 31st

CHANGELOG.md, templates/components/account/address-list.html
In the address-list.html field, the the company field should be {{}} rather than {{{}}} to prevent an XSS attack
* [BCTHEME-1985](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1985)
**Before:**
**After:** 
[BCTHEME-1985]: https://bigcommercecloud.atlassian.net/browse/BCTHEME-1985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront): BCTHEME-1985 Fix stored XSS within company address field

.github/workflows/pull_request_review.yml, CHANGELOG.md
Fix the GH action that builds Cornerstone by bumping upload-artifact:
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
While I was doing this, I improved the action in other ways:
- Update matrix strategy
- Use modern node versions (18/20)
- Improve artifact naming
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
=> Update GH upload-artifact action to v4 to fix build

CHANGELOG.md, package-lock.json, package.json
This pull requests bumps the @bigcommerce/stencil-utils version to **6.18.0** that allows the dependencies to be resolved with Node v20, that is a minimum requirement for Stencil CLI
- [Issue](https://github.com/bigcommerce/cornerstone/issues/2492)
=> Bump stencil-utils version to 6.18.0

.github/workflows/pull_request_review.yml, CHANGELOG.md
Bump other GH action versions to get rid of warnings related to old node versions
=> Bump other GH actions to stop using old node

CHANGELOG.md, assets/scss/components/stencil/cart/_cart.scss, templates/components/cart/shipping-estimator.html
We are working on a new feature to allow shipping discount to be created on the promotion side and applied to a cart with a selected shipping option.
This ticket is about showing the discount on the cart page and will be composed of 2 tickets:
- a BCApp ticket to return the `discounted_shipping_cost` (https://github.com/bigcommerce/bigcommerce/pull/60385)
- a Cornerstone ticket to update the template using this new variable
This feature is protected behind a LaunchDarkly Experiment and will be slowly ramped up when the feature development is complete. 
- https://bigcommercecloud.atlassian.net/browse/CHECKOUT-8516
Tested using Stencil CLI:
Without Shipping Discount:
With Shipping Discount:
ping @bigcommerce/team-checkout
=> feat(checkout): CHECKOUT-8516 Add Shipping Discount to Cart Page

CHANGELOG.md, templates/components/products/bulk-discount-rates.html
This PR fixes the bulk pricing modal bug on PLP.
**Before**
https://github.com/user-attachments/assets/7fc9ea27-cccc-4d0e-81ad-f7c392ce7564
**After**
https://github.com/user-attachments/assets/6324a214-0d92-46e2-8791-49cb99656b44
=> fix(storefront): BCTHEME-1937 Bulk pricing modal on PLP only displays information for the first product

CHANGELOG.md, templates/components/faceted-search/show-more-facets.html
Product Filter's configured Display Name does not appear on the "Show More" modal window
- [ES-5026](https://bigcommercecloud.atlassian.net/browse/ES-5026)
- related BCAPP PR: https://github.com/bigcommerce/bigcommerce/pull/60722
Changes tested on integration store:
[ES-5026]: https://bigcommercecloud.atlassian.net/browse/ES-5026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ES-5026: Product Filter's configured Display Name does not appear on the "Show More" modal window

CHANGELOG.md, config.json
This PR basically fixes colour value in `config.json` file for `carousel-play-pause-button-textColor`. Previously # was missed  in Settings there that caused issues with showing correct colour in 
- [SD-7619](https://bigcommercecloud.atlassian.net/browse/SD-10726)
locally
[SD-7619]: https://bigcommercecloud.atlassian.net/browse/SD-7619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront): SD-7619 Update colour value for carousel play-pause button

CHANGELOG.md, config.json, schema.json, schemaTranslations.json
This PR fixes adding font weight 700 for the Karla font and removes the italic font style.
This PR is the result of discussion [here](https://github.com/bigcommerce/cornerstone/pull/2396).
- [SD-10894](https://bigcommercecloud.atlassian.net/browse/SD-10894)
https://github.com/user-attachments/assets/d461c609-5225-44f1-a5ed-a9fbe47426ee
[SD-10894]: https://bigcommercecloud.atlassian.net/browse/SD-10894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront): SD-10894 add Karla 700 font weight to schema.json and remove italic versions

CHANGELOG.md, templates/components/common/cart-preview.html
Add a section to display the payment promotion widget in the drop-down of the cart preview.
**(!) This part of the theme is rendered dynamically via an Ajax request. Therefore, we cannot use "regions" for this purpose. It is implemented in the same manner as `cart.additional_checkout_buttons` in the same file (cart-preview.html).**
- [PI-2764](https://bigcommercecloud.atlassian.net/browse/PI-2764)
- [PI-2763](https://bigcommercecloud.atlassian.net/browse/PI-2763)
Use case:
[PI-2764]: https://bigcommercecloud.atlassian.net/browse/PI-2764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PI-2763]: https://bigcommercecloud.atlassian.net/browse/PI-2763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(payment): PI-2764 Add a section to display the payment promotion widget in the drop-down of the cart preview.

CHANGELOG.md, templates/layout/base.html, templates/pages/category.html
This PR removes escaping of `=` symbol for `<head>`, namely for meta prev/next URLs on the Category Page and favicon.
- [SD-10779](https://bigcommercecloud.atlassian.net/browse/SD-10779)
**before:**
https://github.com/user-attachments/assets/f79e6871-e9ff-4175-9a27-84d386861e10
**after:**
https://github.com/user-attachments/assets/f6776a66-6b1e-4521-85c3-bee660536f40
[SD-10779]: https://bigcommercecloud.atlassian.net/browse/SD-10779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront): remove escaping of = symbol for <head>

CHANGELOG.md, assets/js/theme/cart.js, package-lock.json, package.json
Update `cart.js` to use `utils.api.cart.postFormData` when updating variant options from the cart page. Using AJAX gives us more control over which headers are sent.
- [STRF-12475](https://bigcommercecloud.atlassian.net/browse/STRF-12475)
https://github.com/user-attachments/assets/92b63615-652a-4f01-8939-cceb50d8c93e
[STRF-12475]: https://bigcommercecloud.atlassian.net/browse/STRF-12475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(storefront): STRF-12475 Use utils.api.cart.postFormData when updating variants in cart

CHANGELOG.md, templates/components/products/card.html, templates/components/products/list-item.html
Add a region to display the payment promotion widget on the category pages.
- [PI-2771](https://bigcommercecloud.atlassian.net/browse/PI-2771)
- [PI-2770](https://bigcommercecloud.atlassian.net/browse/PI-2770)
See screenshots in the related PR: https://github.com/bigcommerce/bigcommerce/pull/61296
[PI-2771]: https://bigcommercecloud.atlassian.net/browse/PI-2771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PI-2770]: https://bigcommercecloud.atlassian.net/browse/PI-2770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(payment): PI-2771 Add a region to display the payment promotion widget on the category pages.

CHANGELOG.md, templates/components/products/card.html, templates/components/products/list-item.html
Follow up PR for https://github.com/bigcommerce/cornerstone/pull/2530. 
In the previous PR, I added new regions to several shared product components. During testing, it was noticed that these components are injected not only on category pages but also on the product view page (as a list of related products at the bottom). The problem is that the product view page already has a region with the same name. Thus, injecting components with the same region name leads to the multiplication of an existing banner intended for the product details page. This fix is intended to rename the regions introduced in https://github.com/bigcommerce/cornerstone/pull/2530 to avoid unexpected behavior. The old names are not used by any store yet, as they were merged recently.
Add links to any relevant tickets …
=> feat(payment): PI-2771 Rename region for product item.

CHANGELOG.md, templates/pages/blog.html, templates/pages/brand.html
While merging #2526 into our codebase, I noticed that `blog.html` and `brand.html` didn't get the update that removes escaping of = symbol for `<head>` for meta prev/next URLs.
We don't utilize the blog functionality, so I can't provide BEFORE / AFTER screenshots for that change, but here are screenshots for changes to `brand.html`
**BEFORE**
**AFTER**
=> Remove escaping of "=" symbol for <head> for blog and brand

CHANGELOG.md, assets/js/theme/common/product-details-base.js
Updated check for showing/hiding available wallet buttons
- [PAYPAL-5000](https://bigcommercecloud.atlassian.net/browse/PAYPAL-5000)
https://github.com/user-attachments/assets/f31e6916-5ae6-4ad3-9c78-710ffe0a5aca
[PAYPAL-5000]: https://bigcommercecloud.atlassian.net/browse/PAYPAL-5000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(payment): PAYPAL-5000 Quick pay buttons are seen on PDP before 'required' option selection

CHANGELOG.md, assets/js/theme/common/product-details.js, templates/components/products/options/date.html
Update `date.html` and `product_details.js` to remove the space at the stop of date fields and to support multiple date fields per page. 
The ID attributes for date fields cause invalid html when there are multiple date fields on a page due to duplicate IDs.
OPTGROUP under the Day select box causes extra space in Day dropdown.
ready() call is not necessary, there already is a $scope class member which references a containing element.
- [SD-10928](https://bigcommercecloud.atlassian.net/browse/SD-10928)
Before:
https://github.com/user-attachments/assets/722fd1b7-f125-4bbc-a1fc-c8ff849c84a6
After:
https://github.com/user-attachments/assets/4ac37bdd-f018-4bf9-b8e6-98609c6eaf03
[SD-10928]: https://bigcommercecloud.atlassian.net/browse/SD-10928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …
=> fix(storefront): SD-10928 Cornerstone update to support multiple date fields and remove blank space

.github/workflows/pull_request_review.yml
The GitHub Actions workflow currently runs on both Node.js 18.x and 20.x via a matrix strategy.
Recent updates to internal dependencies (specifically `undici`, used by `@bigcommerce/stencil-cli`) require the global File API, which is only available in Node.js 20+.
As a result, all CI jobs running under Node 18.x fail during the stencil bundle step with the error
`Error: Process completed with exit code 1.`
=> chore: remove Node.js 18 from matrix to fix CI build with stencil-cli

CHANGELOG.md, templates/components/account/payment-methods-list.html
Reverts bigcommerce/cornerstone#2572
Stripe will use default `ACH` instrument type, and no need additional logic for `tokenized_ach`  type
=> Revert "feat(payment): STRIPE-987 Add Stripe OCS ACH stored bank accounts type"
